### ISSUE TITLE
Disable bubbling of fire_event

### ISSUE THREAD

**Issue by moll** [watir/watir#161]
Hey,

I noticed an older version of Watir had a bubble attribute to `fire_event`. Why was that removed?

I was just writing a test to test the `paste` event, which on the latest Chrome seems not to bubble. At least it's not caught by jQuery's delegates. But, when doing the same thing with Watir, that is setting the input via JavaScript to not trigger keyups and then `fire_event 'paste'` on that input, jQuery catches that — so it's a false positive.

Disabling bubbling in that case to make sure production code binds _on_ the input and not via delegates, would make writing this test possible. I mean, unless somehow using the fireEvent.js directly that's in Watir's repo.

**Comment by titusfortner** [comment]
After 5+ years no obvious way for us to fix this within the current code; as well as not having an obvious use case for testing actual user interactions on a site, I'm going to close it as "won't fix"
