### ISSUE TITLE
Not able to set value for input text field with type=number

### ISSUE THREAD

**Issue by rtcoms** [watir/watir#272]
Using Watir-webdriver with Firefox. It's not allowing to set value for input textfield with type=number

Below is my html element

```
<input id="payment_amount_as_float" type="number" value="0" style="width: 
200px;"step="any"name="payment[amount_as_float]"></input>
```

Output from my watir script :

```
irb(main):041:0> browser.text_field(:id,"payment_amount_as_float")
    => #<Watir::TextField:0x48127438 located=false selector={:id=>"payment_amount_as_float",   
    :tag_name=>"input or textarea", :type=>"(any text type)"}>
irb(main):042:0> browser.text_field(:id,"payment_amount_as_float").set(200) 
    => ""
```

As you can see, it is not setting the value to 200 and returns "". I tried with set("200"), value=(200), value=("200"), append("200"), append(200), but none of those worked

**Comment by dideler** [comment]
I'm having similar issues when not running headless.

```ruby
browser.text_field(id: 'transfer_in_amount').set(amount)
# amount is 2000, but field gets value 200
```

However, if I set the amount twice, it sets the correct value the second time.
```ruby
2.times { browser.text_field(id: 'transfer_in_amount').set(amount) }
```

Using Firefox 41.0.2 and watir-webdriver 0.9.1.

@jarib what's the best way to report this issue? Create a new one here or on Google Code?

**Comment by jarib** [comment]
Create a new one here and one of the current maintainers will take a look at it.
