### ISSUE TITLE
Different exist/visible results for string and regexp

### ISSUE THREAD

**Issue by titusfortner** [watir/watir#342]
From conversation in [PR 65](https://github.com/watir/watirspec/pull/65)

A selector of {text: String} is translated into an xpath selection and returns the first text node that contains the string, or the top-most text node if the text value is inside a nested text node. If a node that contains the text is nested inside the selected node and has the display set to "none," #visible? will return true, even when false.

A selector of {text: Regexp} gathers an array of WebDriver::Element and iterates through it to match the regular expression with the Element#text of each element. Since #text only returns what is visible on the page, it will return false to #exists? where a String match would return true.

I'm not sure which behavior should match which. I'm leaning toward the Regexp approach of returning false for #exists? if it is not visible on the page, even if it is in the DOM. I can write a spec if we agree this is desired behavior.

**Comment by p0deje** [comment]
As far as I know, it's not possible to make XPath/CSS expression that would consider visibility of node. With that said, I don't think we can make the behavior with String/Regexp consistent at all.

Do you have any ideas on how to implement it?

**Comment by titusfortner** [comment]
I'm not sure how sizzle would work.

Couldn't we just implement text matching the same way we do regexp matching? Something like:

```ruby
      txt_selector = selector.delete :text
      how, what = build_wd_selector(selector)
      elements = parent.find_elements(how, what)
      elements.__send__(method) { |el| el.text == txt_selector }
```

**Comment by p0deje** [comment]
Should it be applied for `:text` only? What about other attributes? I feel like there are other cases like this.

It will also make text selector so much slower than it is now. As a heavy user of `:text`, I'm not a great fan of performance degradation.

**Comment by titusfortner** [comment]
I... don't think this applies to other attributes? Let me consider it after I get some sleep.

Regarding performance, you definitely make a good point. Our regexp implementation is *slow, and that makes sense if you are doing a #text call for every matching element (e.g. every div on a page, etc). Maybe we can make one extra call if it is specifically a text selector just to verify it is present. 

```Ruby
        idx ||= 0
        el = @wd.find_elements(how, what)[idx]
        el == nil if selector.key?(:text) && el.text != selector[:text]
```
