### ISSUE TITLE
Screenshot#save should validate file extension

### ISSUE THREAD

**Issue by jarmo** [watir/watir#400]
Currently this code works:

``` ruby
browser.screenshot.save "foobar.jpg"
```

The problem is, however, that (at least with chrome-driver) the screenshot will be saved in `png` format instead. I'm not sure if it differs between drivers, but I suggest either to add extension validation into `watir-webdriver` or convert files into proper format in the end.

Code above caused me many problems in different software - for example even `Photoshop CC 2015` didn't open that kind of files because it thought it is `jpg` although it was a `png` and `GoPro Studio` just crashed.

Yes, all this software could be smarter, but to avoid that kind of a problem we could have a safe-guard in `watir-webdriver`.

`watir-classic` for example does use `win32screenshot` to take screenshots and it will validate extensions and save screenshots into different formats depending of the given extension (`jpg` is among of these formats).

Thoughts?

**Comment by p0deje** [comment]
What if we just force-add png to the end of extension unless it was given?

In any case, need to check what WebDriver spec says about screenshot formats.

**Comment by jarmo** [comment]
I'm not sure this would be a good solution because then we change user specified parameter implicitly. Better would be to raise an Exception so it will be explicitly changed and fixed for forever. Then it's also similar to `watir-classic`, which would raise an Exception if unsupported extension is provided.

**Comment by abotalov** [comment]
This has been handled in Selenium - https://github.com/SeleniumHQ/selenium/pull/4157
