### ISSUE TITLE
Update Watirwebdriver.com for Chrome download issue

### ISSUE THREAD

**Issue by JHFirestarter** [watir/watir#421]
Gents, would you please update the **Chrome** section of https://watirwebdriver.com/browser-downloads for the answer below, re: changing default browser download directory?

http://stackoverflow.com/questions/33224614/downloading-files-with-watir-webdriver

Assuming it is correct.

**Comment by JHFirestarter** [comment]
FWIW, I think Undo's answer is far simpler

**Comment by titusfortner** [comment]
Adding this to website tracker: https://github.com/watir/watir.github.io/issues/51
