### ISSUE TITLE
Repo Conversion

### ISSUE THREAD

**Issue by titusfortner** [watir/watir#437]
This process is mostly complete. I think we need to wait on a final release of 6.0 before we release gems for watir-classic & watir-webdriver.

If anyone sees any issues with where things are right now, let's get them addressed.
1. ~~ww_note: create new repo about watir-webdriver repo moving~~
2. ~~watirspec: Merge watirspec/#84~~
3. ~~watir-webdriver: get all Specs Passing with #395~~
4. ~~watir-webdriver: merge #395~~
5. ~~watir: update Readme that it is deprecated~~
6. ~~watir: rename to watir_meta~~
7. ~~watir-webdriver: rename to watir~~
8. ~~watirspec: verify links watir vs watir-webdriver~~
9. ~~watir.github.io: update links to watir~~
10. ~~ww_note: rename to watir-webdriver~~
11. ~~water-classic: update Readme & gemspec that it is deprecated~~
12. ~~Release 6.0 beta on rubygems~~
13. ~~watir.github.io: post about 6.0 beta~~
14. ~~[PROMOTE](https://twitter.com/titusfortner/status/762053171707469824) RELEASE!~~
15. ~~Steak!~~
16. ~~Wait for Selenium 3.0 Release~~
17. ~~Release 6.0 production on rubygems~~
18. ~~Release final watir-webdriver 0.9.9 on rubygems~~
19. ~~Release final water-classic 4.3.1 on rubygems~~
20. More Steak!

**Comment by titusfortner** [comment]
@p0deje something I did broke yardoc again. Something about the browser_name it doesn't like, but I don't know what might have changed.

**Comment by ghost** [comment]
Not sure if this is the right place to put this, but the blog domain at https://watirwebdriver.com/ has expired...which is like the opposite of task item 14!

**Comment by titusfortner** [comment]
Thanks, yes, @bret is going to renew it, but the plan is to redirect the domains for both watir.com & watirwebdriver.com to the new website: http://watir.github.io

**Comment by titusfortner** [comment]
A few other things I'd like to add as either part of this issue or for our future conversations on our Roadmap:
1. Update our [wikipedia entry](https://en.wikipedia.org/wiki/Watir) with more accurate description of the history and current state of the project.
2. Update Stackoverflow tags: for [watir-webdriver info](http://stackoverflow.com/tags/watir-webdriver/info), [watir info](http://stackoverflow.com/tags/watir/info), [watir-webdriver synonyms](http://stackoverflow.com/tags/watir-webdriver/synonyms), and [watir synonyms](http://stackoverflow.com/tags/watir/synonyms)
3. Update [watir-general](https://groups.google.com/forum/#!forum/watir-general) links
4. Identify places where we can update links that are currently pointing to the old repo.

**Comment by Inglonias** [comment]
It appears that Selenium 3.0 has been released out of beta now.

Is it update and/or steak time yet?

**Comment by titusfortner** [comment]
@Inglonias - we are very close. We decided we want to merge in #479 first. It should be very soon.

**Comment by Inglonias** [comment]
Alright. #479 has been merged. What happens now?

Is it steak?

**Comment by titusfortner** [comment]
Yes, now it is time for steak. :) https://twitter.com/titusfortner/status/796410569972711424
