### ISSUE TITLE
Cannot clear react controlled inputs

### ISSUE THREAD

**Issue by qsorix** [watir/watir#438]
Observed on watir 0.8.0, page-object 1.1.1, react 15.2.1

React [controlled](https://facebook.github.io/react/docs/forms.html#controlled-components) inputs are confused by watir's default implementation that uses
element.clear. The 'clear' method clears DOM element without triggering events,
so react never learns that the element was cleared. Any rerender makes the value
reappear.

On next key presses, it only learns that a new letter was added and it resumes
working using its last known value.

```
> text_field.value
=> "foo"

> text_field.clear
=> nil

> text_field.value
=> ""

> text_field.set('bar')
=> nil

> text_field.value
=> "foobar"
```

A workaround is to clear input using backspace. `send_keys` do generate
events and react is happy.

I think that the implementation of `.clear` need to generate events as well.
Maybe select-all, followed by a backspace -- I guess that's the way users would
clear an input.

**Comment by p0deje** [comment]
Watir proxies clear command to Selenium, so this issue should be report in [its issue tracker](https://github.com/SeleniumHQ/selenium/issues).

**Comment by qsorix** [comment]
Thank you! Turns our there's an issue about it already https://github.com/SeleniumHQ/selenium/issues/2316

**Comment by p0deje** [comment]
:+1:

**Comment by titusfortner** [comment]
Just a note, you can use `#send_keys` to enter text without it first making a `clear` call.
