### ISSUE TITLE
Several links are not returning the intended pages

### ISSUE THREAD

**Issue by evanniedojadlo** [watir/watir#439]
URL:
http://watir.github.io/contributing/

The following links are not returning the intended pages:

"issue"
https://github.comwatir/watir/issues

"pull request"
https://github.comwatir/watir/pulls

"our webpage"
https://github.com/waitr/watir.github.io

**Comment by titusfortner** [comment]
Fixed: https://github.com/watir/watir.github.io/commit/b571af
Thanks for bringing these to our attention!
