### ISSUE TITLE
Validating Elements found #by_id

### ISSUE THREAD

**Issue by titusfortner** [watir/watir#442]
We don't validate that an element we locate by id is of the type we specify.

All of these return true for a specific:

```
browser.div(id: 'foo').exists?
browser.span(id: 'foo').exists?
browser.iframe(id: 'foo').exists?
browser.text_field(id: 'foo').exists?
```

Is there a reason we decided to short circuit the validation for id's?

**Comment by p0deje** [comment]
Guess it's just for performance reasons. We can probably change it so that it validates all the time.

**Comment by titusfortner** [comment]
Oh, this was a bug and #467 fixed this, good to close
