### ISSUE TITLE
Merge WatirSpec into Watir

### ISSUE THREAD

**Issue by titusfortner** [watir/watir#443]
We've discussed the difficulties of using a submodule to write tests for PRs.
@Rodney-QAGeek had this issue when doing his first PR, and [westlakem mentions it here](https://github.com/watir/watir/pull/387#issuecomment-159382480)

@p0deje mentioned he'd like to do this in a way that other projects can still access it if necessary.

Depending on how complicated the solution is, we may also need a tutorial on how to write PRs.

**Comment by p0deje** [comment]
I'm willing to work on this, not sure when I'll start though :)

**Comment by titusfortner** [comment]
I also want to make sure that the solution we pursue solves the underlying problem. For instance, Capybara puts a bunch of their specs [inside their lib](https://github.com/jnicklas/capybara/tree/master/lib/capybara/spec), but these are really difficult to run the way I'm used to (one test at a time). It's kind of an all-or-nothing approach to running their selenium specs. While a submodule is a pain to set up, once it is set up, it's much easier to work with than what I'm seeing of Capybara's solution.

**Comment by abotalov** [comment]
You can add an rspec tag if you want to run a particular Capybara test (or some of them).

**Comment by titusfortner** [comment]
Maybe I just found it difficult getting it to work with Rubymine the last time I tried.

**Comment by titusfortner** [comment]
@abotalov - Is there an example somewhere of how to run specific selenium specs in the capybara repo? I couldn't find anything online.

**Comment by abotalov** [comment]
I noticed that answer was already given here - https://github.com/jnicklas/capybara/pull/1744#issuecomment-244249665 :-)

**Comment by p0deje** [comment]
Oh, this is now done 😄
