### ISSUE TITLE
CONTRIBUTING.md file

### ISSUE THREAD

**Issue by titusfortner** [watir/watir#449]
Most projects have one of these, Watir should too.
(See [Selenium's](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md) as an example)

**Comment by p0deje** [comment]
@titusfortner Do you want me to take care of that?

**Comment by titusfortner** [comment]
I can't figure out how to add it to the project list, but this one isn't a priority for me right now. :)

**Comment by titusfortner** [comment]
tbh not a priority
