### ISSUE TITLE
IFrame text

### ISSUE THREAD

**Issue by titusfortner** [watir/watir#450]
The Principle of Least Astonishment would say that doing this:

`browser.iframe(id:'foo').text`

Should return the text inside the iframe. This would mean switching frames and returning the text when this element is called.

Reference: http://stackoverflow.com/questions/39298529/copy-and-print-text-inside-iframe-by-watir-webdrive

**Comment by jkotests** [comment]
This should already be working in Watir(-Webdriver) v0.9.2 and above. It was fixed in Issue #413.

**Comment by titusfortner** [comment]
Damn, and I even wrote that code only a couple months ago. sigh. Thanks @jkotests for being more on the ball with this. :)
