### ISSUE TITLE
Add deprecated watir_meta gem methods

### ISSUE THREAD

**Issue by jarmo** [watir/watir#471]
I'm trying out watir 6.0.0.beta4 on my real-life project where watir 5 was used.

First thing I noticed is that previous watir gem methods do not exist as a deprecated methods.

For example, I have this in my code:

``` ruby
Watir.driver = :webdriver
```

I suggest adding methods `Watir.driver` and `Watir#driver=` to Watir 6 as a deprecated methods so everything would not blow up, but migration path would be easier with a deprecation warning message.

Looking at the public [API methods](https://github.com/watir/watir_meta/blob/master/watir/lib/watir/loader.rb) of previous gem I don't see that there's any other methods which should get a deprecation warning.

**Comment by p0deje** [comment]
Should these methods only contain deprecation message or some other logic too?

**Comment by jarmo** [comment]
If you mean only `driver` and `driver=` then I'm not sure. Maybe just a message?

**Comment by titusfortner** [comment]
`Watir.driver` wouldn't actually do anything in Watir 6.0, so a deprecation notice / `Kernel#warn` makes sense to me.

**Comment by titusfortner** [comment]
Well shoot... somehow I ignored this for 2 years, and now I think it's probably no longer an issue, especially since it is just a matter of deleting the line and not changing to something else.
