### ISSUE TITLE
Browser#initialize does not take arguments anymore?

### ISSUE THREAD

**Issue by jarmo** [watir/watir#472]
I'm trying out watir 6.0.0.beta4 on my real-life project where watir 5 was used.

This code blows up:

``` ruby
$browser = Watir::Browser.new :chrome

# ArgumentError:
#       wrong number of arguments (1 for 0)
```

Didn't see this breaking API change in [CHANGES](https://github.com/watir/watir/blob/master/CHANGES.md) nor is there any information in the README about switching browsers.

If API has changed then I suggest adding arguments support back with a deprecation message and add a browser switching API example to the README.

**Comment by jarmo** [comment]
Closing this because problem seems to be caused by some other third party gems.

**Comment by trobrock** [comment]
@jarmo did you identify the issue?

**Comment by jarmo** [comment]
Can't remember anymore. Sorry.

**Comment by titusfortner** [comment]
@trobrock check your `Gemfile.lock` and make sure there are no references to outdated packages like watir-classic or commonwatir.
