### ISSUE TITLE
Add watir related gems back to README

### ISSUE THREAD

**Issue by jarmo** [watir/watir#476]
Previously README included Watir related projects such as [watir-rspec](https://github.com/watir/watir-rspec), [watir-rails](https://github.com/watir/watir-rails), [test-page](https://github.com/jarmo/test-page) and many others.

Currently nothing like that exists in the README. Wouldn't it be good to add them back so that people using Watir would not spend too much time for getting it working within Rails, RSpec or any other eco-system?

**Comment by titusfortner** [comment]
Yes, we should do this. Also tracked here: https://github.com/watir/watir.github.io/issues/52
