### ISSUE TITLE
set functionality is not working in IE browser version 11 for text_field 

### ISSUE THREAD

**Issue by ambikashri** [watir/watir#487]
I am trying to login to a page having the below html code

`<div class="login-container">

```
<form action="/cs/oss_login.html" name="loginForm" method="post">
    <input type="hidden" value="http://testpage.com/" name="test_redirect">
    <h3 class="login-header">Login to OSS</h3>
    <label><input type="text" placeholder="Username" maxlength="32" value="" name="test_UserName" class="login-input"></label>
    <label><input type="password" placeholder="Password" maxlength="20" value="" name="test_Password" class="login-input"></label>
    <input type="submit" class="btn" value="Login" name="oss_Login">
</form>
```

<div class="subtext">Access to this page is restricted to authorized employees and contractors of <a href="http://www.test.com">Tested
</a>. If you need access (or additional access), please contact your manager.</div>

</div>`

My ruby watir code to login is as below

`if (browser.name.to_s == 'internet_explorer' and browser.a(:id=>'overridelink').exists?)
                browser.a(:id=>'overridelink').when_present.click
            end

```
        browser.wait_until(60){
            browser.div(:class, 'login-container').present?
        } rescue nil

        browser.text_field(:name, 'test_UserName').when_present.set('abc')
        browser.text_field(:name, 'test_Password').when_present.set('abc123')

        browser.button(:value, 'Login').when_present.click`
```

This code sets the text field with values in chrome and firefox, but it fails to insert text incase of IE11. 

I am using the below setup
IE version 11
Selenium webdriver 2.53.1
watir (5.0.0)
watir-webdriver(0.9.3)

Also note this issue is seen only when I am running the selenium hub and node in the background.

**Comment by p0deje** [comment]
Can you please provide a test script that we could run to debug the problem? I'm pretty sure that might be Selenium bug, but let's take a look first.

**Comment by titusfortner** [comment]
@ambikashri if this is still an issue please provide reproducible test case or at least logs (`Selenium::WebDriver.logger.level = :info`), and we can reopen.
