### ISSUE TITLE
Watir Webdriver is very slow in execution

### ISSUE THREAD

**Issue by pgundlupetvenkatesh** [watir/watir#488]
Hi,
So far I was using Watir-classic for all the testcases to execute. Recently to handle Windows Model dialog I had to switch to Watir-WebDriver 0.9.1 which is executing extremely slow. I am using IEDriverServer 2.53.1 32bit, I even tried with x64bit, but the speed didn't seem to change. Is there something I am missing to make it run fast? BTW I am using IE11.

**Comment by titusfortner** [comment]
The IE Driver is indeed slower than watir-classic, and there isn't much that can be done. Microsoft's implementation of W3C spec compatible driver for Edge should improve things for Microsoft users; but that's Windows 10 only.
