### ISSUE TITLE
text not showing up in  javascript prompt text field in Chrome using  alert.set(value) 

### ISSUE THREAD

**Issue by jaytest1** [watir/watir#489]
A javascript prompt has a field where text should be entered. Tried using alert.set('text to enter'). The alert.set(value) method works fine with IE, but not chrome. alert.ok and alert.close work fine in Chrome. 

This may related to chromedriver/chrome interaction. I'm using the latest chromedriver stable release 2.24

Not sure how to tell if this related to chromedriver or watir.

**Comment by titusfortner** [comment]
Please provide a reproducible example. The test at the bottom of this page is passing in all environments: https://github.com/watir/watir/blob/master/spec/watirspec/alert_spec.rb

**Comment by jaytest1** [comment]
`require 'watir'

driver = Watir::Browser.new :chrome

driver.goto('http://www.w3schools.com/js/tryit.asp?filename=tryjs_prompt')

driver.iframe(:id => 'iframeResult').button.click

driver.alert.set('blah')`

**Comment by p0deje** [comment]
I can reproduce the error using the script provided, need to write a spec now.

**Comment by titusfortner** [comment]
This is a bug in chromedriver: https://bugs.chromium.org/p/chromedriver/issues/detail?id=1120

It is worth noting that Chrome does in fact get the text update (so the resulting value on the page is correct), it just does not display in the alert box.
