### ISSUE TITLE
Upload Method on Form

### ISSUE THREAD

**Issue by titusfortner** [watir/watir#490]
What do we think about adding `#upload(../relative/path/file)` to the form element? It would find the file_field and do a `File#expand_path` by default.

**Comment by p0deje** [comment]
Is that a problem to do the same manually?

**Comment by titusfortner** [comment]
No, but I've had two users have questions/problems with it this week, so I
was trying to think of something that might make it more convenient.

**Comment by p0deje** [comment]
I think that can be handled on page object level with something like:

``` ruby
class Page
  form :profile, class: 'profile' do
    text_field :name, class: 'name'
    file_field :photo, class: 'photo'
    button :submit, class: 'submit'
  end
end

page = Page.new
page.profile = {name: 'Alex', photo: '../photo.jpg'}
```

I believe this is not Watir responsibility.

**Comment by titusfortner** [comment]
Agreed.
