### ISSUE TITLE
[WATIR 6.0] Odd warning related to new waiting logic

### ISSUE THREAD

**Issue by azohra** [watir/watir#492]
We are seeing the warning ```Instead of passing arguments into Wait#until method, use keywords``` when calling  ```page_ready_element.wait_until { |el| el.present? }```

We understand the warning is about using timeout/message keys when calling wait_until, but as you can see we are only passing a block. Are we correct in understanding that timeout/message are optional? 

It could be that the `page-object` gem is getting in the way somehow as we are accessing the watir element through its `_element` method.

**Comment by titusfortner** [comment]
Yeah, I found another bug running page object specs, it might be related, but I'll check. Can you attach a stack trace?

**Comment by azohra** [comment]
@titusfortner - we just get the warning. We did a pry session to isolate the behaviour and ensure no other bad code was generating this warning.

See below, 100% reproduction rate with page object element calls.

```
18: def initialize_page
 => 19:   binding.pry
    20:   page_ready_element.wait_until { |el| el.present? }
    21: end

[1] pry(#<Home>)> page_ready_element.wait_until { |el| el.present? }
Instead of passing arguments into Wait#until method, use keywords
=> true
[2] pry(#<Home>)>
```

**Comment by azohra** [comment]
@cheezy & @daneandersen just for visibility.

**Comment by titusfortner** [comment]
@tk8817 Firstly, I can't figure out how to easily reproduce this, and secondly only watir-webdriver should be supported by current page-object gem.

**Comment by azohra** [comment]
We made the transition on a fork a month back - I will wait to see what cheezy has cooking before opening any new issues. However, aside from this we have been having no troubles.
