### ISSUE TITLE
[WATIR 6.0] Add ability to set default wait timeout 

### ISSUE THREAD

**Issue by azohra** [watir/watir#493]
Hey @titusfortner,

was wondering if we could take a similar approach to `page-object` and make the default timeout configurable. This would be preferable over custom setting 45 or 60 seconds for ever wait_until block.

E.g 

```
Watir.default_element_wait = 60
```

**Comment by titusfortner** [comment]
Yes, it uses `Watir.default_timeout`
The default is 30 seconds
Let me know if there's something else you're looking for here.

**Comment by azohra** [comment]
Ack, did not see any notes in the new documentation, I must have missed it. Cheers.
