### ISSUE TITLE
file_field requiring to be present to be able to manipulate and add files to it

### ISSUE THREAD

**Issue by vinchbr** [watir/watir#497]
Watir is expecting for the element to be present, but file fields can be hidden.

So `set` on a file field as a workaround for making file uploads breaks

StackTrace:
> Watir::Exception::UnknownObjectException
    element located, but timed out after 30 seconds, waiting for true condition on {:id=>"upload", :tag_name=>"div"} --> {:name=>"files", :tag_name=>"input", :type=>"file"}
    /Users/vnaves/.rubies/ruby-2.1.7/lib/ruby/gems/2.1.0/gems/watir-6.0.2/lib/watir/elements/element.rb:528:in `rescue in wait_for_present'
    /Users/vnaves/.rubies/ruby-2.1.7/lib/ruby/gems/2.1.0/gems/watir-6.0.2/lib/watir/elements/element.rb:518:in `wait_for_present'
    /Users/vnaves/.rubies/ruby-2.1.7/lib/ruby/gems/2.1.0/gems/watir-6.0.2/lib/watir/elements/element.rb:535:in `wait_for_enabled'
    /Users/vnaves/.rubies/ruby-2.1.7/lib/ruby/gems/2.1.0/gems/watir-6.0.2/lib/watir/elements/element.rb:547:in `wait_for_writable'
    /Users/vnaves/.rubies/ruby-2.1.7/lib/ruby/gems/2.1.0/gems/watir-6.0.2/lib/watir/elements/element.rb:658:in `element_call'
    /Users/vnaves/.rubies/ruby-2.1.7/lib/ruby/gems/2.1.0/gems/watir-6.0.2/lib/watir/elements/element.rb:306:in `send_keys'
    /Users/vnaves/.rubies/ruby-2.1.7/lib/ruby/gems/2.1.0/gems/watir-6.0.2/lib/watir/elements/file_field.rb:24:in `value='
    /Users/vnaves/.rubies/ruby-2.1.7/lib/ruby/gems/2.1.0/gems/watir-6.0.2/lib/watir/elements/file_field.rb:13:in `set'

**Comment by vinchbr** [comment]
Verified it works with `0.9.1`
it returns false for `hidden? present? visible?`

**Comment by titusfortner** [comment]
per Slack conversation this also works for him:
`browser.file_field(:name, 'files').wait_until(&:exists?).wd.send_keys(File.expand_path(file_path))`

**Comment by p0deje** [comment]
@titusfortner Can you take care of this?

**Comment by bendizen** [comment]
I'm seeing a similar issue with textarea.  We used to be able to set text via send_keys on a textarea that wasn't present.  I verified it works in 0.9.9 and does not in 6.03.   Should I file a separate issue?

**Comment by titusfortner** [comment]
@mkarlovich - If you could do that, then it was a bug. Watir is designed to interact with a page like a user. If the field is not visible, it is designed not to allow you to interact with it.

**Comment by titusfortner** [comment]
@vinchbr - can you provide the sample page & code for this? Looking over [displayedness in the w3c spec](https://w3c.github.io/webdriver/webdriver-spec.html#element-displayedness), it says nothing about a form field being exempt (like options and optgroup). I'd be curious to know why Selenium sees it but Watir does not, since the code should be checking the same things.

**Comment by vinchbr** [comment]
I will as soon as I have time to 'hide' any sensitive information from business

**Comment by vinchbr** [comment]
https://gist.github.com/vinchbr/d7455ec6c20bbb7c3f3141e690b60190

**Comment by louis-json** [comment]
I've run into this issue as well interacting with a file_field that has the CSS property `visibility: hidden`. Worked fine in versions prior to 6.0.

I was able to work around the problem by doing this:
```
 Watir.relaxed_locate = false
 browser.iframe(:id => 'filepicker_dialog').file_field(:index =>0).wait_until(&:enabled?).set(filename)
 Watir.relaxed_locate = true
```

**Comment by titusfortner** [comment]
Does that work for Firefox with geckodriver? Or are you using it with Chrome?

**Comment by vinchbr** [comment]
I am using it with chrome
now that snippet I haven't tested by it self

**Comment by louis-json** [comment]
@titusfortner The snippet I pasted works with Chrome. Haven't tested in Firefox.

**Comment by djwgit** [comment]
the relaxed_locate workaround works for latest chrome and firefox (51+), 
btw, the it does not work for watir6.1 + firefox(v45) (kind of need ff45 for an another issue not fixed in watir6.1+ff51)

**Comment by titusfortner** [comment]
I was able to reproduce this error. It works in Firefox, but not in Chrome, so I filed a chromedriver bug:
https://bugs.chromium.org/p/chromedriver/issues/detail?id=1713

The question, @p0deje, is whether we should code a workaround for this, since it is going to be a common use case, and who knows when/if Google will fix it.

**Comment by p0deje** [comment]
I'm not really sure that's a ChromeDriver bug. From a user perspective, the input is invisible and that's a common case for uploader - user interacts with some UI and hidden input is populated with JavaScript.

My best idea is to actually check for input **existence**, not **presence** for file fields.

**Comment by titusfortner** [comment]
This was fixed: https://github.com/watir/watir/commit/a039ef91794dd1932349acfb400c9f7e61f26455

**Comment by djwgit** [comment]
@titusfortner, is this fixed for chrome?
- latest chrome 57.0.2987.133 (64-bit)
- watir 6.2.1
- chromedriver 2.29

try this page: https://tympanus.net/Tutorials/CustomFileInputs/
```
require 'watir'
browser= Watir::Browser.new :chrome
browser.goto("https://tympanus.net/Tutorials/CustomFileInputs/")
file_path="./path/myfile.png"
# Watir.relaxed_locate = false   # without this workaround, could not send_keys to the invisible field_field
browser.file_fields[0].send_keys(file_path)   # does not work 
```
thanks...

**Comment by titusfortner** [comment]
You need to use `file_field` it doesn't work with just `inputs[0]`

**Comment by djwgit** [comment]
@titusfortner thanks for the quick reply, 
file_field does not work either, code updated above.  it works when setting relaxed_locate to false...
updated chromedriver to latest 2.29 (same...)

could you try the code above, not sure if I missed something...   thanks...

**Comment by ArunKarra01** [comment]
Im trying to upload file
  @browser.file_field(id: 'uploadFile').set file_path, but not working. Is there any expertise in Ruby/Watir who can help me please.

**Comment by Rajagopalan-M** [comment]
Ask the question in stackoverflow by tagging watir. This is GitHub which is to raise an issue and pull the request for new features.
