### ISSUE TITLE
Google returns empty page when using PhantomJS

### ISSUE THREAD

**Issue by jaimeiniesta** [watir/watir#498]
I have a script that uses Watir to log in a Google account. It works fine when using `Watir::Browser.new :firefox`, but if I use a headless browser like in the script below, it just returns an empty page.

```ruby
capabilities = Selenium::WebDriver::Remote::Capabilities.phantomjs("phantomjs.page.settings.userAgent" => "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.98 Safari/537.36")
driver       = Selenium::WebDriver.for :phantomjs, desired_capabilities: capabilities
browser      = Watir::Browser.new(driver)
browser.goto('https://accounts.google.com/ServiceLogin#identifier')
browser.html
# "<html><head></head><body></body></html>"
```

If I try this same script with any other URL it works fine:

```ruby
capabilities = Selenium::WebDriver::Remote::Capabilities.phantomjs("phantomjs.page.settings.userAgent" => "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.98 Safari/537.36")
driver       = Selenium::WebDriver.for :phantomjs, desired_capabilities: capabilities
browser      = Watir::Browser.new(driver)
browser.goto('https://github.com')
browser.html
# "<!DOCTYPE html><html lang=\"en\" class=\" is-copy-enabled emoji-size-boost is-u2f-enabled\"> (...)"
```

It doesn't raise any error, it just quickly returns the empty page HTML as above.

How can I debug this? Is there any way to see the status code in the server response? I guess the visit is being rejected, but I don't know why.

Thanks!

**Comment by jaimeiniesta** [comment]
Using ngrok I've verified that the request this makes includes the specified User-Agent:

```
GET / HTTP/1.1
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.98 Safari/537.36
Accept-Encoding: gzip, deflate
Accept-Language: es-ES,en,*
```

**Comment by jaimeiniesta** [comment]
I'm using the latest `selenium-webdriver` (3.0.1).

**Comment by jaimeiniesta** [comment]
Forget it, it works fine if I just use `Watir::Browser.new :phantomjs` - without all that capabilities and driver ceremony.

**Comment by titusfortner** [comment]
@jaimeiniesta yeah those capabilities looked other-than-what-I'm-used-to, but I've done nothing with AppleWebKit so far. 

Oh you were using it as user agent, I see. I've not worked with that either.

**Comment by jaimeiniesta** [comment]
Reopening this as I could make it work when visiting http://google.com - but this keeps failing:

```ruby
browser = Watir::Browser.new :phantomjs
browser.goto('https://accounts.google.com/ServiceLogin#identifier')
browser.html
# "<html><head></head><body></body></html>"
```

I'm using phantomjs 2.0.0 in OSX Sierra.

But it works fine in Heroku with phantomjs 2.1.1...

**Comment by titusfortner** [comment]
This works for me with phantomjs 2.1.1 in Sierra. 

So I think the answer is to upgrade phantomjs. (or don't use phantomjs because it is very rarely the best choice). :)

**Comment by jaimeiniesta** [comment]
Cool, I just checked with phantomjs 2.1.1 it works fine in Sierra.

What do you mean with phantomjs not being the best choice? What headless browser capable of JS do you recommend? Thanks!

**Comment by titusfortner** [comment]
Depends on your platform and your reason for using headless.
But ghostdriver code in phantomjs hasn't been maintained in several years now, and it isn't any faster in most circumstances than chromedriver. 
If you are running it on a machine that doesn't have a gui, then using xvfb with a real browser is definitely a better choice.

**Comment by jaimeiniesta** [comment]
Thanks, I want to use it in Heroku, that's why it must be headless.

**Comment by titusfortner** [comment]
You can use xvfb on heroku.

**Comment by jormon** [comment]
@jaimeiniesta Check out these demo apps if you're interested in using headless or xvfb on heroku.  I'm using chrome, which may not be a fit if you require firefox, but maybe they will help?

https://github.com/jormon/minimal-chrome-on-heroku-xvfb
https://github.com/jormon/minimal-chrome-on-heroku
