### ISSUE TITLE
Stale element error not being rescued causes Watir tests to crash

### ISSUE THREAD

**Issue by pjdjr** [watir/watir#504]
Watir no longer rescues some stale element errors, which can lead to tests crashing.

Here is line 72 from one of our tests (called PreferencesCreateDeleteUser.rb as seen in the stack trace):

`browser.div(:class, 'blockUI blockOverlay').wait_while_present`

This formerly worked with Watir-Webdriver, but because not all stale element errors are being rescued by the new Watir, this line of code is frequently (but not always) causing the test to crash with the stack trace shown below.

`[WARN] 12:13:57 PM :: Selenium::WebDriver::Error::StaleElementReferenceError exception occurred in session: stale element reference: element is not attached to the page document
  (Session info: chrome=54.0.2840.100)
  (Driver info: chromedriver=2.25.426924 (649f9b868f6783ec9de71c123212b908bf3b232e),platform=Linux 3.13.0-57-generic x86_64)
[WARN] 12:13:57 PM :: exception stacktrace:
/home/pj/.rvm/gems/ruby-2.3.0/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/remote/response.rb:69:in `assert_ok'
/home/pj/.rvm/gems/ruby-2.3.0/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/remote/response.rb:32:in `initialize'
/home/pj/.rvm/gems/ruby-2.3.0/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/remote/http/common.rb:81:in `new'
/home/pj/.rvm/gems/ruby-2.3.0/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/remote/http/common.rb:81:in `create_response'
/home/pj/.rvm/gems/ruby-2.3.0/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/remote/http/default.rb:86:in `request'
/home/pj/.rvm/gems/ruby-2.3.0/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
/home/pj/.rvm/gems/ruby-2.3.0/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/remote/bridge.rb:653:in `raw_execute'
/home/pj/.rvm/gems/ruby-2.3.0/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/remote/bridge.rb:631:in `execute'
/home/pj/.rvm/gems/ruby-2.3.0/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/remote/bridge.rb:579:in `element_displayed?'
/home/pj/.rvm/gems/ruby-2.3.0/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/common/element.rb:191:in `displayed?'
/home/pj/.rvm/gems/ruby-2.3.0/gems/watir-6.0.2/lib/watir/elements/element.rb:386:in `visible?'
/home/pj/.rvm/gems/ruby-2.3.0/gems/watir-6.0.2/lib/watir/elements/element.rb:410:in `present?'
/home/pj/.rvm/gems/ruby-2.3.0/gems/watir-6.0.2/lib/watir/wait.rb:71:in `block in while'
/home/pj/.rvm/gems/ruby-2.3.0/gems/watir-6.0.2/lib/watir/wait.rb:89:in `block in run_with_timer'
/home/pj/.rvm/gems/ruby-2.3.0/gems/watir-6.0.2/lib/watir/wait/timer.rb:19:in `block in wait'
/home/pj/.rvm/gems/ruby-2.3.0/gems/watir-6.0.2/lib/watir/wait/timer.rb:18:in `loop'
/home/pj/.rvm/gems/ruby-2.3.0/gems/watir-6.0.2/lib/watir/wait/timer.rb:18:in `wait'
/home/pj/.rvm/gems/ruby-2.3.0/gems/watir-6.0.2/lib/watir/wait.rb:88:in `run_with_timer'
/home/pj/.rvm/gems/ruby-2.3.0/gems/watir-6.0.2/lib/watir/wait.rb:71:in `while'
/home/pj/.rvm/gems/ruby-2.3.0/gems/watir-6.0.2/lib/watir/wait.rb:151:in `wait_while'
/home/pj/.rvm/gems/ruby-2.3.0/gems/watir-6.0.2/lib/watir/wait.rb:193:in `wait_while_present'
websign_tests/PreferencesCreateDeleteUser/PreferencesCreateDeleteUser.rb:72:in `block in run_this_test'`

If additional details are needed to debug this issue, please let me know and I will be happy to assist.

**Comment by titusfortner** [comment]
Thanks for this bug report.

I changed `#visible?` and `#enabled?` so it would not go through `#element_call` to minimize recursive calls with `#wait_for_*`. That removes the Stale Element handling. We need to verify that recursive calls don't cause a problem. I verified all tests pass putting them back into `#element_call`, but I'd be more comfortable stepping through a run to make sure it works as expected.

**Comment by titusfortner** [comment]
Addressed by #515
