### ISSUE TITLE
Issues with Firefox at the end of automation.

### ISSUE THREAD

**Issue by acappelgryn** [watir/watir#505]
Hello everyone,

I am in the process of upgrading to watir 6 for selenium 3.0 support, but ran into bit of an issue I cannot find the source of.

Current environment:
macOS 10.12.2 (Sierra)
watir 6.0.2 (selenium-webdriver 3.0.3)
firefox 50.1.0 (geckodriver 0.11.1)

The issue I am having is when any automation ends and the browser is closed `b.close` I receive the following error message: 
**Firefox Web Content quit unexpectedly.**
Click Report to see more detailed information and send a report to Apple.
OPTIONS:
Ignore/Report...

I have tried uninstalling everything and reinstalling all of it again, but the error still seems to be popping up. Does anyone have any ideas as to why and what could be causing the error?

**Comment by titusfortner** [comment]
What is the code you are using to start the browser? Does it happen if you close the browser immediately after creating it?

**Comment by acappelgryn** [comment]
This is what I use to open my browser and set a timeout for some of the pages that load longer the 60 seconds
```
client = Selenium::WebDriver::Remote::Http::Default.new
client.timeout = (MyConstants.new).getTimeout # seconds – default is 60
browser = Watir::Browser.new (MyBrowser.new).getBrowser, :http_client => client
```

It only happens at the end of the code when it closes the browser or if I cntl + c to interrupt it.
If I close the test window with the red x manually, during a running test, no error.

**Comment by titusfortner** [comment]
But the error is on Firefox, not in the Ruby code?

**Comment by acappelgryn** [comment]
Yes, it is a Mac UI dialog that gives the error message for Firefox. The error displays outside of my CLI.

**Comment by acappelgryn** [comment]
This only occurs during an automation run though. When I manually open my Firefox browser and quit the application I get no such error message.

**Comment by titusfortner** [comment]
Well, I'm using the same versions of everything as you are without any issues. You might try downloading Firefox Nightly and seeing if that one gives you an issue. Nightly will have better support for geckodriver regardless.

Either way, without being able to replicate what you are seeing there really isn't anything we can do for this.
