### ISSUE TITLE
Method drag_and_drop_by throwing weird error

### ISSUE THREAD

**Issue by acappelgryn** [watir/watir#506]
Running the code below throws the error `unknown command: :mouse_move_to (ArgumentError)`

```
draggable = b.element_1
droppable = b.element_2
draggable.drag_and_drop_on droppable
```

Checked the code running this method and there is no `:mouse_move_to` anywhere. Any ideas why this is happening? Could it be an issue with selenium-webdriver?

**Comment by titusfortner** [comment]
Are you running this with geckodriver on Firefox 48+? Mozilla has not yet implemented the Actions classes. Does it work with Chrome?

**Comment by acappelgryn** [comment]
Yes I am running on geckodriver and firefox 50.1. That is probably the issue.

I ran it in chrome as everything is working fine. 
I apologize for not running that in that browser before asking here.
I will be sure to add that to my list of things to test before asking here again.
