### ISSUE TITLE
Ruby 2.4.0 TableCell alias_method issue

### ISSUE THREAD

**Issue by MacCracken** [watir/watir#508]
With the recent release of Ruby 2.4.0, after repairing the Fixnum depreciations there is a remaining issue with TableCell alias_method

`/usr/local/lib/ruby/gems/2.4.0/gems/watir-6.0.4/lib/watir/elements/table_cell.rb:3:in ‘alias_method': undefined method ‘col_span' for class ‘Watir::TableCell' (NameError)
	from /usr/local/lib/ruby/gems/2.4.0/gems/watir-6.0.4/lib/watir/elements/table_cell.rb:3:in ‘<class:TableCell>'
	from /usr/local/lib/ruby/gems/2.4.0/gems/watir-6.0.4/lib/watir/elements/table_cell.rb:2:in ‘<module:Watir>'
	from /usr/local/lib/ruby/gems/2.4.0/gems/watir-6.0.4/lib/watir/elements/table_cell.rb:1:in ‘<top (required)>'
	from /usr/local/lib/ruby/gems/2.4.0/gems/watir-6.0.4/lib/watir.rb:133:in ‘<top (required)>'
	from /usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in ‘require'`

**Comment by MacCracken** [comment]
Repaired by fixing attribute_helper

**Comment by ttguy** [comment]
I have both the issues you mention here - Fixnum depreciations and the undefined method ‘col_span' .
Can you provide any guidance on how I could fix them?

**Comment by MacCracken** [comment]
confirm that you are not asserting Fixnum in your tests.
