### ISSUE TITLE
wait_until is broken in watir 6.0.3

### ISSUE THREAD

**Issue by pravinrmali** [watir/watir#512]
Using Watir 6.0.3, page object 2.0.0 and Ruby 2.1.9

As per latest watir changes changed this line of code from 
```
wait_until(DEFAULT_WAIT_TIME.to_i, 'Login button not found when waiting for the login page to load') do
      login_element.visible?
    end
```
 to  
`login_element.wait_until(timeout: 10, message: "Login button not found when waiting for the login page to load") { |el| el.visible? }`

but getting following error in 'until' function from 'Wait' (watir-6.0.3\lib\watir\wait.rb ) module.

`undefined method 'zero?' for #<Hash:0x48b7eb8> (NoMethodError)`

**Comment by titusfortner** [comment]
I do think there are some unintended things happening with `#visible?` that need to be tracked down. Can you provide a full stack trace for the error? Or a reproducible test case?

That being said, this issue might go away for you if you use [`#to_proc`](http://watir.github.io/watir-6-faq/#I):

```
message = "Login button not found when waiting for the login page to load"
login_element.wait_until(timeout: 10, message: message, &present?)
```

**Comment by pravinrmali** [comment]
seems like page-object issue, if I get rid of Page-object 'wait_until' and use Watir 'wait_until' it works as expected.
```
    message = "Login button not found when waiting for the login page to load"
    browser.button(name: 'login').wait_until(timeout: 10, message: message, &:visible?)
```

**Comment by titusfortner** [comment]
Appears to be logged here now: https://github.com/cheezy/page-object/issues/408
