### ISSUE TITLE
 Selenium::WebDriver::Error::NoSuchDriverError: no such session

### ISSUE THREAD

**Issue by aaron-zipnosis** [watir/watir#513]
I'm trying to get watir up and running (replacing Capybara).  I can't seem to get a session.  I'm using the example in the readme, so I assume it should just work.

```
$ bundle list
  * chromedriver-helper (1.0.0)
  * selenium-webdriver (3.0.5)
  * watir (6.0.3)
```

```ruby
    require 'watir'

    browser = Watir::Browser.new
    browser.goto 'google.com'
    browser.text_field(title: 'Search').set 'Hello World!'
    browser.button(type: 'submit').click

    puts browser.title
    # => 'Hello World! - Google Search'
    browser.close
```

```
     Failure/Error: browser.goto 'google.com'

     Selenium::WebDriver::Error::NoSuchDriverError:
       no such session
         (Driver info: chromedriver=2.25.426935 (820a95b0b81d33e42712f9198c215f703412e1a1),platform=Mac OS X 10.11.6 x86_64)
```

The chromedriver I have in my path does not match the driver shown in the error.

```
$ chromedriver --version
ChromeDriver 2.27.440174 (e97a722caafc2d3a8b807ee115bfb307f7d2cfd9)
```

**Comment by titusfortner** [comment]
That's because you are using the `chromedriver-helper` gem which creates a reference to a different chromedriver. Which ruby version manager are you using (rvm / rbenv / chruby)? Uninstalling the gem should work. You can also switch to the `webdrivers` gem (which I wrote) that is a fork/update to that gem but auto-downloads the latest version of a driver and supports drivers for all browsers.

And welcome to Watir, I'd love to hear more about how your transition is going from Capybara. You can join our Watir Channel on the Selenium Slack: https://seleniumhq.herokuapp.com/

**Comment by aaron-zipnosis** [comment]
When I remove the chromdriver-helper gem I get 

```     
Selenium::WebDriver::Error::WebDriverError:
        Unable to find chromedriver. Please download the server from http://chromedriver.storage.googleapis.com/index.html and place it somewhere on your PATH. More info at https://github.com/SeleniumHQ/selenium/wiki/ChromeDriver.
```

**Comment by titusfortner** [comment]
Sounds like the gem didn't uninstall cleanly.
Try using `webdrivers` gem which should overwrite it.
If that doesn't work, try switching to a different version of Ruby that never had `chromedriver-helper` installed in the first place.

**Comment by titusfortner** [comment]
(that last one is assuming you are using RVM or similar)

**Comment by aaron-zipnosis** [comment]
I've tried webdrivers.
I just installed 2.3.2 (fresh), installed all the gems, re-ran my spec.  Same error:

```
     Failure/Error: browser.goto 'google.com'

     Selenium::WebDriver::Error::NoSuchDriverError:
       no such session
         (Driver info: chromedriver=2.25.426935 (820a95b0b81d33e42712f9198c215f703412e1a1),platform=Mac OS X 10.11.6 x86_64)
```

**Comment by titusfortner** [comment]
are you using rvm?

**Comment by aaron-zipnosis** [comment]
yes.  I was using 2.3.1, so I installed 2.3.2, installed bundler, and bundled

**Comment by titusfortner** [comment]
and you have `gem webdrivers` and not `gem chromedriver-helper`?

**Comment by aaron-zipnosis** [comment]
Yes.  Going to try

```
rvm remove 2.3.2
rvm remove 2.3.1
rvm install 2.3.1
rvm use 2.3.1
gem install bundler
bundle
```

**Comment by titusfortner** [comment]
Then do 

```
chromedriver --version
which chromedriver
```

**Comment by aaron-zipnosis** [comment]
```
$ chromedriver --version
ChromeDriver 2.27.440174 (e97a722caafc2d3a8b807ee115bfb307f7d2cfd9)
$ which chromedriver
/Users/aaron/.rvm/gems/ruby-2.3.1/bin/chromedriver
```

Still have the error with 2.25

Threw a binding before the error:

```
`which chromedriver`
"/Users/aaron/.rvm/gems/ruby-2.3.1/bin/chromedriver\n"
```

**Comment by titusfortner** [comment]
are you running your tests with `bundle exec`? :)

**Comment by aaron-zipnosis** [comment]
![facepalm](https://cloud.githubusercontent.com/assets/16294433/21573081/0e255114-cea6-11e6-96c6-90624166e0c8.jpg)

Unbelievable.  Thank you.

**Comment by titusfortner** [comment]
Sure thing. I've spent hours in the past to figure out that is what I was doing wrong. :)
