### ISSUE TITLE
Different behaviour depending on url

### ISSUE THREAD

**Issue by evilmarian** [watir/watir#514]
I've been playing with watir lately, and found really strange behaviour while having fun with parsing some test dymanic pages using `phantom`.

In my case, watir has opened different pages depending whether I put `www` in front of page url or not. I have tested this using pure `phantomjs`, and it behaves correctly.

```
require 'watir'

good_url = 'http://www.flashscore.com/match/rBpIJpah/#odds-comparison;1x2-odds;full-time'
bad_url = 'http://flashscore.com/match/rBpIJpah/#odds-comparison;1x2-odds;full-time'

browser = Watir::Browser.new(:phantomjs)
browser.goto(bad_url)

# this puts different page when using good_url and bad_url
puts browser.url
```

I am not convinced if that's on `watir` side, but wonder if there is a way to debug this behaviour and see what can be causing this.

My specs:
```
ruby: ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin15]
phantomjs: 2.1.1
watir: 6.0.3
selenium-webdriver: 3.0.4
```

**Comment by titusfortner** [comment]
This works in both chrome & firefox, so I'm going to go with a bug in phantomjs with browser redirects. We recommend avoiding phantomjs browser as the GhostDriver portion that interacts with Selenium has not been maintained in several years.
