### ISSUE TITLE
Please tag old versions in git (including watir-webdriver one) 

### ISSUE THREAD

**Issue by hashar** [watir/watir#519]
Hello!

Had some troubles with the legacy watir-webdriver version (0.9.x) that used to be hosted on https://github.com/watir/watir-webdriver/  That repo got emptied in favor of watir/watir.  Unfortunately it lacks a few tags for the 0.9.x version and the 6.0.0.beta

In the interesting of git bisecting and digging in the code history I would really appreciate if you could tag the missing 0.9.x and 6.x versions:

| Version | Commit | Git cmd with `v` prefix
|--|--|--
| 0.9.1 | 49e121e | `git tag v0.9.1 49e121e`
| 0.9.2 | 8b926df | `git tag v0.9.2 8b926df`
| 0.9.3 | 9c55914 | `git tag v0.9.3 9c55914`
| 0.9.9 | 494be19 | `git tag v0.9.9 494be19`
| 6.0.0.beta1 | b94f00c3 | `git tag v6.0.0.beta1 b94f00c3`
| 6.0.0.beta2 | e8764b26 | `git tag v6.0.0.beta2 e8764b26`
| 6.0.0.beta4 | 7f3f6e43 | `git tag v6.0.0.beta4 7f3f6e43`
| 6.0.0.beta5 | 9997b296 | `git tag v6.0.0.beta5 9997b296`
| 6.0.0 | 97a496e | `git tag v6.0.0 97a496e`
| 6.0.1 | 20405e0 | `git tag v6.0.1 20405e0`
| 6.0.2 | 5e28be1 | `git tag v6.0.2 5e28be1`
| 6.1.0 | b2b485f | `git tag v6.1.0 b2b485f`

Or for copy pasting and reviewing:
```
git tag v0.9.1 49e121e
git tag v0.9.2 8b926df
git tag v0.9.3 9c55914
git tag v0.9.9 494be19
git tag v6.0.0.beta1 b94f00c3
git tag v6.0.0.beta2 e8764b26
git tag v6.0.0.beta4 7f3f6e43
git tag v6.0.0.beta5 9997b296
git tag v6.0.0 97a496e
git tag v6.0.1 20405e0
git tag v6.0.2 5e28be1
git tag v6.1.0 b2b485f
```

And to verify them:
```
$ git show --no-patch --decorate --oneline v0.9.1 v0.9.2 v0.9.3 v0.9.9 v6.0.0.beta1 v6.0.0.beta2 v6.0.0.beta4 v6.0.0.beta5 v6.0.0 v6.0.1 v6.0.2 v6.0.1
49e121e (tag: v0.9.1) Update changelog and release 0.9.1
8b926df (tag: v0.9.2) Update changelog and release 0.9.2
9c55914 (tag: v0.9.3) Update changelog and release 0.9.3
494be19 (tag: v0.9.9, origin/watir-webdriver) final release of watir-webdriver
b94f00c (tag: v6.0.0.beta1) update gemspec file for beta release
e8764b2 (tag: v6.0.0.beta2) support for requiring watir-webdriver
7f3f6e4 (tag: v6.0.0.beta4) release 6.0.0.beta4
9997b29 (tag: v6.0.0.beta5) release Watir 6.0 beta 5
97a496e (tag: v6.0.0) release 6.0!
20405e0 (tag: v6.0.1) release Watir 6.0.1
5e28be1 (tag: v6.0.2) release 6.0.2
```

(I have excluded the old 0.0.1.devXX ones)

Thank you in advance!

Self ref: `colordiff -u <(grep ^### CHANGES.md|cut -d\  -f2|sort -n) <(git tag|cut -b2-|sort -n)`
CC @zeljkofilipin

**Comment by p0deje** [comment]
Thank you very much for doing all the work so I could just copy-paste commands and push the tags. This is now done!

P.S. @titusfortner are you releasing with `rake release`?

**Comment by hashar** [comment]
You are welcome !

**Comment by titusfortner** [comment]
@p0deje - uhhh, we have a `rake release`? I'll make sure to do that next time.
I did notice that the tags were missing, but I hadn't gotten to figuring it out yet. So, thanks from me as well, @hashar. Let us know if there is anything we can help troubleshoot that prompted the bisecting in the first place.

**Comment by hashar** [comment]
The watir-webdriver 0.9.x chokes under ruby 2.4. Because : Fixnum is deprecated which causes some alias_method to fail :]  That is fixed in your `v.6.1.0` by f005ab958040c65b51c6f76a09e20ed588332e94 

The reason I bisected is I have bumped watir-webdriver from 0.8.0 to 0.9.3 and thought it might had a regression.  Eventually wanted to find out why 0.9.9 could not be found in the repo and I went crafting tags for my bisect.

That is when I realized the root cause is ruby 2.4.

I should thus migrate to your v6 and Selenium 3 in order to use ruby 2.4.  Nothing you can do honestly since 0.9 is end of life :]


Thank you!
