### ISSUE TITLE
Calling alert.set 'text' in Firefox causes error

### ISSUE THREAD

**Issue by tarikdem** [watir/watir#522]
```
Selenium::WebDriver::Error::InvalidArgumentError:
       Missing 'value' parameter
```

The same call works in Chrome.

**Comment by p0deje** [comment]
Please provide information about selenium-webdriver, watir, Firefox and GeckoDriver versions.

**Comment by tarikdem** [comment]
- watir 6.0.2 (also tried with 6.1.0)
- selenium-webdriver 3.0.5
- Firefox 50.0
- geckodriver 0.11.1

**Comment by p0deje** [comment]
Can you try to upgrade geckodriver to 0.13 (and probably Firefox to a compatible version) and try one more time?

There is a probably related issue https://bugzilla.mozilla.org/show_bug.cgi?id=1255906 which was commented to be working by @titusfortner only yesterday.

**Comment by tarikdem** [comment]
The issue still exists after upgrading geckodriver to 0.13 and Firefox to 50.1. I am currently using `@browser.execute_script("window.prompt = function() {return 'text'}")` as a workaround.

**Comment by titusfortner** [comment]
It works in Firefox Nightly, (which has other issues), so the bug is closed even if it still affects users.

**Comment by p0deje** [comment]
@tarikabh Guess we can only recommend to wait for new release then. Closing this.
