### ISSUE TITLE
chrome with watir v6.1.0  close automatically

### ISSUE THREAD

**Issue by lovingyu** [watir/watir#523]
hi , i have a question 

require 'watir'
browser = Watir::Browser.new :chrome
browser.goto 'www.baidu.com'
puts browser.title

When i run this code, the browser opens the site and then closes automatically . Why does it close automatically?

my environment:
windows 10
ruby 2.2.6 x64
chrome 55.0.2883.87 
chrome driver:  chromedriver_win32  (the latest version driver in  http://chromedriver.storage.googleapis.com/index.html   2.27 folder)

with browser firefox ,ie, edge all works fine .
thanks .

**Comment by p0deje** [comment]
Does it cause any problems for you? If yes, please re-open the issue with test case to reproduce and expected/actual behavior.

Browser is being closed because when script exits, selenium closes driver.

**Comment by titusfortner** [comment]
If you want the browser to stay open after the process has ended you need to detach the browser from it. Take a look at detach option here https://sites.google.com/a/chromium.org/chromedriver/capabilities
