### ISSUE TITLE
Running Chrome/chromedriver headlessly

### ISSUE THREAD

**Issue by acappelgryn** [watir/watir#525]
Trying to run chrome/chromium (either is fine) headlessly on an ubuntu server. Got Firefox running perfectly fine with the ruby headless gem (with xvfb) and geckodriver, but for some reason Chrome keeps throwing an error `chrome failed to start: crashed`

Is chrome currently incapable or running headlessly? Or is there a method of setting up an environment? I have been researching, but all documentation/applications found are quite old and either does not work or does not exist anymore.

**Comment by titusfortner** [comment]
This is more of a question than a Watir issue. There are several better ways to get these questions answered as described on our site http://watir.github.io/help/

That being said, the most likely cause is mismatched versions of chrome and chromedriver, so make sure those are both up to date.
