### ISSUE TITLE
browser.goto error "EOFError: end of file reached"

### ISSUE THREAD

**Issue by radvc** [watir/watir#526]
Im having an issue when I run goto method, "EOFError: end of file reached", I use IRB to test watir for scraping a website below is my example code in IRB:

require "watir"

browser = Watir::Browser.new(:chrome)
browser.goto("google.com")

**Comment by titusfortner** [comment]
Update your chromedriver to 2.27

**Comment by radvc** [comment]
@titusfortner still got the same error

**Comment by titusfortner** [comment]
Then you likely have multiple versions of chromedriver on your system. Are you using chromedriver helper gem? I created a fork of that, the webdrivers gem, that automatically checks for and updates to the latest version of any selenium supported driver. Gem uninstall chromedriver-helper if you have it, and gem install webdrivers and try again.

**Comment by radvc** [comment]
@titusfortner its working now! Thanks! 👍
