### ISSUE TITLE
watir6.1 + safari10, could not interact with controls ?

### ISSUE THREAD

**Issue by djwgit** [watir/watir#527]
watir6.1,  safari10.0.1, mac os x sierra

could launch the browser, but could not interact with ui controls.

```
$irb
$ require 'watir'
> $browser=Watir::Browser.new :safari
> $browser.goto "www.google.com"
> $browser.button(:text, "Google Search").exists?
=> true
> $browser.button(:text, "Google Search").click
```
then nothing happen.  not sure if this is a bug of safaridriver or selenium, or watir :-(
thanks.

**Comment by titusfortner** [comment]
Are you using latest version of Selenium? Are you using Sierra or El Capitan?

**Comment by titusfortner** [comment]
Ok, I can reproduce this. It's a safaridriver bug with `GET session/<session_id>/element/<element_id/displayed` endpoint

This is fixed in The Safari Technical Preview.
Download it from the App store and initialize your browser like this:

```
tech_preview_driver = "/Applications/Safari\ Technology\ Preview.app/Contents/MacOS/safaridriver"
browser = Watir::Browser.new :safari, driver_path: tech_preview_driver
```

**Comment by titusfortner** [comment]
I should note that the Safari Technical Preview safaridriver only works on Sierra, not on El Capitan.

**Comment by djwgit** [comment]
thanks @titusfortner
