### ISSUE TITLE
Docker, Kubernetes, Watir, Chrome, AWS, & file download

### ISSUE THREAD

**Issue by flah00** [watir/watir#533]
I've been unable to determine the easiest way to download a file, using a remote chrome node, in selenium grid, with watir. I suppose I could rely on EFS (NFS in AWS), but the requires some cleanup, which is less than ideal. 

Is there a simple way to direct a remote chrome node to download a file, which local rspec/watir can access? The tests I'm running are e2e and are attempting to validate data in reports. Another thought is faking the request, using curl or something similar, but if that can be avoided, it'd make things much simpler.

**Comment by p0deje** [comment]
This is not a bug report.

Please, use [watir-general](https://groups.google.com/forum/#!forum/watir-general) mailing list or StackOverflow for getting help.
