### ISSUE TITLE
Not able to click a Checkbox with Watir-6.2.0

### ISSUE THREAD

**Issue by Droidmannn** [watir/watir#536]
Hi Team,

I was using Watir-Webdriver for automating Web pages and since this has been deprecated and Watir gem got introduced I replaced Watir-Webdriver with Watir-6.2.0 but unfortunately I am not able to click on a checkbox and time out error occurs with the latest Watir-6.2.0. However the same step works with Watir-Webdriver. We tried the same in irb as well and it acts the same way..... 

Any help???

my environment:
windows 7
ruby 2.2.4p230 (2015-12-16 revision 53155) [x64-mingw32]
chrome 56.0.2924.87 
chrome driver: chromedriver_win32 (the latest version driver)

**Comment by p0deje** [comment]
Please provide a test case to reproduce the problem.

**Comment by Droidmannn** [comment]
This issue happens when we have checkbox inside a label tag.

```
 <label class="checkbox-label general-label ">
                        <input type="checkbox" class="checkbox unknown" name="Unknown" id="list-unknown">
                        <span class="checkbox-label-text">Unknown</span>
 </label> 
```

**Comment by p0deje** [comment]
Can you create a test script that we can run to see the error?

**Comment by titusfortner** [comment]
Are you getting a timeout error? Does it say the element isn't visible?

**Comment by titusfortner** [comment]
I can't reproduce this issue with this code. I wonder if it might be related to this (which I could reproduce): https://bugs.chromium.org/p/chromedriver/issues/detail?id=1713

**Comment by tnypxl** [comment]
I've experienced this same issue in Safari and Firefox as well. Its not limited to checkboxes either, it happens on links as well.

**Comment by titusfortner** [comment]
What error do you get? Do you have a reproducible test case we can look at?

**Comment by tnypxl** [comment]
For example: I click a checkbox, then hit a button to submit a form, and look for something on the page that follows. My test fails on validation. However, its still sitting on the first page, waiting to do the first step. Whats odd is that is continues to scroll through the page as if it had clicked everything successfully.

**Comment by tnypxl** [comment]
@titusfortner Thats just it. There are no weird deltas in my code. Its just really basic `.click` and `.set`.  in succession. I've verified there aren't multiple identical elements, I've verified that our application isn't breaking mouse events (its a react application).

One (gross) workaround I've tried was something like this:

```
browser.checkbox(class: 'foo').set until browser.checkbox(class: 'foo').set?
```

My hunch is that its somewhat related to what #534 is trying to resolve.

**Comment by titusfortner** [comment]
Which JavaScript framework are you using? If you put a sleep before the click it works?

**Comment by tnypxl** [comment]
@titusfortner I tried that. Putting a sleep before doesn't make a difference.

**Comment by titusfortner** [comment]
So if it isn't a timing issue, does it work if you just click it twice?

**Comment by tnypxl** [comment]
@titusfortner Sometimes clicking it twice works. But if the viewport clips the element even just a little bit, it seems to render that approach useless.

**Comment by tnypxl** [comment]
Also, we're using React for our application.

**Comment by titusfortner** [comment]
Sigh, react apps seem to be doing weird things with selenium recently. Regardless, we need something reproducible. Does using watir-scroll help?

**Comment by titusfortner** [comment]
Sigh, react apps seem to be doing weird things with selenium recently. Regardless, we need something reproducible. Does using watir-scroll help?

**Comment by tnypxl** [comment]
@titusfortner I can certainly try it.

**Comment by titusfortner** [comment]
@Droidmannn if this is still an issue please provide a reproducible test case or the combination code you are using and logs you get (`Selenium::WebDriver.logger.level = :info`) and I can re-open this.
