### ISSUE TITLE
unable to connect to phantomjs

### ISSUE THREAD

**Issue by aaron-zipnosis** [watir/watir#539]
I've started a project fresh.  I'm using Watir and rolling my own PageObject framework.

I want to push this up to our CI and use phantomjs, however when I run my test with the browser instantiation of `Watir::Browser.new :phantomjs`, I'm returned the error:

```
     Selenium::WebDriver::Error::WebDriverError:
       unable to connect to phantomjs @ http://127.0.0.1:8910 after 20 seconds
```

I don't know if it's on Selenium's side, Webdriver's side, or Watir's side.  When I check `~/.webdrivers/mac` I see `phantomjs`.

I also deleted the binary and installed `phantomjs` through `homebrew` with the same result.  If I instantiate my driver with `:chrome` or `:firefox` everything works fine.

**Comment by titusfortner** [comment]
Which CI?

It seems like it is finding it but unable to connect, which could indicate a user/permission issue.

Out of curiosity, why phantomjs? chrome is actually significantly faster on linux and has the advantage of being a real browser. :)

Also for reference, this is what we do to use phantomjs for our watir tests: https://github.com/watir/watir/blob/master/support/travis.sh

**Comment by aaron-zipnosis** [comment]
Running on Semaphore.  I tried phantom because chrome wasn't working. Chrome wasn't working because it looks like the Rails server isn't spinning up properly, an issue with phusion.  So even if I got phantom to work, our tests would still fail.  I'm going to close this.

**Comment by titusfortner** [comment]
ah, yeah, phantomjs is unlikely to work if chromedriver doesn't work. But yeah, I recommend chromedriver (with xvfb if necessary) over phantomjs.
