### ISSUE TITLE
watir 6.2.1 not support edge browser?

### ISSUE THREAD

**Issue by lovingyu** [watir/watir#545]
hi , 
 with watir 6.2.0(selenium-webdriver3.0.5) , test edge browser fine.
but update to watir6.2.1(selenium-webdriver3.3.0),test edge browser failed.
------------------error message:--------------------------------------------------------
d:/Ruby22/lib/ruby/gems/2.2.0/gems/selenium-webdriver-3.3.0/lib/selenium/webdriver/remote/w3c_bridge.rb:118:in `create_session': no sessionId in returned payload (Selenium::WebDriver::Error::WebDriverError)
	from d:/Ruby22/lib/ruby/gems/2.2.0/gems/selenium-webdriver-3.3.0/lib/selenium/webdriver/remote/w3c_bridge.rb:76:in `initialize'
	from d:/Ruby22/lib/ruby/gems/2.2.0/gems/selenium-webdriver-3.3.0/lib/selenium/webdriver/edge/bridge.rb:49:in `initialize'
	from d:/Ruby22/lib/ruby/gems/2.2.0/gems/selenium-webdriver-3.3.0/lib/selenium/webdriver/common/driver.rb:66:in `new'
	from d:/Ruby22/lib/ruby/gems/2.2.0/gems/selenium-webdriver-3.3.0/lib/selenium/webdriver/common/driver.rb:66:in `for'
	from d:/Ruby22/lib/ruby/gems/2.2.0/gems/selenium-webdriver-3.3.0/lib/selenium/webdriver.rb:87:in `for'
	from d:/Ruby22/lib/ruby/gems/2.2.0/gems/watir-6.2.1/lib/watir/browser.rb:46:in `initialize'
	from test.rb:2:in `new'
	from test.rb:2:in `<main>'

**Comment by titusfortner** [comment]
Can you set this: `Selenium::WebDriver.logger.level = :info` before you initialize the browser and provide the output?

**Comment by lovingyu** [comment]
hi ,the output:
---------------------------------------------------------------------------------
2017-04-08 13:25:56 INFO Selenium -> POST session
2017-04-08 13:25:56 INFO Selenium    >>> http://localhost:17556/session | {"desiredCapabilities":{"browserName":"MicrosoftEdge","platform":"WINDOWS"}}
2017-04-08 13:25:57 INFO Selenium <- {"sessionId":"10AAC21D-6DB3-4357-8D16-7616549D00F9","status":0,"value":{"browserName":"MicrosoftEdge","browserVersion":"38.14393.0.0","platformName":"windows","platformVersion":"10","takesElementScreenshot":true,"takesScreenshot":true,"acceptSslCerts":true,"applicationCacheEnabled":true,"locationContextEnabled":true,"webStorageEnabled":true,"pageLoadStrategy":"normal"}}

**Comment by lovingyu** [comment]
hi ,  i add a output  in the  w3c_bridge.rb file ( d:/Ruby22/lib/ruby/gems/2.2.0/gems/selenium-webdriver-3.3.0/lib/selenium/webdriver/remote/w3c_bridge.rb:121  )
 in the create_session function:
       def create_session(desired_capabilities)
          resp = execute :new_session, {}, {desiredCapabilities: desired_capabilities}
	  puts "--------------------------"
	  puts resp
	  puts "--------------------------"
          @session_id = resp['sessionId']
          return W3CCapabilities.json_create resp['value'] if @session_id

          raise Error::WebDriverError, 'no sessionId in returned payload'
        end

the output is ：
--------------------------
{"browserName"=>"MicrosoftEdge", "browserVersion"=>"38.14393.0.0", "platformName"=>"windows", "platformVersion"=>"10", "takesElementScreenshot"=>true, "takesScreenshot"=>true, "acceptSslCerts"=>true, "applicationCacheEnabled"=>true, "locationContextEnabled"=>true, "webStorageEnabled"=>true, "pageLoadStrategy"=>"normal"}
--------------------------

**Comment by lovingyu** [comment]
hi ,  i add a output  in the  w3c_bridge.rb file ( d:/Ruby22/lib/ruby/gems/2.2.0/gems/selenium-webdriver-3.3.0/lib/selenium/webdriver/remote/w3c_bridge.rb:121  )
 in the create_session function:
   def create_session(desired_capabilities)
          resp = execute :new_session, {}, {desiredCapabilities: desired_capabilities}
	  puts "--------------------------"
	  puts resp
	  puts "--------------------------"
          @session_id = resp['sessionId']
          return W3CCapabilities.json_create resp['value'] if @session_id
          raise Error::WebDriverError, 'no sessionId in returned payload'
        end
the output is ：
--------------------------
{"browserName"=>"MicrosoftEdge", "browserVersion"=>"38.14393.0.0", "platformName"=>"windows", "platformVersion"=>"10", "takesElementScreenshot"=>true, "takesScreenshot"=>true, "acceptSslCerts"=>true, "applicationCacheEnabled"=>true, "locationContextEnabled"=>true, "webStorageEnabled"=>true, "pageLoadStrategy"=>"normal"}
--------------------------

**Comment by p0deje** [comment]
Please create issue in https://github.com/SeleniumHQ/selenium/issues for that.

Closing as not a Watir issue.
