### ISSUE TITLE
Backslashes being added to CSS attribute

### ISSUE THREAD

**Issue by c0nfleis** [watir/watir#546]
I am attempting to pass a value into a page object locator and in the course of doing so am finding that watir is adding backslashes around my passed in value.

```
@topic = "Travel"
@x = '[data-test-id='+ @topic + '] .category-label'

y = label(:topicHeader, :css => @x)
```

The result of inspecting y is:
` y=#<Watir::Label: located: false; {:topicHeader=>{:css=>"[data-test-id=\"Travel\"] .category-label"}, :tag_name=>"label"}>`

The backslashes are causing my tests to fail due to the object not being found.

**Comment by titusfortner** [comment]
Watir shouldn't be doing any conversions of provided css, so I suspect this is happening in the driver. You can set `Selenium::WebDriver.logger.level = :info` to see exactly what the input to the server/driver looks like.

That being said, this would likely be a better locator for you: 
`label(data_test_id: /#{@topic}/, class: 'category-label')`

Also, labels have some additional special processing available; what is adjacent html in your file?

**Comment by titusfortner** [comment]
@iNeedICS if this is still an issue for you, you can provide the logs and I'll reopen this.
