### ISSUE TITLE
Case difference between element search and element properties

### ISSUE THREAD

**Issue by Paul3816547290** [watir/watir#552]
I have some source with `<h3 class="xyz">My heading</h3>`

If I write browser.element({:tag_name=>"h3",:text=>"MY HEADING"}) it fails as expected because the case is wrong.  And I know I could use browser.h3(:text..etc.) but I have reasons not to. I believe the browser element compares (case sensitive) to the source - Correctly.

However, If I then write 
```
for element in browser.elements({:tag_name=>"h3"})
  puts (element.text.inspect)
end
```
it prints "MY HEADING" 

element.text returns the displayed version of the text (in this case the class styling presents uppercase)

I am writing a framework that when the search fails attempts to output some usefull information as to the elements that might have been intended.
Not helpfull when it says 
Could not locate an element with a :tag_name="h3" and :text="MY HEADING"
Possible elements
  :index=1 :tag_name="h3" :text="MY HEADING"

My issue is that element.text returns a manipulated version based on styling.  Is it possible to see the same raw version the search is using for its comparison?
In this instance I think element.text should return "My heading" not "MY HEADING" or is there some other method I should be using?

**Comment by titusfortner** [comment]
The [W3C specification section on getting element text](https://w3c.github.io/webdriver/webdriver-spec.html#get-element-text) specifies that it should return "as rendered." Watir is returning what the drivers are returning per the spec. 

The text location used in Watir is imperfect as it is an XPath translation which does not concern itself with rendering, and additionally [has different behavior between `String` and `Regexp`](https://github.com/watir/watir/issues/342). 

```
browser.h3(text: 'My heading').exist?
# => true
browser.h3(text: 'MY HEADING').exist?
# => false
browser.h3(text: /My heading/).exist?
# => false
browser.h3(text: /MY HEADING/).exist?
# => true
```
That being said, `#inner_html` executes a javascript which should give you what you are looking for.
```
browser.h3(text: 'My heading').text
# => 'MY HEADING'
browser.h3(text: 'My heading').inner_html
# => 'My heading'
```

To the extent that there is something that needs to be done here, I think it is to update the location side of things, not the text return side of things, and that action item is represented by issue #342

**Comment by Paul3816547290** [comment]
Thanks for the feedback.  I was unaware of the regex behaving differently and was bound to bang my head into that soon too.
I has resorted to inner_html and the having to parse it to ensure the item had no embedded tags etc.  Basically turning it to text only.  However I may nee to be sensitive to the request parameter types str/regex and adjust my response from the framework accordingly.

**Comment by titusfortner** [comment]
Is the framework you are making open source?

**Comment by Paul3816547290** [comment]
I think it will be possible when it starts to stabalize again

Version 1 was it was Open sourced and called H2O (I dont remember where its been almost 10 years) - it was early watir based and had lots of features like running your code through W3C validation, automatic spellchecking, page timing, and recording all the results with screenshots as it went - all automatically - however it required an Ubuntu webserver and database server, and various virtualized PC's as Slave runners.  It was complex to set up behind new company firewalls and proxies (as they are all different), and email management (for confirming emails sent or email verifications required) was always a pain.  But the benifit of having novice users running scripts via a browser and being emailed the result was just such a huge win in complex system support.

I then turned it into Wyne a version that would run on a local PC (it was hacked down rather poorly - and converted to the then new selenium-driver) to do End2End Tests or Directories full of regression tests.  

Its been on the shelf for 2 years while I was not testing and finally dusted off.  Watir has made HUGE leaps forward since those days.  So Im just in the throws of another refactoring/rewrite.  The idea is to add to watir and make it easier for more tester to write and execute scripts (not cobble it).  And it is just so much better than the first versions I was using.

Probably going to keep with the name Wyne (Turning Watir into Wyne) ;-)

**Comment by titusfortner** [comment]
I like the name! So this is a PC application? There are a number of us working on an initiative to make it easier for companies to get up and going with Watir. If you can join us in the Selenium Slack, there's a Watir channel ([auto-invite](http://seleniumhq.herokuapp.com/)), I'd be interested in a longer discussion on goals and ideas.
