### ISSUE TITLE
Adding Retry mechanism to Watir in case of Timeout

### ISSUE THREAD

**Issue by algritz** [watir/watir#556]
Hello,

I have a series of scripts that I have developed using Watir. Those are wrapped by Spinach, but that is beside what I am about to ask.

The intent of those scripts is to do some functional spot check or simply alleviate some very repetitive tasks.

They have been running well for a while, but lately, I've started to see a lot of failure due to Timeouts between the Chromedriver / Geckodriver (tried both browsers) and the scripts. (At the time I was using watir-webdriver alongside chromedriver and thought that moving to Watir would alleviate the issue, but it did not) Of course, I could simply restart the script, but when the success rate goes below 70 % it really starts to be aggravating.

What I ended up doing is wrap up all of my calls to Watir in a Proc with a Begin, rescue that would do a retry in case of a timeout.

This is ugly and violates so many rules that I am nearly ashamed to had to resort to this solution, but at least using this my scripts are now completing.

here is how I worked around the issue:

```
# takes a proc and wraps it around a series of rescue
def execute_block_and_rety_if_needed
  yield
rescue Net::ReadTimeout
  puts 'Read Timeout detected, retrying operation'
  retry
rescue Net::HTTPRequestTimeOut
  puts 'Http Request Timeout detected, retrying operation'
  retry
rescue Errno::ETIMEDOUT
  puts 'Errno::ETIMEDOUT detected, retrying operation'
  retry
end
```
a sample use would look like this:

    `execute_block_and_rety_if_needed { @browser.link(name: 'OK').wait_until_present.click } # click the 'OK' button`
As you can see, this clearly violates the DRY principle as I need to call this proc every single time.

My question is: how can I move this as a module / feature of Watir so that it picks it up automatically. (ideally I would add a maximum number of retry to prevent an infinite loop).

Thanks! And sorry for the wall of text.

Version information: - Chromedriver => 2.29.461585 - GeckoDriver => 0.16.1 - Firefox => ESR 52 - Chrome => 58 - Watir => 6.2.1

**Comment by titusfortner** [comment]
This is a question rather than an issue with the Watir code, and would be better asked in one of our [three supported help platforms](http://watir.github.io/help/)

That being said, try updating from the deprecated `watir-webdriver` to `watir`. It does the `#wait_until_present` calls for you. Also, I disagree that retrying a proc when a condition isn't met is not DRY. I've successfully used that approach before as well; but let's discuss this somewhere else.

**Comment by algritz** [comment]
posted the question on Stackoverflow:

http://stackoverflow.com/questions/43943522/adding-retry-mechanism-to-watir-in-case-of-timeout

As far as the DRY comment, I reffered to fact that I had to wrap ALL of my watir calls with the proc, sorry if this wasn't clear.

```
execute_block_and_rety_if_needed { @browser.link(name: 'User').wait_until_present.click } # click the 'Edit' button
execute_block_and_rety_if_needed { @browser.link(name: 'Cancel').wait_until_present.click } # click the 'Cancel' button
execute_block_and_rety_if_needed { @browser.link(name: 'OK').wait_until_present.click } # click the 'OK' button
```
The above is just an example that has to happen if I want to use the retry mechanism.
