### ISSUE TITLE
Calling present? on an iframe will return an error if iframe cannot be located

### ISSUE THREAD

**Issue by Mildlywilde** [watir/watir#557]
Calling present? should return a boolean. When called on an iframe it is able to return true but will throw an error instead of returning false.

logs:
https://gist.github.com/WildeRunner/18a9898e99a1edccba07bd4e104348bd

**Comment by titusfortner** [comment]
Do you have the code you used to get this log?

Our specs are passing for it: https://github.com/watir/watir/blob/master/spec/watirspec/elements/iframe_spec.rb#L44-L55

You might also try with Watir > 6.4 since we made a significant update to how things are located & errors are rescued.

**Comment by titusfortner** [comment]
If you can send us a way to duplicate this bug or verify it is still an issue on the latest version of Watir, I will reopen. Thanks.
