### ISSUE TITLE
Website is down - no articles on wiki

### ISSUE THREAD

**Issue by vmvelev** [watir/watir#561]
Hi all,

The website is down and the wiki does not contain any articles, it refers to the website.
Do you have any updates on this?

Venelin

**Comment by jayschab** [comment]
Seems to be an issue with the GitHub Pages settings. In the meantime the raw files are available at https://github.com/watir/watir.github.io/tree/master/_docs

![image](https://cloud.githubusercontent.com/assets/1414862/26732738/fa5cf60c-478e-11e7-9b0d-8bf0962d896c.png)

**Comment by coferc** [comment]
Hi @jayschab we're doing big plug for Watir in our conference presentation at Cerner this Friday, is there any way to fix the website by then? Thanks!

**Comment by titusfortner** [comment]
We're in the process of getting the watir.github.io content to be used on watir.com. This requires changes with the domain registrar, which is maintained by someone no longer associated with the project. The step that causes that warning has to happen first, and hopefully the next step happens soon.

**Comment by titusfortner** [comment]
@coferc let us know if there's anything we can do to help with your presentation. If you join the [Selenium Slack](http://seleniumhq.herokuapp.com/) we can chat in the #Watir channel.

**Comment by coferc** [comment]
Ok thanks @titusfortner. I do have a documentation question -- I'll post on the #Watir channel thanks!

**Comment by coferc** [comment]
Documentation is back up, in time for our big plug at Cerner, thanks so much!
https://watir.github.io/

**Comment by titusfortner** [comment]
Watir site has been transitioned
