### ISSUE TITLE
Set operation fails on non-visible textarea element

### ISSUE THREAD

**Issue by maybelinot** [watir/watir#566]
same as https://github.com/watir/watir/issues/497, but for textarea
**Watir version**: 6.2.1
**Google Chrome**: Version 56.0.2924.76 (64-bit)
```
2.3.0 :008 > browser.goto 'https://ace.c9.io/'
 => "https://ace.c9.io/"
2.3.0 :009 > browser.textarea(:xpath=>"//textarea").visible?
 => false
2.3.0 :010 > browser.textarea(:xpath=>"//textarea").exist?
 => true
2.3.0 :011 > browser.textarea(:xpath=>"//textarea").set 'asd'
This code has slept for the duration of the default timeout waiting for an Element to be present. If the test is still passing, consider using Element#exists? instead of rescuing UnknownObjectExcept
ion
Watir::Exception::UnknownObjectException: element located, but timed out after 30 seconds, waiting for true condition on #<Watir::TextArea: located: true; {:xpath=>"//textarea", :tag_name=>"textarea
"}>
        from /home/etrott/.rvm/gems/ruby-2.3.0/gems/watir-6.3.0/lib/watir/elements/element.rb:531:in `rescue in wait_for_present'
        from /home/etrott/.rvm/gems/ruby-2.3.0/gems/watir-6.3.0/lib/watir/elements/element.rb:521:in `wait_for_present'
        from /home/etrott/.rvm/gems/ruby-2.3.0/gems/watir-6.3.0/lib/watir/elements/element.rb:538:in `wait_for_enabled'
        from /home/etrott/.rvm/gems/ruby-2.3.0/gems/watir-6.3.0/lib/watir/elements/element.rb:550:in `wait_for_writable'
        from /home/etrott/.rvm/gems/ruby-2.3.0/gems/watir-6.3.0/lib/watir/elements/element.rb:655:in `element_call'
        from /home/etrott/.rvm/gems/ruby-2.3.0/gems/watir-6.3.0/lib/watir/user_editable.rb:11:in `set'
        from (irb):11
        from /home/etrott/.rvm/rubies/ruby-2.3.0/bin/irb:11:in `<main>'
2.3.0 :012 > Watir.relaxed_locate = false
 => false
2.3.0 :013 > browser.textarea(:xpath=>"//textarea").set 'asd'
 => nil
```

**Comment by titusfortner** [comment]
Do you have an example you can point to? Is it the same for chrome and Firefox? What browser/driver version? Thanks.

If this is a one off issue, the workaround is `browser.textarea.wd.send_keys 'asd'`, but either the driver shouldn't be reporting false for displayed, or it shouldn't be allowing text entry.

**Comment by maybelinot** [comment]
@titusfortner description updated with example and driver/browser versions. Was reproduced on Firefox as well.

**Comment by titusfortner** [comment]
Interesting. geckodriver shows it is visible, but chromedriver does not. Not sure what iedriver says... I want to just blame ace for a weird-ass implementation. I've pinged AutomatedTester for his take on this. I'll keep this open until I hear back from him on how this should look, but I'm unlikely to support the same workaround we made for file field.

**Comment by titusfortner** [comment]
Actually, the new [beta release](https://twitter.com/titusfortner/status/877652624744501253) might solve this. Please try it out and let us know.

**Comment by maybelinot** [comment]
@titusfortner you're right, works well in beta!
