### ISSUE TITLE
Chrome v59.0.3071

### ISSUE THREAD

**Issue by nhammERA** [watir/watir#567]
How are you planning to address the latest feature, https://www.chromestatus.com/feature/5669008342777856, in Chrome v59.0.3071?  For websites running specifically with your implementation of Basic Browser Authentication (http://watir.github.io/docs/basic-browser-authentication/), stylesheets have the capability of breaking due to this feature of the latest release of Chrome.

**Comment by titusfortner** [comment]
There's nothing for the Watir project to do with this. We can update our documentation to no longer list it as a solution. Perhaps the extension discussed in that article still works?
