### ISSUE TITLE
make waiting optional per call or at least per browser object

### ISSUE THREAD

**Issue by akostadinov** [watir/watir#569]
Hello, #479 implemented automatic waiting for element exist and element visible before an operation can be performed. This is awesome in 99% of the use cases but breaks 1% which can easily kill your productivity.

There are some situations where it needs to be switched off. In a perfect world you can change your app to make it more testable but sometimes you work with third party products (e.g. integration), or product is huge and updating some dialog generated by some lib (e.g. ACE editor #566) is non-trivial and will take much time. Or code freeze has been done for a release and upgrading/fixing a lib is not an option for non-user-visible bugs.

The setting `Watir.relaxed_locate = false` is fine but it changes the behavior for the whole ruby process and especially if you run tests in parallel, it wouldn't be an option. I think that if we can set this per call or at least per `browser` object that will allow thread safety.

In fact the use case that **sometimes** doesn't work is waiting for element to become visible. As a workaround for things that can be done by user but cannot be done by API, we sometimes set hidden fields. So IMO a setting to disable automatic waiting for element to become visible would do the job.

As an example, per call it could be something like:
```
element.invisible.set "my value"
```

The `invisible` methodl on the `element` could return a `dup` of the element where the `visible?` method of it is hardcoded to `true` (or an alias for `exists?`).

I think if we can set per `browser` that can also do the trick but will be uglier:
```
browser.skip_visibility_check = true
element.set "my value"
browser.skip_visibility_check = false
```

**Comment by titusfortner** [comment]
Is this still an issue with the latest beta?

**Comment by akostadinov** [comment]
Could you point out the specific fixes have been implemented so I can try to understand whether it could be an issue or not?

**Comment by akostadinov** [comment]
Is it  4cb031e?

**Comment by akostadinov** [comment]
sorry I meant is it de510381

**Comment by titusfortner** [comment]
It no longer verifies visibility of an element before attempting to take the action, it merely handles the exception returned by the driver.
```
gem install watir --pre
```
or
```
gem "watir", ">= 6.4.0.rc1"
```
and verify for yourself.

**Comment by titusfortner** [comment]
And no, it would be this one: dc05ce4505f1f84ae7a20e17f1f70cfa4874a740

**Comment by akostadinov** [comment]
Testing indeed indicates it is working now, but I fail to understand how is the `visible?` Check skipped when `relaxed_locate` is still turned on. Probably I need to spend more time understanding the code.

**Comment by titusfortner** [comment]
That toggle now manages what happens when the exception is thrown. Glad this is working for you.

**Comment by akostadinov** [comment]
I think I found it in `Element#element_call`:
```
    def element_call(exist_check = :wait_for_exists)
      already_locked = Wait.timer.locked?
      Wait.timer = Wait::Timer.new(timeout: Watir.default_timeout) unless already_locked
      begin
        if exist_check == :wait_for_enabled
          if self.is_a?(Input) || self.is_a?(Button) || self.is_a?(Select) || self.is_a?(Option)
            wait_for_enabled
          else
            wait_for_exists
          end
        else
          send(exist_check)
        end
...
```

Thank you!
