### ISSUE TITLE
Deprecration Warning from Selenium: :args or :switches is deprecated

### ISSUE THREAD

**Issue by designium** [watir/watir#572]
2017-07-05 09:51:35 WARN Selenium [DEPRECATION] :args or :switches is deprecated. Use Selenium::WebDriver::Chrome::Options#add_argument instead.

     b = Watir::Browser.new :chrome, args: %w[headless disable-gpu]

Is there anything that has to be changed in order to accept the args?

**Comment by titusfortner** [comment]
This is a good point. I think Watir needs to make it easier to interact with the changes Selenium needs to make. I'll work out some options for this. For now, ignore the deprecation warning.

**Comment by designium** [comment]
Thanks!

Cheers

Chim

**Comment by Cantzoul** [comment]
Just updated all my ruby gems and getting the same error now.

**Comment by titusfortner** [comment]
This has been fixed here: fd7820baff3e56d79b06bec1507034d68a9de6e6

Also, direct support for headless should get merged in soon: https://github.com/watir/watir/pull/593

**Comment by designium** [comment]
Thanks for the fix. 

Could you share what is the new syntax for headless and disable gpu?

Cheers!

**Comment by titusfortner** [comment]
All the good stuff is here: http://watir.com/watir-6-6/#watir-capabilities

But it is as simple as:
`Watir::Browser.new :chrome, headless: true`

**Comment by designium** [comment]
Thanks a lot!
