### ISSUE TITLE
(Partially) wrong offset

### ISSUE THREAD

**Issue by rvfx** [watir/watir#574]
I am using the `element.wd.location` and `element.wd.size` function with the selenium webdriver.

While some elements are shown at its correct position, some others have a wrong x position and sometimes a wrong y position. Does anyone have an idea what could cause this problem?

<img width="1085" alt="bildschirmfoto 2017-07-10 um 00 04 05" src="https://user-images.githubusercontent.com/6519355/27997970-8f813e00-6503-11e7-9ec7-ffb5da51b115.png">

**Comment by titusfortner** [comment]
The results come from the browser driver itself. I would expect the behavior to be different Chrome vs Firefox. It also may be that there is a race condition between when you are gathering the information and when the page finishes loading all of the dynamic content.

Regardless, this is not an issue with Watir (or Selenium) code. You can bring this up in the #selenium irc or Slack channels or post on the Selenium users group email.

**Comment by rvfx** [comment]
Ok, thank you!
