### ISSUE TITLE
Watir::Browser.new :phantomjs stops/freezes

### ISSUE THREAD

**Issue by jcarlos7121** [watir/watir#577]
I installed Watir on my ubuntu server 16.04, and using phantomjs 1.9,

Whenever i open a remote console with rails console, and type

Watir::Browser.new :phantomjs

my console just stops, and i cannot type any other command, it just stays there forever.

Is there somewhere i could look for the log files to see whats happening?

**Comment by titusfortner** [comment]
Yes, you can set `Selenium::WebDriver.logger.level = :debug` and see details.

**Comment by jcarlos7121** [comment]
Thanks!!
