### ISSUE TITLE
Object not found in wait_while_present

### ISSUE THREAD

**Issue by husieo** [watir/watir#589]
I use the method wait_while_present to ensure that the element disappeared, but it makes little sense for this method to return an error if an element is already not present. 

Right now I have to wrap the code with a condition for the presence of a document, which should not be the case.

```
Minitest::UnexpectedError: Watir::Wait::TimeoutError: timed out after 30 seconds, waiting for false condition on #<Watir::Div: located: false; {:text=>"whitelist.txt", :tag_name=>"div"}>
    C:/Ruby/lib/ruby/gems/2.4.0/gems/watir-6.4.3/lib/watir/wait.rb:72:in `while'
    C:/Ruby/lib/ruby/gems/2.4.0/gems/watir-6.4.3/lib/watir/wait.rb:151:in `wait_while'
    C:/Ruby/lib/ruby/gems/2.4.0/gems/watir-6.4.3/lib/watir/wait.rb:193:in `wait_while_present'

```

**Comment by titusfortner** [comment]
Can you show your code? The specs show everything is working as intended (immediately returning when it does not see an element, regardless of whether it has been previously located). 
I need more information to reproduce this.

**Comment by titusfortner** [comment]
If you can send a way to duplicate this failure I'll reopen this. Thanks.
