### ISSUE TITLE
Define What all goes in Watir 7

### ISSUE THREAD

**Issue by titusfortner** [watir/watir#590]
What things do we think belong in a major version update? I'd like to plan on one later this year. Thoughts?

**Comment by titusfortner** [comment]
@p0deje do you have any strong thoughts on this?

Maybe we write the code and have the PRs ready to drop when Selenium 4 is released and we can do it at the same time again.

It'll probably depend on how long it takes Selenium to release, but maybe we don't want to rush 7.0, either?

**Comment by p0deje** [comment]
I really have no big plans for the future releases, so I guess once Selenium 4 is released it might be the biggest reason to release Watir 7. I wouldn't rush for it also.

**Comment by titusfortner** [comment]
I think what is tagged with Watir-7 label right now is what I'm interested in for v7
