### ISSUE TITLE
HTML Input Type Date Not Supported

### ISSUE THREAD

**Issue by brnscc08** [watir/watir#595]
WATIR v6.1.0, Selenium v3.4.3, chromedriver 2.30, chrome v59.0.3071.115
```Ruby
pry(main)> @browser = Watir::Browser.new :chrome
pry(main)> @browser.goto("https://www.w3schools.com/html/tryit.asp?filename=tryhtml_input_date")
=> "https://www.w3schools.com/html/tryit.asp?filename=tryhtml_input_date"
pry(main)> @browser.text_field(:name =>"bday").exists?
=> false
pry(main)> @browser.button(:text=>"Submit").exists?
=> true
```

Using watir I navigated to the w3schools.com test page for input date type.  Upon checking if the input type date exists I get false.  To make sure the page was working I followed it up by checking the Submit button is present and it came back as expected; true.

The date type is new to HTML5 so I believe this type may not be currently supported.

**Comment by titusfortner** [comment]
There's an iframe in there :)
```
@browser.iframe(id: 'iframeResult').text_field(name: 'bday').exists?
=> true
```

**Comment by brnscc08** [comment]
D'oh always forget about iframe as I don't often interact with them.  However, I get an error upon trying to set the value of that text field.  

```Ruby
@browser.iframe(id: 'iframeResult').text_field(name: 'bday').set "08/01/2017"
Selenium::WebDriver::Error::InvalidElementStateError: invalid element state: Element must be user-editable in order to clear it.
  (Session info: chrome=59.0.3071.115)
  (Driver info: chromedriver=2.30.477690 (c53f4ad87510ee97b5c3425a14c0e79780cdf262),platform=Mac OS X 10.11.6 x86_64)
```

There is a workaround I can use, but would really like to see the date type supported in the future if possible.

```Ruby
@browser.iframe(id: 'iframeResult').input(name: 'bday').send_keys "08/01/2017"
```

**Comment by titusfortner** [comment]
Oh interesting. Yes, we should see about explicitly supporting date type differently. It would be nice if we can find a way to send a `DateTime` to that element instead of a String, but I'm not sure how compatible that is with all date elements.

**Comment by titusfortner** [comment]
Ok, so this is a chromedriver bug: https://bugs.chromium.org/p/chromedriver/issues/detail?id=1319

Also, unfortunately, I don't think there is a way to get the format of the html5 date type since it is based on the browser / OS locale. 

So, I'm going to close this again as something we can't do anything about at this time.
