### ISSUE TITLE
Watir in docker container (chrome browser)

### ISSUE THREAD

**Issue by potapovDim** [watir/watir#599]
Hello , i try to setup watir in docker container
spec cant run chrome

Dockerfile
__________________________________________________
FROM debian:jessie

RUN apt-get update && apt-get install -y curl xvfb chromium wget xvfb unzip zlib1g-dev ruby bundler git libxi6 libgconf-2-4

RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
RUN echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list

RUN apt-get update
RUN apt-get install -y google-chrome-stable

ENV CHROMEDRIVER_VERSION 2.30
ENV CHROMEDRIVER_DIR /chromedriver

RUN mkdir $CHROMEDRIVER_DIR
RUN wget -q --continue -P $CHROMEDRIVER_DIR "http://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip"
RUN unzip $CHROMEDRIVER_DIR/chromedriver* -d $CHROMEDRIVER_DIR

ENV PATH $CHROMEDRIVER_DIR:$PATH
RUN gem install watir
RUN gem install chromedriver-helper

RUN chmod +x $CHROMEDRIVER_DIR/chromedriver*
ADD simple.e2e.rb /spec/simple.e2e.rb

ADD xvfb-setup /usr/bin/xvfb-setup

RUN ln -s /usr/bin/xvfb-setup /usr/bin/chrome-stable
RUN ln -s /usr/bin/xvfb-setup /usr/bin/chrome
__________________________________________________
setup x server file 
__________________________________________________
`#!/bin/bash

_kill_procs() {
  kill -TERM $chromium
  wait $chromium
  kill -TERM $xvfb
}

trap _kill_procs SIGTERM

XVFB_WHD=${XVFB_WHD:-1280x720x16}

Xvfb :99 -ac -screen 0 $XVFB_WHD -nolisten tcp &
xvfb=$!

export DISPLAY=:99

chromium --no-sandbox $@ &
chromium=$!

wait $chromium
wait $xvfb
__________________________________________________

spec file 
__________________________________________________
require 'watir'

@browser = Watir::Browser.new :chrome

@browser.goto 'https://google.com'

print @browser.text
`
and it fail 
"ruby/2.1.0/net/protocol.rb:158:in `rescue in rbuf_fill': Net::ReadTimeout (Net::ReadTimeout)"

ps: with firefox work perfect

**Comment by ddavison** [comment]
why not use the https://github.com/SeleniumHQ/docker-selenium containers, and just run your watir tests against those?

**Comment by titusfortner** [comment]
Since this isn't technically an issue with Watir code, I'm closing this. Please feel free to reach out to us on our mailing list or in Slack if you would like to discuss this further.
