### ISSUE TITLE
Attribute Location

### ISSUE THREAD

**Issue by titusfortner** [watir/watir#600]
So, while looking at #207, we have a big issue with how attribute location is working. I guess this means that no one really uses it? :)

I think this is a result of #261. We need to get the generator working again and be able to update the code. I don't really understand it well enough to know what it is doing. :-/

For instance, with this html:
```html
 <div tabindex="1">Foo</div>
```
To select the element, the xpath needs to contain "tabindex", which is precisely the way that the current code does not let you use.

```ruby
# underscore (selector builder converts to dash)
browser.div(tab_index: "1")).exist?
# 2017-08-03 00:07:02 DEBUG Watir Converted {:tab_index=>"2"} to [:xpath, ".//div[@tab-index='2']"]

# downcase
browser.div(tabindex: "1").exist?
# Watir::Exception::MissingWayOfFindingObjectException: invalid attribute: :tabindex

# camelcase
browser.div(tabIndex: "1").exist?
# 2017-08-03 00:07:02 DEBUG Watir Converted {:tabIndex=>"2"} to [:xpath, ".//div[@tabIndex='2']"]
```

Just aliasing the method between `tabindex` & `tab_index` will still raise the exception for invalid attribute.

This looks like it is an issue with every single camel case attribute in `html_elements.rb`
Which I guess means we aren't testing any of these attribute location strategies right now?

**Comment by p0deje** [comment]
#207 and #28 is about attribute methods:

```ruby
browser.div.tab_index
```

Nobody really looked into selectors, so I'm not sure what works and doesn't work there.

Tricky part here is that you have to translate some of them to dashed and some to camelCase. For example, `tab_index` should be `tabindex`, while `http_equiv` should be `http-equiv`. There are many cases so #601 should take into account.

**Comment by titusfortner** [comment]
#207 talked about both... But this is a good question. Do we need underscores for any of these? Doesn't `#itemtype` make more sense than `#item_type` if the actual attribute that someone sees in the html is the latter?

**Comment by titusfortner** [comment]
fixed!
