### ISSUE TITLE
Fix Generator

### ISSUE THREAD

**Issue by titusfortner** [watir/watir#602]
We need to get the generator code working again. 

My cursory investigation also leads me to wonder if we shouldn't be basing our code off of [W3C HTML 5.1](https://www.w3.org/TR/html/) instead of the [HTML Living Standard](https://github.com/whatwg/html) like we're currently doing. If we are going to use the latter, we probably should be running the generator regularly (before releasing). There appears to be considerable disdain toward W3C from WHATWG members, but I also kind of like the idea of saying we are "version X" compatible. 🤷‍♂️ 

Living Standard also has a [raw file on github](https://github.com/whatwg/html/blob/master/source) we can parse instead of working with a much larger html file.

This might also mean updating Jari's IDL code? Or forking it? Or rewriting something similar but different?

**Comment by titusfortner** [comment]
For giggles I tried to implement something with some complicated nokogiri parsing, completely avoiding the webidl gem. It.. mostly works, but obviously I needed to use hard coded variables and things that aren't desirable, and I'm stuck on getting the `GlobalEventHandlers` and `WindowEventHandlers` to work, since they aren't at all delineated in the xml. And multiple elements implement them; right now now everything is getting put in `HTMLElement` where only `GlobalEventHandlers` belong. :-/

Anyway, this is it. Not sure how worthwhile it is to keep going with it. I think it'd get us 90% of what we want, but then there's a chance that it's going to miss things. https://github.com/watir/watir/commit/6de374

There have been a bunch of changes to the spec in the past 2 years, though it's hard to say how much because the order of the old and new spec files is also very different.

**Comment by p0deje** [comment]
I'm not sure when I'll have time to take a look at it, but generally usage of WebIDL gem is simple, we just need to extract IDL interfaces correctly and pass them in.

In past, most of the issues were coming from the fact that HTML spec had bugs and/or invalid IDLs.

**Comment by titusfortner** [comment]
Fixed now.
