### ISSUE TITLE
Watir (chrome+options) failing with new versions of libs

### ISSUE THREAD

**Issue by Paul3816547290** [watir/watir#606]
I installed up a new machine with ruby, watir, and selenium-webdriver and the script (that still runs on the previous version) now will not start

I produced a minimal script below and the reported error (with version numbers visible in the dump)

Is there a workaround to get the new machine going.  I tried to uninstall the gems and install the older versions but this did not appear to work and just installed the same versions again.

--- simple script

require 'watir'

options = Selenium::WebDriver::Chrome::Options.new
options.add_argument('--disable-infobars')
driver = Watir::Browser.new :chrome, options: options

--- result

C:>watir test.rb
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/selenium-webdriver-3.4.4/lib/selenium/webdriver/chrome/options.rb:43:in `initialize': wrong number of arguments (1 for 0) (ArgumentError)
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/watir-6.6.0/lib/watir/capabilities.rb:68:in `new'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/watir-6.6.0/lib/watir/capabilities.rb:68:in `process_browser_options'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/watir-6.6.0/lib/watir/capabilities.rb:28:in `process_capabilities'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/watir-6.6.0/lib/watir/capabilities.rb:15:in `to_args'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/watir-6.6.0/lib/watir/browser.rb:47:in `initialize'
        from .../watir test.rb:5:in `new'
        from .../watir test.rb:5:in `<main>'

---- previous install on an older machine still works fine

waitr 6.3
selenium-webdriver 3.4.3

----- comment by  Titus Fortner (watir Forums)

Watir isn't handling it correctly if a Selenium Options class is passed in.

**Comment by titusfortner** [comment]
Thanks for filing the issue.

The goal is for Watir users not to have to initialize Selenium classes any more when creating a Browser. That being said, we should accept objects that have been created by the user already.

This should fix it: https://github.com/watir/watir/commit/02fbdd287ce8af71621bb68f53004c8fda492fd7

I'll release a bug fix update soon.

**Comment by titusfortner** [comment]
This fix has been released with 6.6.1
