### ISSUE TITLE
Error while starting Chrome in headless mode

### ISSUE THREAD

**Issue by darkogj** [watir/watir#611]
I'm using Windows (and I've tried starting Chrome in headless mode using Capybara, it worked, so this is a Watir issue).

When I do:

`Watir::Browser.new :chrome, headless: true`

I get:

`C:/Ruby22/lib/ruby/gems/2.2.0/gems/watir-6.6.1/lib/watir/capabilities.rb:65:in `process_browser_options': undefined method `<<' for nil:NilClass (NoMethodError)
	from C:/Ruby22/lib/ruby/gems/2.2.0/gems/watir-6.6.1/lib/watir/capabilities.rb:28:in `process_capabilities'
	from C:/Ruby22/lib/ruby/gems/2.2.0/gems/watir-6.6.1/lib/watir/capabilities.rb:15:in `to_args'
	from C:/Ruby22/lib/ruby/gems/2.2.0/gems/watir-6.6.1/lib/watir/browser.rb:47:in `initialize'
	from C:/Users/User/RubymineProjects/daily_valuable_expired_domains/test.rb:6:in `new'
	from C:/Users/User/RubymineProjects/daily_valuable_expired_domains/test.rb:6:in `<top (required)>'
	from -e:1:in `load'
	from -e:1:in `<main>'
`

**Comment by titusfortner** [comment]
Yup, I broke it. This will fix it: https://github.com/watir/watir/commit/ffcc25.
I'll make a new release later today.
Thanks.

**Comment by darkogj** [comment]
Cool. Thank you for the awesome work for this gem!

**Comment by titusfortner** [comment]
6.6.2 is released
