### ISSUE TITLE
Element Existentialism

### ISSUE THREAD

**Issue by titusfortner** [watir/watir#626]
Similar and related ideas:

* Selenium: `#find_element` & `#displayed?`
* Watir: `#exist?`, `#visible?`, `#present?`
* W3C: `"interactable"`, 

Many of these are non-intuitive for their actual behavior.
"exist" probably makes the most sense.
"present" is typically a synonym for "exist," but it also has the connotation of "being in view" so it can also be synonymous with "visible", but "displayed" would seem to be more correct/precise. In practice this is what we use for "interactable"
"visible" has the added complication of indicating to a user that they can see it on the page they are looking at without scrolling

As far as current behaviors go, I can't think of any reasons to favor #visible?, over #present?
I've been considering after looking through `watir-scroll`, is the idea of "inside viewport". 

How big of a deal would it be to deprecate `#visible?` in favor of `present?` in Watir 6, and then re-introduce it in Watir 7 as "exists, present, and entirely contained in the current viewport"? Actually, I kind of want to deprecate `#visible?` regardless because i think it is just unnecessary confusion that it is almost exactly the same but slightly and non-intuitively different.

I'm not completely sold that this is a good enough idea to break backward compatibility, but I thought I'd throw it out there to see what others think.

**Comment by jkotests** [comment]
+1 for deprecating `#visible?`

I have always recommended the usage of `#present?` first. There are some places where `exists?` is important. I haven't had a reason to recommend the usage of `#visible?`. I'm not convinced that re-implementing it as "in the current viewport" is needed. At least I cannot think of a situation where the differentiation between requiring scrolling or not mattered.

**Comment by titusfortner** [comment]
I have had people ask about it, or at least be surprised that it was saying visible when they couldn't see it. The Page Object gem's test for scrolling actually uses that method assuming it will be false if it isn't scrolled there. :)

That being said, I'm not sure it is actually real world useful to most people, either, especially if it causes any confusion to change it.

**Comment by akostadinov** [comment]
In my tests I never needed this. But consider somebody wants to perform responsiveness testing. They may want to make sure some elements are visible/non-visible depending on browser window size. I don't mind if nother method name might be chosen for it though. Just saying, I don't have a horse.

**Comment by husieo** [comment]
In my tests, I sometimes experience the need for `#accessible?`.
Example scenario:
1. Modal popup window is opened
2. Parent popup window calls nested popup window.
3. Interaction with nested popup window is completed, nested window is closed.
4. I try to interact with parent window, but (in case the browser is fast enough) the element in parent window is present, but cannot be clicked yet, so I have to explicitly wait with `sleep(some_time)`.

**Comment by titusfortner** [comment]
Watir can only implement something it can poll for. Do you know why the element can't be clicked? Or is it getting clicked, but nothing happens?

**Comment by akostadinov** [comment]
I don't know if this is related to @Droom1995's  issue. In our testing it is a problem that sometimes page script is not fully loaded before elemets are interacted with. For example I notice with marionette that one check - a warning appears on invalid value, that is more often than not failing. If I do the operation manually it always works. Particularly an issue with angular websites. Hard-coding waits is also inefficient. Resolving such issues on a case by case basis but it is a pain. I'm not sure if watir can help in any way though.

**Comment by husieo** [comment]
@titusfortner For example, button is on the page, but hidden behind the temporary popup window - right now Watir gives an exception "Element is not clickable at point ..." right away, but it might be a good idea to wait for some time before the element becomes accessible.
Like on this picture, if I click "Hide modal popup" and then "Show modal popup" in the code subsequently, the execution might fail, because Watir will try to click the button "Show" while the modal window was still not closed.
![image](https://user-images.githubusercontent.com/7140299/29960847-9d9baa92-8efd-11e7-86fc-c6cbf4942bc6.png)

@akostadinov I believe it's a bit different, in your case `#present?` method or `#wait_until_present` should be sufficient. I have encountered some cases when this is not true, but not so often. Can you provide some specific example?

**Comment by titusfortner** [comment]
@akostadinov I'm looking to make an angular gem that includes angular specific locators and the ability to do waits like this: https://github.com/watir/watir/pull/387 I was hoping someone(s) might be interested in working on it at the Toronto Hackathon in a couple weeks.

@Droom1995 Yeah, we decided not to automatically retry "Element is not clickable" exceptions. I have ideas for Watir 7.0 that will make it easier to customize Watir to make this easier. In the meantime, you might want to wrap it where you might have an issue:

```ruby
def clickable_click(element)
  element.click
rescue Selenium::WebDriver::Exception::UnknownException => ex
  raise unless ex.message.include('Element is not clickable')
  retry
end
```

**Comment by akostadinov** [comment]
wow, I was going to try inserting elements based on `ng-view` angular hooks then wait for the elements. But what I see in the related PR looks really interesting.

**Comment by titusfortner** [comment]
@akostadinov, I'd love help with this one: https://github.com/titusfortner/watir_angular
I don't know enough Angular to know if what this does is the best approach. :)
