### ISSUE TITLE
Passing Proxy Options to :phantomjs Browser?

### ISSUE THREAD

**Issue by ninp0** [watir/watir#629]
This used to work but no longer honors proxy settings:
https://github.com/ninp0/csi/blob/master/lib/csi/plugins/transparent_browser.rb#L89-L117

What steps need to be take to pass proxy parameters to the :phantomjs browser?

**Comment by titusfortner** [comment]
Bah. I really hate capabilities. Yes,`:driver_opts` is a valid option that is currently not getting processed by Watir. I'll fix it and make a new release. Thanks for filing the bug.

Also note that phantomjs is likely being deprecated with the next major release of Selenium.

**Comment by ninp0** [comment]
Good to know - thanks for the heads up and thanks for your help!

**Comment by titusfortner** [comment]
Merged & Released with 6.7.3

**Comment by ninp0** [comment]
When will https://rubygems.org/gems/watir/versions/6.7.3 be avilable?

**Comment by titusfortner** [comment]
ugh, I thought I released it already. Done now. Thanks for checking.

**Comment by ninp0** [comment]
Thanks!
