### ISSUE TITLE
problem with FIrefox legacy driver in 6.7.3

### ISSUE THREAD

**Issue by akostadinov** [watir/watir#634]
Hello,

```
firefox_profile = Selenium::WebDriver::Firefox::Profile.new
client = Selenium::WebDriver::Remote::Http::Default.new
client.open_timeout = 180
caps = Selenium::WebDriver::Remote::Capabilities.firefox(marionette: false)
@browser = Watir::Browser.new :firefox, :profile => firefox_profile, :http_client=>client, desired_capabilities: caps
```

This results in:
```
Exception: ArgumentError: unknown option: {:options=>#<Selenium::WebDriver::Firefox::Options:0x0000f36b68b168 @args=[], @binary=nil, @profile=#<Selenium::WebDriver::Firefox::Profile:0x0000f36b6febb8 @model=nil, @native_events=false, @secure_ssl=false, @untrusted_issuer=true, @load_no_focus_lib=false, @additional_prefs={}, @extensions={}>, @log_level=nil, @prefs={}, @options={}>}
--
0: /home/avalon/.gem/ruby/gems/selenium-webdriver-3.5.1/lib/selenium/webdriver/remote/bridge.rb:86:in `initialize'
1: /home/avalon/.gem/ruby/gems/selenium-webdriver-3.5.1/lib/selenium/webdriver/firefox/legacy/driver.rb:54:in `new'
2: /home/avalon/.gem/ruby/gems/selenium-webdriver-3.5.1/lib/selenium/webdriver/firefox/legacy/driver.rb:54:in `initialize'
3: /home/avalon/.gem/ruby/gems/selenium-webdriver-3.5.1/lib/selenium/webdriver/firefox/driver.rb:35:in `new'
4: /home/avalon/.gem/ruby/gems/selenium-webdriver-3.5.1/lib/selenium/webdriver/firefox/driver.rb:35:in `new'
```

If I hook to `legacy/driver.rb:54` and check the options, then I see:
```
[1] pry(#<Selenium::WebDriver::Firefox::Legacy::Driver>)> opts
=> {:http_client=>
  #<Selenium::WebDriver::Remote::Http::Default:0x0000f36b77e188
   @open_timeout=180,
   @read_timeout=nil>,
 :options=>
  #<Selenium::WebDriver::Firefox::Options:0x0000f36954ee28
   @args=[],
   @binary=nil,
   @log_level=nil,
   @options={},
   @prefs={},
   @profile=
    #<Selenium::WebDriver::Firefox::Profile:0x0000f36b6febb8
     @additional_prefs={},
     @extensions={},
     @load_no_focus_lib=false,
     @model=nil,
     @native_events=false,
     @secure_ssl=false,
     @untrusted_issuer=true>>,
 :url=>"http://127.0.0.1:7056/hub"}
```

Basically the `options` option is not recognized by `Remote::Bridge.new`. I think issue is some recent changed because this has been working with Watir 6.5

Any ideas how to fix or workaround?

**Comment by akostadinov** [comment]
The above also works fine without `marionette: false`. But for Firefox ESR still 52. And SSL insecure does not work fine on it AFAIK.

**Comment by titusfortner** [comment]
I think I'd rather consider legacy Firefox as deprecated than add code to specifically support it in Watir.

It will still work if you do:

```
caps = Selenium::WebDriver::Remote::Capabilities.firefox(marionette: false)
browser = Watir::Browser.new :firefox, desired_capabilities: caps
```

**Comment by akostadinov** [comment]
Ok, thank you, that was the path I was going to try provided no other solution. It is also likely that the inconsistency is better fixed inside selenium webdriver but I also don't want to spend much time on it.

Just FYI I spent the day using marrionette vs FF55 in my dev environment. It's not so stable as I'd hope. A number of times marionette failed to start FF with some communication problem error. Also on a number of pages sometimes I saw events triggered - sometimes not. That might be also FF or timing issues though. Just a warning that switch to marionette might not be entirely smooth.

**Comment by akostadinov** [comment]
I misread your comment, sorry. I do exactly this:
```
        caps = Selenium::WebDriver::Remote::Capabilities.firefox(marionette: false)
        @browser = Watir::Browser.new :firefox, desired_capabilities: caps
```

And then I'm getting:
```
      unknown option: {:options=>#<Selenium::WebDriver::Firefox::Options:0x00008410052e60 @args=[], @binary=nil, @profile=nil, @log_level=nil, @prefs={}, @options={}>} (ArgumentError)
```

The issue is exactly the `desired_capabilities` bit, not any of the other options.

**Comment by titusfortner** [comment]
Yeah, Firefox w/ Geckodriver might still have some timing issues, but there shouldn't be communication issues. Is it the "127.0.0.1" error?

Ok, yeah Watir might be sending a blank Options that won't work with legacy Firefox. Oh, and you can't just use 6.5 because 6.4 broke something that you need 6.5 for? Sigh. Might need to stick with 6.3 until I get a fix out. Sorry.

**Comment by titusfortner** [comment]
Or you can \<head hanging in shame\> use 6.4 and monkey patch the fix in the commit you referenced on my blog.

**Comment by titusfortner** [comment]
Wait, sorry, 6.4.3 should fix what you need. The bug fix in 6.5 was just an optimization to relocate elements in collections, shouldn't affect backward compatibility at all.

**Comment by titusfortner** [comment]
Another option that might work (I need to test all these things) is to do:
```ruby
caps = Selenium::WebDriver::Remote::Capabilities.firefox
browser = Watir::Browser.new :firefox, desired_capabilities: caps, marionette: false
```
I think it defaults to putting extra values in opt if a caps already exists. Not ideal. I need to spend more time on Capabilities it looks like.

**Comment by akostadinov** [comment]
For anybody needing this, here's how I made it work. I don't see this documented. I think the bug is in Selenium::Webdriver that doesn't handle `options` option properly (SeleniumHQ/selenium/issues/4602). btw the legacy driver seems to still work with FF55 as well and appears more stable to me. Or it is not so fast thus missing some timing issues.. I need to play more with it.

```ruby
        caps = Selenium::WebDriver::Remote::Capabilities.firefox marionette: false, profile: firefox_profile #, firefox_binary: "/home/user/local/firefox-52-esr/firefox"
        # options = Selenium::WebDriver::Firefox::Options.new(profile: firefox_profile, binary: "/home/user/local/firefox-52-esr/firefox")
        driver = Selenium::WebDriver.for :firefox, desired_capabilities: caps, http_client: client
        @browser = Watir::Browser.new driver
```

P.S. firefox profile can be used to set proxy and client can be used to set read timeout. If you don't need those, then these options may be omitted.

**Comment by titusfortner** [comment]
@akostadinov if you are running on Firefox 55, you are very unlikely to be using the legacy driver. You should be able to see when you turn on logging which protocol is getting used: `Selenium::WebDriver.logger.level = :debug`

The point of the `Watir::Capabilities` class is to allow users to configure everything they need without unnecessarily needing to initialize any Selenium objects.

Ideally you should be able to do:

`Watir::Browser.new :firefox, read_timeout: 120, proxy: my_proxy, options: {profile: firefox_profile, binary: binary_path}`

But, this explicitly doesn't work with Legacy Firefox.

**Comment by akostadinov** [comment]
I can identify easily which protocol is used. When using geckodriver, there is a robot left of the URL bar. When using legacy, there isn't. I was also surprised legacy works fine with ff 55.

I tried your debug log approach. But I couldn't quickly figure out which exactly messages are relevant for protocol used. In the very beginning I see:
```
2017-08-30 22:01:41 DEBUG Selenium {:extenstion=>:webdriver}
2017-08-30 22:01:41 DEBUG Selenium Executing Process ["/usr/bin/firefox", "-no-remote", "-foreground"]
2017-08-30 22:01:41 DEBUG Selenium polling for socket on ["127.0.0.1", 7055]
```
Which to me doesn't look like `geckodriver`. Not sure though. Thanks in any case. Things are now working both ways. Hope this dual driver madness to end soon.
