### ISSUE TITLE
cannot load such file -- watir/extensions/select_text (LoadError) requiring 'page-object'

### ISSUE THREAD

**Issue by Sebisnow** [watir/watir#635]
I get the following error since the new watir version 6.8. Using 6.7.3 everything works like a charm

    cannot load such file -- watir/extensions/select_text (LoadError)
    /var/lib/gems/2.3.0/gems/page-object-2.2.2/lib/page-object/elements/element.rb:2:in `require'
    /var/lib/gems/2.3.0/gems/page-object-2.2.2/lib/page-object/elements/element.rb:2:in `<top (required)>'
    /var/lib/gems/2.3.0/gems/page-object-2.2.2/lib/page-object/elements.rb:29:in `require'
    /var/lib/gems/2.3.0/gems/page-object-2.2.2/lib/page-object/elements.rb:29:in `<top (required)>'
    /var/lib/gems/2.3.0/gems/page-object-2.2.2/lib/page-object/widgets.rb:1:in `require'
    /var/lib/gems/2.3.0/gems/page-object-2.2.2/lib/page-object/widgets.rb:1:in `<top (required)>'
    /var/lib/gems/2.3.0/gems/page-object-2.2.2/lib/page-object.rb:11:in `require'
    /var/lib/gems/2.3.0/gems/page-object-2.2.2/lib/page-object.rb:11:in `<top (required)>'

Is that an issue with you guys or a dependency issue within page-object?
I use the latest page-object version 2.2.2.

Gemfile.lock:

    page-object (2.2.2)
      page_navigation (>= 0.10)
      selenium-webdriver (~> 3.0)
      watir (~> 6.7)

**Comment by titusfortner** [comment]
Yes, Watir reconfigured its JavaScript so that this extension is no longer used. 
I've made a PR for addressing this in Page Object gem: https://github.com/cheezy/page-object/pull/445

You'll need to continue using Watir 6.7.3 until Page Object gem is updated.
Thanks for reporting this.
