### ISSUE TITLE
assert_enabled does not check for visibility of element

### ISSUE THREAD

**Issue by mikewkwan** [watir/watir#636]
Trying to use `.click` on an element with `display: none` does not seem to timeout

From what I can see,  `.click` now asserts enabled and exists, both of which would return try to an element with `display: none`.

**Comment by titusfortner** [comment]
`#assert_enabled` shouldn't check for visibility, they are completely
separate things.

What do you mean by "does not seem to timeout?" Default timeout is 30
seconds. Is the element getting clicked and moving on to the next line, or
is it hanging for longer than the specified timeout?

As of Watir 6.4, the implementation was changed to attempt to take the
click and properly respond to what is returned by the driver instead of
making a bunch of extra wire calls ahead of time.

**Comment by mikewkwan** [comment]
Well, from what I can see, calling `.click` on an element that has css `display: none;` causes my tests to hang indefinitely, even though I assume it should timeout after 30 seconds.

**Comment by titusfortner** [comment]
Can you turn on selenium logging and provide the results? `Selenium::WebDriver.logger.level = :info` maybe do `Watir.logger.level = : info` as well in case. Thanks

**Comment by jrmartinez03** [comment]
@titusfortner  @mikewkwan I would like to restate the problem, if I may: `Watir::Element#wait_for_enabled` used to call `#wait_for_present` > `#wait_until_present` > `#present?` > `#visible` [see this commit](https://github.com/watir/watir/commit/dc05ce4505f1f84ae7a20e17f1f70cfa4874a740#diff-a0982f69261cbd95246962ebecdabf3cL538) - so if an element existed but was visible, Watir automatically waited for it to become present and enabled. Now, there is no `#wait_for_present`, and if one tries to interact with an element that is located but not visible, the exception `element present and enabled, but timed out after 60 seconds, waiting for #<Watir::TextField: located: true; {:css=>"...", :tag_name=>"input"}> to not be disabled (Watir::Exception::ObjectDisabledException)` is thrown (despite what the exception message say, there is no waiting at all, the error occurs when trying to interact with an invisible/disabled element).

Maybe "enabled" and "visible" are two separate things, but this represents a change in functionality, as I now need to `#wait_until_present` before setting such fields, which I don't think was an intended consequence.

**Comment by titusfortner** [comment]
So the element is present but disabled, but needs to wait until it is enabled?

**Comment by jrmartinez03** [comment]
Element is NOT present, i.e. `@element.displayed?` is false.

**Comment by titusfortner** [comment]
We're not going to go back to checking for present before hand because of performance reasons. Watir still has to check enabled before attempting to locate it because the driver will allow you to click a disabled button, while Watir needs to throw an exception. It should still wait, and that error does not look right.

Which is just to say that I need to understand the order so I can duplicate so I can fix. Logging the steps could help.

**Comment by titusfortner** [comment]
Ok, after some time investigating. 

I've duplicated this issue:

> calling .click on an element that has css display: none; causes my tests to hang indefinitely

I think I have the fix; when a user clicks on an element that never becomes visible it will time out after the specified time.

I can't duplicate issue:

> if one tries to interact with an element that is located but not visible, the exception element present and enabled, but timed out after 60 seconds, waiting for #<Watir::TextField: located: true; {:css=>"...", :tag_name=>"input"}> to not be disabled (Watir::Exception::ObjectDisabledException) is thrown

What are you doing to get it?

**Comment by jrmartinez03** [comment]
@titusfortner here's an example: 
```
require 'watir'

url = 'https://app.launchdarkly.com/login'
browser = Watir::Browser.start(url)

browser.text_field(css: '#username').set('username@email.com')
browser.button().click
browser.text_field(css: '#password').set('password')

```

**Comment by jrmartinez03** [comment]
You can see here the password field `#exists?` and `#enabled?` but is not `#visible?`

**Comment by titusfortner** [comment]
Ok, thanks. I verified that my fix also works for the use case provided. They were both symptoms of the same problem: https://github.com/watir/watir/commit/00c39a

It'll work in 6.8.2 whenever that gets released (likely later this week).

**Comment by jrmartinez03** [comment]
Sorry @titusfortner but this doesn't resolve the issue. To better demonstrate the missing automatic wait, try running the steps this way:
```
require 'watir'

url = 'https://app.launchdarkly.com/login'
browser = Watir::Browser.start(url)

browser.text_field(css: '#username').set('username@email.com'); browser.button().click; browser.text_field(css: '#password').set('password')
```

**Comment by jrmartinez03** [comment]
It seems appropriate that `#wait_for_writable` would `#wait_for_present`, but this issue also affects button clicks - we now have to `button.wait_until_present.click` or `button.wait_until(&:visible?).click`.

**Comment by titusfortner** [comment]
It looks like I unnecessarily restricted the allowed messages when rescuing `InvalidElementStateError`. Everything is passing when I remove the restriction, so should have the fix ready soon.  Thanks.

**Comment by titusfortner** [comment]
Ok, 6.8.3 has been released. Let us know if that doesn't solve the problem. Thanks for reporting this.

**Comment by jrmartinez03** [comment]
@titusfortner that does solve the problem for disabled text fields, but I still have to #wait_for_present on button clicks, there is no automatic wait for element to become present before #click:
```
url = 'https://app.launchdarkly.com/login'
browser = Watir::Browser.start(url)
Watir.default_timeout = 3

browser.button(css: ".Button:enabled").text #waits as expected before raising UnknownObjectException
browser.button(css: ".Button:enabled").click #does not wait, immediately raises UnknownObjectException
```

**Comment by titusfortner** [comment]
fingers crossed that 6.8.4 fixes all the things.
