### ISSUE TITLE
WATIR goes into infinite loop when the element is invisible

### ISSUE THREAD

**Issue by Rajagopalan-M** [watir/watir#649]
WATIR goes into infinite loop when the element is invisible, It's not coming out of the loop in given time of WATIR default time out.

**Comment by titusfortner** [comment]
1. Make sure you are seeing this with Watir 6.8.4
2. Provide a reproducible test case.

**Comment by Rajagopalan-M** [comment]
@titusfortner  yes it works fine in WATIR 6.8.4 now. Thanks.
