### ISSUE TITLE
Newly created click! is not holding the page load

### ISSUE THREAD

**Issue by Rajagopalan-M** [watir/watir#652]
## Meta -
Watir Version: 6.8.4
Selenium Version: 3.5.2
Browser Version: Firefox

## Expected Behavior -
click! has to hold the page load after the click 
## Actual Behavior -
It's not holding the page load after the click
## Steps to reproduce -

b.element(name: 'q').click!

Actually this is not holding the page load because it's javascript click and it's expected but we could have included b.wait(b.default_timeout) inside the method click!. Since WATIR already has wait() javascript function, we could have included wait() inside click! function something like

```
def click!
     document.getElementById("something").click
     wait(default_timeout) #I would be calling b.wait(10) from my program
end
```

**Comment by Rajagopalan-M** [comment]
@jkotests  Can you please consider this issue as well?

**Comment by jkotests** [comment]
@Rajagopalan-M, can you provide an example where this is a problem? I think I understand your point, but it would be easier to have a concrete example to ensure we have actually addressed the problem.

**Comment by Rajagopalan-M** [comment]
@jkotests 

Any click which navigate to the next page would be my example, it's not waiting for page to load, it moves to the next line of execution, So next line is waiting for the particular element to exist, So watir_default time out of next line is getting utilized while page is loading. I am concerning this issue because WATIR paves the way to write code in both selenium and Javascript, So If WATIR maintains the Javascript coding to the level of Selenium while I try to write through Javascript it would be so good. 

For an example, consider following code

```
b.element(id: 'something').click!
b.element(id: 'policyNumber').send_keys '23232323'
```

Since first line releases the control immediately after the click, the default time out for an element to exist of second line of code will be utilized, that's not correct. So If WATIR uses it's javascript wait statement as I said in my original message, we could accomplish the same behavior while I we use Javascript as well.

**Comment by jkotests** [comment]
@Rajagopalan-M, sorry, I don't understand the example. Won't `send_keys` wait for the element to be present, which presumably means the page loaded? Why does it matter if `click!` is the one waiting for the page load vs `send_keys`? It would help if you could give a runable example that has problems.

**Comment by Rajagopalan-M** [comment]
@jkotests  send_keys waits for element to exist but click! function immediately releases the control after the click, it's not waiting until next page arrives and everything settles down like selenium click does. So the next statement `b.element(id: 'policyNumber').send_keys '23232323'` will start to wait for element to exist even when page started to load, but `this waiting for an element to exist` start to happen after page loaded completely.  Runnable example is not necessary, I am stating something simple about what happens with the click function of selenium and Javascript.

**Comment by titusfortner** [comment]
You can either specify an additional wait time for the element:
```ruby
b.element(id: 'policyNumber').wait_until(timeout: 200, &:present?).send_keys '23232323'
```
or you can add your custom wait for page_load method:
```
def click_away!(element)
  element.click!
  element.wait_until(&:stale?)
end
```
Adding extra behaviors will be easier in Watir 7 when we get the Executor code working.

**Comment by Rajagopalan-M** [comment]
@titusfortner  I am not understanding how this could be a solution? 

when I press the button, If page got refreshed then your solution would work, but how about when I press a button, and it navigates to the next page? How does waiting for stale element would work in this place? Button clicking always leads to the next page. 

did you read the solution of mine? Watir already has wait function and you can call that function after element.click!.

`wait(default_timeout) #I would be calling b.wait(10) `

**Comment by titusfortner** [comment]
Stale just means the element object the driver previously located is no longer in the DOM. You could also `#wait_while_present` if that makes more sense.

Because not every click changes the DOM and there will be race conditions.

**Comment by Rajagopalan-M** [comment]
@titusfortner  That's not the definition of stale element, stale element is when we miss the reference. And also your given idea of using element.wait_until(&:stale?) and #wait_while_present are not working properly, even after the next page has been loaded completely, it still waits for a long time and after long time, it releases the control.

**Comment by Rajagopalan-M** [comment]
@titusfortner oH, I am sorry, I missed out something here, I have mixed selenium code with WATIR, So selenium timer actually waiting for, you are right here. Thanks.
