### ISSUE TITLE
SendKeys not working for ENTER key in Geckodriver

### ISSUE THREAD

**Issue by javigomez** [watir/watir#659]
## Meta
Watir Version: 6.8.4
Selenium Version: 3.6.0
Browser Version: 55.0.3 
Browser Driver Version: 0.19.0
OS Version: MacOS 10.12.5

## Expected Behavior
`browser.text_input_element.send_keys :enter` OR `browser.text_input_element.send_keys :return`
Sends proper ENTER key to the browser.

## Actual Behavior
Sends weird character instead of Hitting ENTER key:
![screen_shot_2017-09-28_at_14_14_15](https://user-images.githubusercontent.com/1375475/30966195-648286b6-a458-11e7-894e-742e0e7085b0.png)

## Steps to reproduce
```
    @browser.goto('http://google.com')
    @browser.input(:id, /lst-ib/).send_keys ['h', 'e', 'l', 'l', 'o']
    @browser.input(:id, /lst-ib/).send_keys :enter
```

**Comment by titusfortner** [comment]
Please [file a Geckodriver bug](https://bugzilla.mozilla.org). Providing the output from running with `Selenium::WebDriver.logger.level = :info` might also provide mozilla with useful information about what the driver is seeing.

Thanks.
