### ISSUE TITLE
element.flash hold the background color red in Firefox instead of blinking

### ISSUE THREAD

**Issue by sjieg** [watir/watir#660]
## Meta -
Watir Version: 6.8.4
Selenium Version: 3.6.0
Browser Version: Firefox 55.0.1 (64bit)
Browser Driver Version: geckodriver 0.18.0
OS Version: Windows 7

## Expected Behavior -

The element background to flash multiple times from red to original color

## Actual Behavior -

The element background color stays red

## Steps to reproduce -

Open `irb`
```
require 'watir'
b = Watir::Browser.new :firefox
b.goto 'google.com'
elm = b.div(:id => 'lga')
elm.flash
```

## Note

The behaviour is different for some elements, for example when flashing the input element, it only blinks red once.

```
require 'watir'
b = Watir::Browser.new :firefox
b.goto 'google.com'
elm = b.input(:name=> 'q')
elm.flash
```

When using chrome, the element works just fine:
```
require 'watir'
b = Watir::Browser.new :chrome
b.goto 'google.com'
elm = b.div(:id => 'lga')
elm.flash
```

**Comment by titusfortner** [comment]
Fixed: https://github.com/watir/watir/commit/80d29457f20d0e610afdaa939bd3f35d37ffe503
It'll be part of the next release
