### ISSUE TITLE
Undefined method browser_name when remote desired capabilities is a symbol

### ISSUE THREAD

**Issue by jkotests** [watir/watir#661]
## Meta -
Watir Version: 6.8.4
Selenium Version: 3.6.0
Browser Version: Chrome 61.0.3163.100
Browser Driver Version: 2.32.498550
OS Version: Windows 10

## Expected Behavior -

Browser starts when calling:

~~~~~~~~ruby
Watir::Browser.new(:remote, desired_capabilities: :chrome)
~~~~~~~~

It should be equivalent to:

~~~~~~~~ruby
Selenium::WebDriver.for(:remote, desired_capabilities: :chrome)
~~~~~~~~

## Actual Behavior -

An exception occurs:

~~~~~~~~ruby
NoMethodError: undefined method `browser_name' for :chrome:Symbol
        from c:/Ruby23/lib/ruby/gems/2.3.0/gems/watir-6.8.4/lib/watir/capabilities.rb:12:in `initialize'
        from c:/Ruby23/lib/ruby/gems/2.3.0/gems/watir-6.8.4/lib/watir/browser.rb:47:in `new'
        from c:/Ruby23/lib/ruby/gems/2.3.0/gems/watir-6.8.4/lib/watir/browser.rb:47:in `initialize'
        from (irb):4:in `new'
        from (irb):4
        from c:/Ruby23/bin/irb.cmd:19:in `<main>'
~~~~~~~~

## Steps to reproduce -

1. Run `Watir::Browser.new(:remote, desired_capabilities: :chrome)`

**Comment by eshah17** [comment]
this work around fixed issue for me : `Watir::Browser.new(:remote, browser: :chrome)`. You can now pass values directly into Watir::Browser opt without needing to use :desired_capabilities

**Comment by evnraja32** [comment]
Watir Version: 6.10.0
Selenium-Webdriver Version: 3.8.0
Browser Version: IE 11.0.9600.18977
Browser Driver Version: 3.8.0 (64-bit)
OS Version: Windows 7

Hi,

This is raja, I'm pretty new to ruby and Watir. But I had experience in Selenium using Java.
When I was trying to launch IE browser using Watir am getting error saying to disable the protected mode settings. But I have already disabled all my Protected Mode settings in Internet Options. But still I'm getting the error.

I believe Something un-expected was happening in the following method
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/ie/driver.rb:61:in `create_capabilities'

Please look into the following different approaches that I have made during my scripting, the IE browser was launched successfully during Approach3 and Approach4.

Please help me in resolving the issue.

Approach 1: Disabled Protected Mode Settings - Adding Desired Capabilities
require 'watir'

capsArray = {
   :introduce_flakiness_by_ignoring_security_domains => true, 
   :ignore_protected_mode_settings=>true
}

caps = Selenium::WebDriver::Remote::Capabilities.ie(capsArray)
browser = Watir::Browser.new :ie, :desired_capabilities => caps

browser.goto 'https://www.google.com'

Output:
2018-05-09 11:18:31 WARN Watir You can now pass values directly into Watir::Browser opt without needing to use :desired_capabilities
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/remote/response.rb:69:in `assert_ok': Unexpected error launching Internet Explorer. Protected Mode settings are not the same for all zones. Enable Protected Mode must be set to the same value (enabled or disabled) for all zones. (Selenium::WebDriver::Error::SessionNotCreatedError)
	from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/remote/response.rb:32:in `initialize'
	from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/remote/http/common.rb:81:in `new'
	from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/remote/http/common.rb:81:in `create_response'
	from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/remote/http/default.rb:104:in `request'
	from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
	from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/remote/bridge.rb:164:in `execute'
	from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/remote/bridge.rb:97:in `create_session'
	from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/remote/bridge.rb:53:in `handshake'
	from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/ie/driver.rb:45:in `initialize'
	from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/common/driver.rb:46:in `new'
	from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/common/driver.rb:46:in `for'
	from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver.rb:84:in `for'
	from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/watir-6.10.0/lib/watir/browser.rb:48:in `initialize'
	from C:/Users/21946417/Documents/NetBeansProjects/HMSS_Selenium/test/Validation/selenium_test.rb:9:in `new'
	from C:/Users/21946417/Documents/NetBeansProjects/HMSS_Selenium/test/Validation/selenium_test.rb:9:in `<main>'


Approach2: : Disabled Protected Mode Settings – Without Desired Capabilities

require 'watir'

browser = Watir::Browser.new :ie

browser.goto 'https://www.google.com'

Output:

C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/remote/response.rb:69:in `assert_ok': Unexpected error launching Internet Explorer. Protected Mode settings are not the same for all zones. Enable Protected Mode must be set to the same value (enabled or disabled) for all zones. (Selenium::WebDriver::Error::SessionNotCreatedError)
	from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/remote/response.rb:32:in `initialize'
	from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/remote/http/common.rb:81:in `new'
	from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/remote/http/common.rb:81:in `create_response'
	from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/remote/http/default.rb:104:in `request'
	from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
	from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/remote/bridge.rb:164:in `execute'
	from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/remote/bridge.rb:97:in `create_session'
	from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/remote/bridge.rb:53:in `handshake'
	from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/ie/driver.rb:45:in `initialize'
	from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/common/driver.rb:46:in `new'
	from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/common/driver.rb:46:in `for'
	from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver.rb:84:in `for'
	from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/watir-6.10.0/lib/watir/browser.rb:48:in `initialize'
	from C:/Users/21946417/Documents/NetBeansProjects/HMSS_Selenium/test/Validation/selenium_test.rb:3:in `new'
	from C:/Users/21946417/Documents/NetBeansProjects/HMSS_Selenium/test/Validation/selenium_test.rb:3:in `<main>'

Approach3:: Directly calling the Selenium to take care of IE Actions importing with watir
require 'watir' #-- importing watir

options = Selenium::WebDriver::IE::Options.new
options.ignore_protected_mode_settings = true
browser = Selenium::WebDriver.for(:ie, options: options)

browser.get 'https://www.google.com'


Output:
Successful launch of browser


I believe Something un-expected was happening in the following method
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/ie/driver.rb:61:in `create_capabilities'
Approch4::Over-ridding Selenium::WebDriver::IE::Driver.create_capabilities method 

require 'watir'

module Selenium
   module WebDriver
      module IE
         class Driver < WebDriver::Driver
            include DriverExtensions::TakesScreenshot

            private
            def create_capabilities(opts)
               caps = opts.delete(:desired_capabilities) { Remote::Capabilities.internet_explorer }
               options = opts.delete(:options) { Options.new }
          
               options.ignore_protected_mode_settings = true
          
               native_events = opts.delete(:native_events)
               unless native_events.nil?
                  WebDriver.logger.deprecate ':native_events', 'Selenium::WebDriver::IE::Options#native_events='
                  options.native_events = native_events
               end

               # Backward compatibility with older IEDriverServer versions
               caps[:ignore_protected_mode_settings] = options.ignore_protected_mode_settings
               caps[:native_events] = options.native_events

               options = options.as_json
               caps.merge!(options) unless options.empty?

               caps
            end

         end # Driver
      end # IE
   end # WebDriver
end # Selenium


capsArray = {
   :introduce_flakiness_by_ignoring_security_domains => true, 
   :ignore_protected_mode_settings=>true
}

caps = Selenium::WebDriver::Remote::Capabilities.ie(capsArray)
browser = Watir::Browser.new :ie, :desired_capabilities => caps

browser.goto 'https://www.google.com'

Output:
Browser launched successfully
