### ISSUE TITLE
Allow all form field types to be called using 1 element type: browser.form_field

### ISSUE THREAD

**Issue by sjieg** [watir/watir#664]
As requested by Titus, putting a ticket in for a possible new feature.

In the category "thinking out loud": I've been working the last few weeks on quite some form validation scripts, creating my own custom form_field_to_value functions and it made me wonder. Could we make (or is there already) a selector that groups `input`, `select` & `textfield` into 1 selector: `form_field`. In practise making it look something as following.

## Expected Behavior -

```Ruby
browser.form_field(:name => 'country').set('netherlands') # Selects the option from a <select> field with the value 'netherlands'

browser.form_field(:id => 'acceptTerms').set(true) # Checks the <input type="checkbox">

browser.form_field(:class => 'descriptionField').set('My life story...') # writes the string in the <textarea> field

```

This would make it much easier to convert configuration values to actual form input values, without having to worry about which element type you're trying to set.

**Comment by titusfortner** [comment]
This might dovetail with #405. What if we define set method on input class, lookup the type and take the action on an object of that subtype.

**Comment by jkotests** [comment]
@titusfortner, are you suggesting that someone would use `browser.input.set`? That'd mean that select lists and textarea are excluded.

**Comment by titusfortner** [comment]
Oh right... I guess `#to_subtype` handles all of it, though... FormField class with set method that returns correct element object? Then alias `#set` for each of those Element objects? Page object gems won't need the extra logic.

**Comment by sjieg** [comment]
I was thinking in the line of: 
```Ruby
def form_field(args*)
  case args
    when b.input(args).exists?
       return b.input(args)
    when b.select(args).exists?
       return b.select(args)
    when b.text_area(args).exists?
       return b.text_area(args)
     else
       raise Watir::ElementNotFoundError
  end
end
```
Or maybe, to reduce redundancy, make an array with form_field_types `['input', 'select', 'text_area']` and loop trough them checking for it existing.

**Comment by titusfortner** [comment]
The intention is to make it so you don't have to specify the element type or figure out the appropriate input method?

What if instead of adding another method, we just duck type it? Everything that responds to `#set` works. So you don't need `#form_field` and can just use `#element`.

```ruby
def set(*args)
  return to_subtype.set(*args) if self.instance_of?(Watir::Element)
  raise "#{self.class} does not support the #set method"
end
```

This would have the advantage of making Page Object implementations easier. This could also make it easier to implement select list type behavior for weird divs that some devs like to do by simply adding a `#set` method to it that class.

**Comment by titusfortner** [comment]
Hmm, though this wouldn't work for the `RadioSet` class we made since `#to_subtype` will return a `Radio` which already has `#set` defined...

**Comment by sjieg** [comment]
To solve the `radio` subtype, how about something like this:
```Ruby
# element(selectors).set(value)
if element.type == 'radio' and value.is_a? String
  browser.input(selectors, :value => value).set
end
```
Maybe this could actually be implemented in the `RadioSet` class. Keep the current behaviour if no value is given, else look for the same selectors with a `:value` added to it.

**Comment by titusfortner** [comment]
This was implemented and will be available in 7.0.0.beta2

**Comment by sjieg** [comment]
Cool stuff, thanks @titusfortner !

**Comment by titusfortner** [comment]
Only took, what, 3 1/2 years? :)
