### ISSUE TITLE
Driver doesn't return control to the code when a browser is loading a page

### ISSUE THREAD

**Issue by qaisbadsha** [watir/watir#665]
## Meta -
Watir Version: 6.8
Selenium Version: 3.6.0
Browser Version: Chrome Version 60.0.3112.113 
Browser Driver Version: ChromeDriver 2.31.488774
OS Version: OSX

## ISSUE -
https://stackoverflow.com/questions/46566606/watir-not-waiting-for-elements-to-load

**Comment by titusfortner** [comment]
This is essentially the same issue as #532. I'm going to close this one and re-open that one for history reasons.;
