### ISSUE TITLE
Not waiting until element is visible

### ISSUE THREAD

**Issue by Rajagopalan-M** [watir/watir#675]
I am writing the following code

the below code tries to interact with the hidden element, and it is expected to wait until element is visible for 30 seconds, but it's throwing error after few seconds
```

require 'watir'

caps = Selenium::WebDriver::Remote::Capabilities.firefox(marionette: false)
driver=Selenium::WebDriver.for :firefox, desired_capabilities: caps, profile: "default"

b=Watir::Browser.new driver

b.goto 'https://www.fitbit.com/login?disableThirdPartyLogin=true&redirect=%2Foauth2%2Fauthorize%3Fclient_id%26response_type%26scope%26state'

b.text_field(name: 'email').set 'abc'
```

Error message

```
C:/Ruby23/lib/ruby/gems/2.3.0/gems/watir-6.8.4/lib/watir/elements/element.rb:634:in `raise_present': element located, but timed out after 30 seconds, waiting for #<Watir::TextField: located: true; {:name=>"email", :tag_name=>"input"}> to be present (Watir::Exception::UnknownObjectException)
	from C:/Ruby23/lib/ruby/gems/2.3.0/gems/watir-6.8.4/lib/watir/elements/element.rb:674:in `rescue in element_call'
	from C:/Ruby23/lib/ruby/gems/2.3.0/gems/watir-6.8.4/lib/watir/elements/element.rb:685:in `element_call'
	from C:/Ruby23/lib/ruby/gems/2.3.0/gems/watir-6.8.4/lib/watir/user_editable.rb:11:in `set'
	from C:/Users/rajagopalan.m/RubymineProjects/Rajagopalan/Example.rb:10:in `<top (required)>'
	from -e:1:in `load'
	from -e:1:in `<main>'

```

**Comment by jkotests** [comment]
@Rajagopalan-M, are you saying that Watir is not waiting the full 30 seconds? Is it specific to the older Firefox as I cannot reproduce it in Chrome or the current Firefox? For me, Watir does wait 30 seconds before timing out.

**Comment by Rajagopalan-M** [comment]
@jkotests  No, Same problem persist in Chrome driver as well. By the way how does driver matters here, WATIR is not maintaining the timings from driver level as Selenium does, WATIR is maintaining the timings from local language binding, So it would happen no matter whatever browser we use. 

@titusfortner ?

**Comment by titusfortner** [comment]
Note that:
`b.text_fields(name: 'email').size #=> 3`

This works just fine:
`b.text_field(name: 'email', visible: 'true').set 'abc'`

**Comment by Rajagopalan-M** [comment]
@titusfortner 

Hi, I know that there are three matches found, and I have known that I can set visible to true to locate this, but the problem is not that. I am reporting this issue because it's not waiting for visibility.  It says that it has waited for 30 seconds, but it's not waiting it's throwing error immediately.

**Comment by titusfortner** [comment]
I can't replicate that behavior. Update your code with what replicates the behavior and I will look again.

**Comment by Rajagopalan-M** [comment]
@titusfortner  Can you please tell me which browser are you using? If you are using firefox, then which driver are you using? Legacy or Geckodriver?

**Comment by Rajagopalan-M** [comment]
@titusfortner 

I have found the solution to this problem, 

The exist_check for text_field is, **wait_for_writable** but in the rescue block, that's not found, that's why this problem happens, 
```
So if you add the wait_for_writable in the below rescue section, problem is solved, 
Like sited below

   rescue Selenium::WebDriver::Error::ElementNotVisibleError,   rescue Selenium::WebDriver::Error::ElementNotVisibleError, Selenium::WebDriver::Error::ElementNotInteractableError
        raise_present unless Wait.timer.remaining_time > 0
        raise_present unless exist_check == :wait_for_present || exist_check == :wait_for_enabled **|| exist_check == :wait_for_writable**
        retry

```

**Comment by titusfortner** [comment]
@Rajagopalan-M would you like to write a test for it and make a PR?

**Comment by Rajagopalan-M** [comment]
@titusfortner 

Can you please add this single line

        raise_present unless exist_check == :wait_for_present || exist_check == :wait_for_enabled **|| exist_check == :wait_for_writable**

All you need to add here is `exist_check == :wait_for_writable`

**Comment by titusfortner** [comment]
@Rajagopalan-M Can you write a spec and make a Pull Request with this?

**Comment by titusfortner** [comment]
Interesting. Chrome was throwing a `ElementNotInteractableError`, so it needed to be tested on Firefox to find the issue. Merged the update into master (with specs).

**Comment by Rajagopalan-M** [comment]
@titusfortner  Chrome would throw ElementNotVisibleError, Firefox will throw ElementNotIntractableError. And May I know why you have closed this issue? Did you add that one line ?

**Comment by titusfortner** [comment]
No, it was the opposite, which is why I couldn't duplicate this issue with Chrome, but could with Firefox.
I closed it because I've:
> Merged the update into master

**Comment by Rajagopalan-M** [comment]
What is opposite? FIREFOX throws ElementNotIntractableError, are you saying no?
