### ISSUE TITLE
browser.driver.manage.logs.get :browser should return complete log with message and arguments

### ISSUE THREAD

**Issue by ghost** [watir/watir#676]
## Meta 
Watir Version: 6.8.0
Selenium Version: 3.6.0
Browser Version: 61.0
Browser Driver Version: 2.33
OS Version: Win 10

## Expected Behavior 
Calling browser.driver.manage.logs.get :browser should return all log entries. Log Entry should be complete. It should contain message and it should also contain arguments if provided. 

## Actual Behavior 
Log Entry contains only message. 

Check my attachments. I have test running from my IDE. In browser console(green square) we can see log is complete. In IDE(debug) we can see log entry is not complete.

**Comment by ghost** [comment]
![expected](https://user-images.githubusercontent.com/9201626/32096080-9725bf66-bb05-11e7-8ca1-c11d2b04e389.PNG)
![actual](https://user-images.githubusercontent.com/9201626/32096081-9743657a-bb05-11e7-9e73-506958222b03.PNG)

**Comment by titusfortner** [comment]
This would be an issue for chromedriver. Watir is returning what Selenium provides, which is coming directly from chromedriver.

**Comment by yair-jarvis** [comment]
Do you have any update on this issue?

**Comment by titusfortner** [comment]
@yair-jarvis this isn't an issue with watir, there is nothing to update.
