### ISSUE TITLE
Some attributes are considered 'invalid'

### ISSUE THREAD

**Issue by enkessler** [watir/watir#681]
Although it is nice to finally be able to locate an element based on whether or not it has an attribute, Watir seems to have a limited view of what is an attribute. If I can inspect an element and see an attribute on it in the DOM, then I expect to be able to use that attribute, as is, to locate that element. Hyphenated attributes, in particular, seem to be a problem for Watir.

## Meta -
Watir Version: 6.7.3
Selenium Version: 3.7.0
Browser Version: Chrome 62
Browser Driver Version: chromedriver 2.33
OS Version: OSX

## Expected Behavior -

I can locate elements based on arbitrary element attributes.

e.g.

`page.div_elements('sidebar-close' => true)`

would successfully locate the element

`<div id="foo" class="stuff" sidebar-close="main"">`

## Actual Behavior -

`Watir::Exception::MissingWayOfFindingObjectException: invalid attribute: "sidebar-close"`

**Comment by titusfortner** [comment]
Watir only supports valid html attributes based on the specification. You can add custom attributes by prepending `data-` and referencing it with `data_custom_attribute: 'foo'`

**Comment by enkessler** [comment]
Could you elaborate on that?

None of these work to locate that element.

`page.div_elements('data-sidebar-close' => true)  # Returns invalid attribute error`
`page.div_elements('data_sidebar-close' => true)  # Returns no elements`
`page.div_elements(data_sidebar_close:  true)       # Returns no elements`

**Comment by titusfortner** [comment]
Can you show the html?

**Comment by titusfortner** [comment]
Also, it would be useful to not include page object gem and use watir code directly.

**Comment by jkotests** [comment]
Adding "data-" would mean needing to modify the HTML to:

~~~~~~~~html
<div id="foo" class="stuff" data-sidebar-close="main"">
~~~~~~~~

If you don't have the option to modify the HTML, you can also [add to the list of valid attributes](https://jkotests.wordpress.com/2014/12/15/adding-custom-attributes-to-the-list-of-valid-locators/). Note that you will need to use underscores instead of dashes.

~~~~~~~~ruby
# adding to the attribute list
Watir::HTMLElement.attributes << :sidebar_close

# will allow you to do
browser.div(sidebar_close: 'main').exists?
~~~~~~~~

**Comment by enkessler** [comment]
I'm trying to locate the following div (slightly sanitized approximation).

`<div class="stuff" sidebar-close="main">`

`@browser.div('data-sidebar-close' => true).exists?` invalid attribute error
`@browser.div('data_sidebar_close' => true).exists?` false
`@browser.div('data_sidebar-close' => true).exists?` false
`@browser.div(data_sidebar_close: true).exists?`. false
`@browser.div(data_sidebar-close: true).exists?` syntax error (can't hyphenate symbols, I assume)

**Comment by enkessler** [comment]
@jkotests Yes, modifying the HTML is not an option.

Your [article](https://jkotests.wordpress.com/2015/06/15/find-elements-based-on-the-presence-or-absence-of-an-attribute/) is my Plan B and how I found out that Water could even do this nowadays which is why I was hoping to just use it normally as Plan A.

**Comment by enkessler** [comment]
I still get an invalid attribute error, even after adding `:sidebar_close` to the list of valid attributes.


`Watir::HTMLElement.attributes << :sidebar_close`
`Watir::HTMLElement.attributes
=> [:title, :lang, :dir, :dataset, :accesskey, :accessKey, :dropzone, :contextmenu, :contextMenu, :onabort, :onblur, :oncancel, :oncanplay, :oncanplaythrough, :onchange, :onclick, :onclose, :oncontextmenu, :oncuechange, :ondblclick, :ondrag, :ondragend, :ondragenter, :ondragexit, :ondragleave, :ondragover, :ondragstart, :ondrop, :ondurationchange, :onemptied, :onended, :onerror, :onfocus, :oninput, :oninvalid, :onkeydown, :onkeypress, :onkeyup, :onload, :onloadeddata, :onloadedmetadata, :onloadstart, :onmousedown, :onmouseenter, :onmouseleave, :onmousemove, :onmouseout, :onmouseover, :onmouseup, :onwheel, :onpause, :onplay, :onplaying, :onprogress, :onratechange, :onreset, :onresize, :onscroll, :onseeked, :onseeking, :onselect, :onshow, :onstalled, :onsubmit, :onsuspend, :ontimeupdate, :ontoggle, :onvolumechange, :onwaiting, :oncopy, :oncut, :onpaste, :content_editable, :contentEditable, :translate?, :translate, :hidden?, :hidden, :draggable?, :draggable, :spellcheck?, :spellcheck, :content_editable?, :isContentEditable, :tabindex, :tabIndex, :id, :class_name, :className, :sidebar_close]`

`@browser.div(sidebar_close: true).exists?` invalid attribute error

**Comment by titusfortner** [comment]
Try adding it camel case

**Comment by enkessler** [comment]
@titusfortner Just tried it. No difference.

**Comment by titusfortner** [comment]
I'll dig into the code to see what is needed

**Comment by titusfortner** [comment]
But I have other things on my list to knock out as well, so not certain time frame.

**Comment by enkessler** [comment]
Okay. I'll try a workaround, in the mean time.

On related note, it's reasonable enough to only directly support 'official' attributes from the HTML specification and I can understand not being able to use `{some-attribute: true}` because it's not valid Ruby (due to the hyphen). However, because even custom attributes are clearly accessible to the element as evidenced here

`<div id="foo" class="lots of classes" sidebar-close="main" ng-click="clear()">`

```
@browser.div(id: 'foo').attribute('sidebar-close')
=> "main"
```

I would think that custom attribute locators along the lines of `@browser.div('sidebar-close' => true)` would be technically possible.

**Comment by jkotests** [comment]
@enkessler, adding the attribute to the attribute list worked for me. When you tried, did you just have Watir loaded or other gems as well? I just did the following in IRB:

~~~~~~~~ruby
require 'watir'
b = Watir::Browser.new
Watir::HTMLElement.attributes << :sidebar_close
b.div(sidebar_close: true).exists?
#=> false
~~~~~~~~

**Comment by enkessler** [comment]
@jkotests I had considered that, so I started a new IRB session and it didn't work. Starting yet another session and typing exactly your code did work this time, though. Odd.

That solution is now working in my project. A more general solution that doesn't require keeping a running list of custom attributes (which may have to be added to every time the site developer decides to try the coolest new JS framework) is still desirable, however.

Thanks for all the help!

**Comment by titusfortner** [comment]
fixed
