### ISSUE TITLE
Issue with new Capabilities setup

### ISSUE THREAD

**Issue by Githraine** [watir/watir#682]
## Meta -
Watir Version: watir (6.8.0)
Selenium Version: (3.4.1)

## Actual Behavior -
When running with this line:
@browser = Watir::Browser.new :remote, caps
I am getting this error:
NoMethodError: undefined method `key?' for #<Selenium::WebDriver::Remote::Capabilities:0x007f819cb07fa0>

## Steps to reproduce -
My caps stack looks like this:
browser_name => 
version => 
platform => {Symbol} any
javascript_enabled => false
css_selectors_enabled => false
takes_screenshot => false
native_events => false
rotatable => false
firefox_profile => nil
proxy => nil
'browser' => ie
'browser_version' => 11
'nativeEvents' => true
'os' => Windows
'build' => _Jenkins_Build#_ie
'resolution' => 1920x1080
'project' => nil
'name' => Test the College Calculator on Massmutual.com - Widget Basic College Calculator check, Examples (#1)
'browserstack.debug' => true
'browserstack.local' => true

**Comment by titusfortner** [comment]
Update to Selenium 3.142.7 & Watir 6.19 and this should all work now.
