### ISSUE TITLE
The selecting List values in a dropdown does not work

### ISSUE THREAD

**Issue by VeeanB** [watir/watir#683]
## Meta -

Watir Version: 6.8.4
Selenium Version: 3.6
Browser Version: Firefox 47
OS Version: Fedora 22
This is my code 
browser.select_list(:name => 'transport_plan[transport_route_id]').select 'Chennai to Mysore'

**Comment by titusfortner** [comment]
There is not enough information here to address this as a bug.

**Comment by VeeanB** [comment]
Following code is not working for me

browser.select_list(:name =>
'transport_plan[transport_route_id]').select 'Chennai to Mysore'
Please help me to resolve this issue

Regards
Veena B
9880444819
