### ISSUE TITLE
The selecting List values in a dropdown does not work

### ISSUE THREAD

**Issue by VeeanB** [watir/watir#691]
## Meta -
Watir Version: 6.8.4
Selenium Version: 3.6
Browser Version:  Firefox 47
OS Version: Fedora 22

This is my code
browser.select_list(:name => 'transport_plan[transport_route_id]').select 'Chennai to Mysore'

**Comment by Rajagopalan-M** [comment]
Give me the site to try it out.

**Comment by VeeanB** [comment]
I tried with this site
http://www.timesjobs.com/candidate/register.html?siteparams=3p9901&utm_source=google&utm_medium=cpc&utm_campaign=search
'

Regards
Veena B
9880444819

**Comment by Rajagopalan-M** [comment]
I think you are giving the wrong site to me, I don't find the select_list with the name 'transport_plan[transport_route_id]' and with the option 'Chennai to Mysore'

Please give me the right site.

**Comment by VeeanB** [comment]
Its our application its under development can u use this

http://www.timesjobs.com/candidate/register.html?siteparams=3p9901&utm_source=google&utm_medium=cpc&utm_campaign=search

This is my code
require 'watir'
@b = Watir::Browser.new :firefox
@b.goto '
http://www.timesjobs.com/candidate/register.html?siteparams=3p9901&utm_source=google&utm_medium=cpc&utm_campaign=search
'
@b.text_field(:id => 'emailAdd').set 'veena.b@fueblab.com'
@b.text_field(:id => 'passwordField').set 'veena123'
@b.select_list(:id => 'curLocation').select 'Chennai'
@b.close


Regards
Veena B
9880444819

**Comment by Rajagopalan-M** [comment]
Okay, here is the solution, But before I post the solution, I want to inform you, this site is not for raising doubts, If you have doubts, please raise it in stackoverflow here

https://stackoverflow.com/questions/tagged/watir

If you find any bug in WATIR, then you need to post it here. 

**solution to your problem:**

actually your select_list has another layer between select and option, that's optgroup, so normal select_list code doesn't work, so write the below code, it would work

`b.select(id: 'curLocation').optgroup(label: '   Metros').option(text: 'Chennai').select`

Remember If you want to choose something outside of Metros, you need to write that as well, the above code would work for all the option which are below Metros.

**Comment by Rajagopalan-M** [comment]
Hi Veena,

I hope the given solution is working for you. 

If your options are unique, then you can directly write this code as well

`b.select_list(id: 'curLocation').option(text: 'Chennai').select`

`b.select_list(id: 'curLocation').select('Chennai')`

But remember, If Chennai is coming under some other sub option, then it always chooses the first one, not the second one.

**Comment by VeeanB** [comment]
Still its not working for me ,
 I wrote same code

Regards
Veena B
9880444819

**Comment by Rajagopalan-M** [comment]
Hi Veena, 

Is it possible to give team viewer connection to your system, let me have a look at them? Because it's working for me without any problem.

**Comment by VeeanB** [comment]
For that  region i am using this code
b.select_list(:id , "sub_part_vehicle_part_id").wait_until_present.click
b.select_list(:id , "sub_part_vehicle_part_id").send_keys :arrow_down
b.select_list(:id , "sub_part_vehicle_part_id").send_keys :arrow_down
b.select_list(:id , "sub_part_vehicle_part_id").click

Regards
Veena B
9880444819
