### ISSUE TITLE
Invalid attribute :name when searching for table

### ISSUE THREAD

**Issue by westlakem** [watir/watir#693]
## Meta -
Watir Version: 6.10.0
Selenium Version: 
Browser Version: 
Browser Driver Version: 
OS Version: 

## Expected Behavior -

Expected to find a table by name

## Actual Behavior -

Watir::Exception::MissingWayOfFindingObjectException: invalid attribute: :name

## Steps to reproduce -
Try to find an HTML Table by name attribute

**Comment by jkotests** [comment]
Are you sure you're actually using v6.10?

We removed the declaration for `Watir::Exception::MissingWayOfFindingObjectException`, so it seems weird that you could get an exception of that type.

**Comment by westlakem** [comment]
I'm sorry, a team memeber was still on 6.9.1.   It seems to have been fixed in 6.10  Appologies

**Comment by titusfortner** [comment]
We anticipated your issue request and provided it a week ahead of time. :)

**Comment by Rajagopalan-M** [comment]
Good one ☺️
