### ISSUE TITLE
Ignoring certificate errors in Chrome headless

### ISSUE THREAD

**Issue by ninp0** [watir/watir#694]
What steps are required to instantiate a headless Chrome browser object that won't verify certificates?

The following displays a blank page when navigating to a test website w/ a self-signed cert but otherwise works on pages that have valid certs:

```          
this_profile = Selenium::WebDriver::Chrome::Profile.new
this_profile['download.prompt_for_download'] = false
this_profile['download.default_directory'] = '~/Downloads'

this_browser = Watir::Browser.new(
  :chrome,
  headless: true
)

this_browser.goto('https://192.168.1.1')
this_browser.title
=> ""
```

Versions:
Watir 6.10.0
Chromium 62.0.3202.89
Chromedriver 2.32

I've even tried:

```
              this_browser = Watir::Browser.new(
                :chrome,
                headless: true,
                switches: [
                  '--ignore-certificate-errors'
                ]
              )
```

to no avail.  The interesting part is if I use :chrome w/o the headless option, the page renders properly.  Please advise.

Thanks in advance for your help!

**Comment by titusfortner** [comment]
Headless chrome does not respect any preferences. Google didn't even include that code in headless chromium.

@p0deje & @jkotests do you think we should add a warning to our capabilities class when using both chrome preferences and headless?

**Comment by ninp0** [comment]
So for headless browsing is it advised to simply use firefox at this point if the intent is to test sites w/ self-signed certificates?  It looks like Selenium removed PhantomJS support.

**Comment by titusfortner** [comment]
Most people using headless don't actually need headless. If headless gem with xvfb make sense, I'd recommend that. If Firefox headless does what you need, then go for it.

**Comment by ninp0** [comment]
No thanks - there's also a multi-OS requirement...I tried firefox but that's not working properly either.  I don't know wth Google was thinking about not respecting any preferences while headless but running headless chrome and ignoring certificates is kind of a big deal when leveraging automation to test internal sites.

**Comment by titusfortner** [comment]
Headless is both complicated and impressive. Most test suites these days are run via CI on remote machines that have GUIs, though, so headless doesn't matter.

**Comment by ninp0** [comment]
fwiw: State on supporting an "acceptInsecureCerts" flag:

https://bugs.chromium.org/p/chromium/issues/detail?id=721739

**Comment by ninp0** [comment]
fwiw, got headless & accepting insecure certificates working in Firefox (Assuming you're not using Firefox ESR since it won't support headless until March 2018):

```
          this_profile = Selenium::WebDriver::Firefox::Profile.new
          # Downloads reside in ~/Downloads
          this_profile['browser.download.folderList'] = 1
          this_profile['browser.helperApps.neverAsk.saveToDisk'] = 'application/pdf'

          # disable Firefox's built-in PDF viewer
          this_profile['pdfjs.disabled'] = true

          # disable Adobe Acrobat PDF preview plugin
          this_profile['plugin.scan.plid.all'] = false
          this_profile['plugin.scan.Acrobat'] = '99.0'

          caps = Selenium::WebDriver::Remote::Capabilities.firefox
          caps[:acceptInsecureCerts] = true

          options = Selenium::WebDriver::Firefox::Options.new(args: ['-headless'])
          options.profile = this_profile
          driver = Selenium::WebDriver.for(:firefox, options: options, desired_capabilities: caps)
          this_browser = Watir::Browser.new(driver)
```

Hope it helps others avoid having to run through the rabbit hole I had to traverse ;)

**Comment by MalloZup** [comment]
thx @ninp0  i will use this issue as good starting point for migrate to firefox
