### ISSUE TITLE
Chrome/Chromium headless profile not passed to chromedriver

### ISSUE THREAD

**Issue by gtd** [watir/watir#701]
Watir Version: 6.10.0
Selenium Version: 3.8.0
Browser Version: Chromium 63.0.3239.84
Browser Driver Version: ChromeDriver 2.33
OS Version: Ubuntu 14.04

## Expected Behavior

Passing a `:profile` option to `Watir::Browser` should use specified profile, however it does not.

## Actual Behavior

The profile is written to disk, but it's not actually wired into the Chrome command.  Instead a different temp profile is used.  You can see this by observing two `/tmp/.org.chromium.Chromium.xxxxx` temp directories created, one with the specified preferences, and another with a set of default preferences.  `ps auxf | grep chrom` shows the one passed to the chromium process started by `chromedriver` 

## Steps to reproduce

```
require 'watir'

profile = Selenium::WebDriver::Chrome::Profile.new
profile['download.prompt_for_download'] = false
profile['download.default_directory'] = '/tmp/download_here_sucka'
@browser = Watir::Browser.new :chrome, profile: profile, headless: true
```

## Root Cause

In investigating this, I found that the Selenium Chrome Driver has [code to handle a profile being passed in](https://github.com/SeleniumHQ/selenium/blob/master/rb/lib/selenium/webdriver/chrome/driver.rb#L76-L91), but it does not fire.  This is because the `:profile` option is not preserved at the top level by [Watir::Capabilities#to_args](https://github.com/watir/watir/blob/master/lib/watir/capabilities.rb#L27-L42).  I am not familiar enough with Selenium/Watir to suggest any particular fix, however the following workaround does seem to work:

```
profile = Selenium::WebDriver::Chrome::Profile.new
profile['download.prompt_for_download'] = false
profile['download.default_directory'] = '/tmp/download_here_sucka'
profile.as_json # Forces tmp directory creation as side effect
args = ["--user-data-dir=#{profile.directory}"]
@browser = Watir::Browser.new :chrome, profile: profile, args: args, headless: true
```

**Comment by titusfortner** [comment]
This is a Chromium Issue, not a Watir issue.
Chrome Preferences are not currently supported in Headless Mode. See Comment 7 in [this Chromium Bug](https://bugs.chromium.org/p/chromium/issues/detail?id=775911#c7)
