### ISSUE TITLE
Full page screenshots with Firefox and geckodriver

### ISSUE THREAD

**Issue by samnissen** [watir/watir#702]
I've hastily [implemented a solution](https://github.com/samnissen/watir-screenshot-stitch) for [geckodriver not supporting full page screenshots](https://github.com/mozilla/geckodriver/issues/570).

Would such an approach be acceptable for merging into Watir? If not, what (if any) other solutions exist for working around geckodriver's limitation?

##### Meta
Watir Version: 6.10.2
Selenium Version: 3.8
Firefox Version: 57.0.4
geckodriver Version: 0.19.1
macOS Version: 10.13.1

**Comment by titusfortner** [comment]
This is great. No, this should be released as its own gem for people to include only of they want to, then you can write a blog post about it for Watir.com

Let us know if you need any help doing that, or if you'd prefer the Watir team store the repo on our org, or whatever we can do to support it. Easier to chat about this in the Watir channel of selenium slack, are you on there?
