### ISSUE TITLE
undefined method `selector_builder' for nil:NilClass

### ISSUE THREAD

**Issue by agodwin** [watir/watir#706]
## Meta -
Watir Version: 6.10.3
Selenium Version: selenium-webdriver (3.8.0)
Browser Version: Chrome Version 64.0.3282.119 (Official Build) (64-bit)
Browser Driver Version: chromedriver --version ChromeDriver 2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061)
OS Version: Mac OS Sierra 10.12.6 (16G1114)

and also seeing for: 
Watir Version: watir (6.10.3)
Selenium Version: selenium-webdriver (3.8.0)
Browser Version: Google Chrome Version 64.0.3282.119 (Official Build) (64-bit)
Browser Driver Version:ChromeDriver 2.34.522940 (1a76f96f66e3ca7b8e57d503b4dd3bccfba87af1)
OS Version: Windows 10 Enterprise

## Expected Behavior -
WATIR does not try to call a method for an uninitialized object reference (see watir-6.10.3/lib/watir/elements/element.rb:662)

## Actual Behavior -
      Failure/Error: @b.div(:id => 'home').div(:class => 'pinned-item-list').wait_until_present(timeout: 6)
      
      NoMethodError:
        undefined method `selector_builder' for nil:NilClass
      # /Users/godwina/.rvm/gems/ruby-2.4.1/gems/watir-6.10.3/lib/watir/elements/element.rb:662:in `rescue in element_call'
      # /Users/godwina/.rvm/gems/ruby-2.4.1/gems/watir-6.10.3/lib/watir/elements/element.rb:680:in `element_call'
      # /Users/godwina/.rvm/gems/ruby-2.4.1/gems/watir-6.10.3/lib/watir/elements/element.rb:404:in `visible?'
      # /Users/godwina/.rvm/gems/ruby-2.4.1/gems/watir-6.10.3/lib/watir/elements/element.rb:427:in `present?'
      # /Users/godwina/.rvm/gems/ruby-2.4.1/gems/watir-6.10.3/lib/watir/wait.rb:46:in `block in until'
      # /Users/godwina/.rvm/gems/ruby-2.4.1/gems/watir-6.10.3/lib/watir/wait.rb:89:in `block in run_with_timer'
      # /Users/godwina/.rvm/gems/ruby-2.4.1/gems/watir-6.10.3/lib/watir/wait/timer.rb:20:in `block in wait'
      # /Users/godwina/.rvm/gems/ruby-2.4.1/gems/watir-6.10.3/lib/watir/wait/timer.rb:19:in `loop'
      # /Users/godwina/.rvm/gems/ruby-2.4.1/gems/watir-6.10.3/lib/watir/wait/timer.rb:19:in `wait'
      # /Users/godwina/.rvm/gems/ruby-2.4.1/gems/watir-6.10.3/lib/watir/wait.rb:88:in `run_with_timer'
      # /Users/godwina/.rvm/gems/ruby-2.4.1/gems/watir-6.10.3/lib/watir/wait.rb:45:in `until'
      # /Users/godwina/.rvm/gems/ruby-2.4.1/gems/watir-6.10.3/lib/watir/wait.rb:125:in `wait_until'
      # /Users/godwina/.rvm/gems/ruby-2.4.1/gems/watir-6.10.3/lib/watir/wait.rb:173:in `wait_until_present'
      # ./lib/pages/mobilehoovers/desktop_page.rb:8:in `valid?'
      # ./spec/mobilehoovers/view_static_list_and_pin_from_list_detail_spec.rb:32:in `block (3 levels) in <top (required)>'
      # ------------------
      # --- Caused by: ---
      # Watir::Exception::UnknownObjectException:
      #   unable to locate element: #<Watir::Div: located: false; {:id=>"home", :tag_name=>"div"}>
      #   /Users/godwina/.rvm/gems/ruby-2.4.1/gems/watir-6.10.3/lib/watir/elements/element.rb:583:in `assert_element_found'

## Steps to reproduce -

I do not have repeatable way to reproduce this problem. It happens randomly for the same test. The common element, as near as I can tell, is it happens when we chain HTML elements together and then have a wait_until_present() for the last element.  

We have tried to work around the problem with: 
1) covert to using wait_until method:
     @b.wait_until(timeout: 6) { @b.div(:id => 'home').div(:class => 'pinned-item-list').present? }
2) have a specific WAIT for each element in the chain: 
     @b.div(:id => 'home').wait_until_present(timeout: 4).div(:class => 'pinned-item-list').wait_until_present(timeout: 2)

**Comment by titusfortner** [comment]
Ah, yes, I see the problem. Looks like `@locator` isn't defined for the child when it is failing for the parent, so it can't process the message and fails.

We can either put lines 662 & 663 into a conditional of `unless @locator.nil?`. 
Or change the order of where `@locator` gets defined in element & iframe.

@p0deje or @jkotests do you have any opinions/preferences on this? The former is easier and probably more appropriate, but the latter might be more correct?

Also, unrelated, but your chromedriver is out of date on both of those machines, you need 2.35 for Chrome 64.

**Comment by agodwin** [comment]
Absolutely, moving to the latest chromedriver is a must. The team was just given a week to update from WATIR 0.9.9 to the latest WATIR. We are on day three, WAITR is in 113 page object files.

**Comment by titusfortner** [comment]
Ooh, exciting. Yeah, let us know how the upgrade goes; we'll get this bug fixed this week one way or another.
If you are running locally you can use `webdrivers` gem to keep the drivers up to date, if you are running via a server I can't help you. :)

**Comment by jkotests** [comment]
@titusfortner , I don't have a strong opinion. It would be nice to get the extra message details since it might explain why the element wasn't found? But I'm not convinced it's worth having to make a lot of changes (though honestly I don't know what that change actually entails).

**Comment by p0deje** [comment]
@titusfortner I don't have a preference :)

**Comment by agodwin** [comment]
Here is an update about our work around. We are no longer using the "covert to using wait_until method" as a work around because we still saw the problem (so it was NOT a work around). 

Our current thinking, and coding, is to "trust Watir 6" and start removing the waits altogether. We now have code which does an element.click() and we have removed the element.wait_until_present() (which was needed by our ancient version of WAITR). With the new WAITR version, we see the need for these waits is no longer necessary (unless we want to control the timeout).

**Comment by titusfortner** [comment]
yeah, you really shouldn't need to put them in there, but it should still work with them there. I *should be able to fix this later today. I'm going with the simple fix that is less likely to have other effects. Thanks for the update

**Comment by titusfortner** [comment]
Forgot about this one, finally merged. Whoa, github auto-closes Issues based on messages in commit. That's pretty cool.
