### ISSUE TITLE
Inconsistency when using watir with JRuby and MRI

### ISSUE THREAD

**Issue by boris-petrov** [watir/watir#707]
This is not exactly an issue but a help request.

The [original problem](https://github.com/titusfortner/webdrivers/issues/7) started from the `webdrivers` gem which didn't seem to work correctly with JRuby. We figured out that the problem was in JRuby so I [opened an issue there](https://github.com/jruby/jruby/issues/4939). Now the guys from JRuby need help diagnosing the problem. Perhaps you could help by reproducing the issue on JRuby (just follow the couple of steps in the issue there) and maybe try to pinpoint the culprit.

@headius can perhaps also help if something is needed on JRuby's side.

Thanks to everyone involved!

**Comment by titusfortner** [comment]
This isn't a watir issue, at best it is a webdrivers issue, but we can discuss it in the jruby issue comments; feel free to tag me there. Also @p0deje if you have any ideas on what might be going on since you've done more with jruby than I have, let me know, thanks!
