### ISSUE TITLE
tinymce.activeEditor is undefined after wait_until(&:present?) on iframe elements

### ISSUE THREAD

**Issue by matthewbyrne** [watir/watir#712]
## Meta -
Watir Version: 6.10.3
Selenium Version: 
Browser Version: FF58.b9
Browser Driver Version: Geckodriver 0.19.0
OS Version: Ubuntu 14.04

## Expected Behavior -
TinyMCE should be accessible after waiting on tinyMCE iFrame to render

## Actual Behavior -
Executing tinymce javascript after asserting a wait on the body of the tinymce iframe causes tinymce to return as undefined. I've narrowed this down to which element the `wait_until(&:present)` method acts upon. 
This only occurs if I use a wait_until(&:present?) on a child element of the iframe.

## Steps to reproduce -
Using IRB instantiate a new instance of Firefox.
We can use the tinymce demo page to reproduce this. https://www.tinymce.com/docs/demo/full-featured/ page
I had to get creative here and view a specific iframe, otherwise the tinymce script interaction fails everytime. Right click on the 'result-iframe' iframe and open that iframe in a new tab.
Set this new tab as your active tab in irb `browser.windows.last.use`
Run the following script to populate the tinymce editor:
`browser.execute_script("tinymce.activeEditor.setContent('test');")`
The tinymce editor should set the body to `test`
Run the following wait command (It would typically be used after the page loads to ensure tinymce window has completed loading)
`browser.iframe(:id => 'mce_0_ifr').body.wait_until(&:present?)`
Now rerun the execute_script command from above.
`browser.execute_script("tinymce.activeEditor.setContent('test');")`

Result:
Exception thrown. tinymce.activeEditor is undefined.

```
Selenium::WebDriver::Error::JavascriptError: TypeError: tinymce.activeEditor is undefined
	from execute_script
	from inline javascript, line 164
	from src: "undefined"
	from Stack:
	from @chrome://marionette/content/evaluate.js:164:15
	from @chrome://marionette/content/evaluate.js:164:2
	from /Users/mbyrne/.rvm/gems/ruby-2.3.1/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/remote/response.rb:69:in `assert_ok'
	from /Users/mbyrne/.rvm/gems/ruby-2.3.1/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/remote/response.rb:32:in `initialize'
	from /Users/mbyrne/.rvm/gems/ruby-2.3.1/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/remote/http/common.rb:81:in `new'
	from /Users/mbyrne/.rvm/gems/ruby-2.3.1/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/remote/http/common.rb:81:in `create_response'
	from /Users/mbyrne/.rvm/gems/ruby-2.3.1/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/remote/http/default.rb:104:in `request'
	from /Users/mbyrne/.rvm/gems/ruby-2.3.1/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
	from /Users/mbyrne/.rvm/gems/ruby-2.3.1/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/remote/bridge.rb:164:in `execute'
	from /Users/mbyrne/.rvm/gems/ruby-2.3.1/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/remote/w3c/bridge.rb:535:in `execute'
	from /Users/mbyrne/.rvm/gems/ruby-2.3.1/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/remote/w3c/bridge.rb:292:in `execute_script'
	from /Users/mbyrne/.rvm/gems/ruby-2.3.1/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/common/driver.rb:211:in `execute_script'
	from /Users/mbyrne/.rvm/gems/ruby-2.3.1/gems/watir-6.10.3/lib/watir/browser.rb:265:in `execute_script'
	from (irb):38
	from /Users/mbyrne/.rvm/rubies/ruby-2.3.1/bin/irb:11:in `<main>'
```

**Comment by titusfortner** [comment]
`#execute_script` executes JavaScript in the context of the currently selected frame or window, and when you take an action on `body` you have selected the iframe as the context.

Try putting `browser.exist?` before the last execute_script

That will tell the driver to use the top level browsing context instead of the iframe context.

**Comment by matthewbyrne** [comment]
No joy.

```
@browser.refresh
 => nil
2.3.1 :047 > @browser.iframe(:id => 'mce_0_ifr').body.wait_until(&:present?)
 => #<Watir::Body: located: true; {:id=>"mce_0_ifr", :tag_name=>"iframe"} --> {:tag_name=>"body"}>
2.3.1 :048 > @browser.exists?
 => true
2.3.1 :049 >     @browser.execute_script(tiny_mce_script)
Selenium::WebDriver::Error::JavascriptError: TypeError: tinymce.activeEditor is undefined
	from execute_script
	from inline javascript, line 164
	from src: "undefined"
	from Stack:
	from @chrome://marionette/content/evaluate.js:164:15
	from @chrome://marionette/content/evaluate.js:164:2
	from /Users/mbyrne/.rvm/gems/ruby-2.3.1/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/remote/response.rb:69:in `assert_ok'
	from /Users/mbyrne/.rvm/gems/ruby-2.3.1/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/remote/response.rb:32:in `initialize'
	from /Users/mbyrne/.rvm/gems/ruby-2.3.1/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/remote/http/common.rb:81:in `new'
	from /Users/mbyrne/.rvm/gems/ruby-2.3.1/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/remote/http/common.rb:81:in `create_response'
	from /Users/mbyrne/.rvm/gems/ruby-2.3.1/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/remote/http/default.rb:104:in `request'
	from /Users/mbyrne/.rvm/gems/ruby-2.3.1/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
	from /Users/mbyrne/.rvm/gems/ruby-2.3.1/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/remote/bridge.rb:164:in `execute'
	from /Users/mbyrne/.rvm/gems/ruby-2.3.1/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/remote/w3c/bridge.rb:535:in `execute'
	from /Users/mbyrne/.rvm/gems/ruby-2.3.1/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/remote/w3c/bridge.rb:292:in `execute_script'
	from /Users/mbyrne/.rvm/gems/ruby-2.3.1/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/common/driver.rb:211:in `execute_script'
	from /Users/mbyrne/.rvm/gems/ruby-2.3.1/gems/watir-6.10.3/lib/watir/browser.rb:265:in `execute_script'
	from (irb):49
	from /Users/mbyrne/.rvm/rubies/ruby-2.3.1/bin/irb:11:in `<main>'
```

**Comment by matthewbyrne** [comment]
Calling the browser worked though.

`browser.iframe(:id => 'mce_0_ifr').body.wait_until(&:present?)`
`browser`
`browser.execute_script(tiny_mce_script)`

Bit of an odd sequence though


EDIT: Scratch that. It worked in that instance, but elsewhere it does nothing. Similarly `browser.exists?` does nothing either.

**Comment by titusfortner** [comment]
That... doesn't make sense. `browser` is just a variable, it isn't changing any kind of state when you just reference it.
You can use
`Selenium::WebDriver.logger.level = :info` to see what is getting sent to/from the driver

Though, the important thing is that you have something working

**Comment by matthewbyrne** [comment]
Yeah, unfortunately "something working" didn't translate to our site. `iframe`s are still causing plenty of bother :(

**Comment by titusfortner** [comment]
I'm not sure when I'm going to get a chance to walk through this code in more detail. 

Are the iframes nested? Maybe you just want:
`@browser.iframe(:id => 'mce_0_ifr').exist?`
That would pull the context up one level instead of to the top level.

**Comment by matthewbyrne** [comment]
Might be onto something there.
I'm now asserting presence on child elements of the iframe, then `@browser.iframe(IFRAME_ID_HERE).exist?` to refocus on the correct iframe.
Then execute the tinymce script.
Is it a case whereby I need to "set" which context (browser/iframe etc) i'm operating in before doing anything?

I'll play around with that and report back tomorrow hopefully.

**Comment by titusfortner** [comment]
In Selenium you have to always specify what context you are in. Watir manages that for you based on what element you are working with. Unless you aren't working with elements and are using JavaScript, which isn't Watir's specific use case.

You can `browser.wd.switch_to.frame(frame_element.wd)` or `browser.wd.switch_to.parent_frame`

Or you can fake it out with Watir by calling `#exist?` on the frame.

**Comment by titusfortner** [comment]
If this discussion didn't resolve the issue, let me know and I'll re-open.
