### ISSUE TITLE
Can i create test result in html by watir?

### ISSUE THREAD

**Issue by Jun12121988** [watir/watir#713]

**Comment by titusfortner** [comment]
This is a question and not an issue. Please ask your question in one of our supported channels: http://watir.com/help/

**Comment by Rajagopalan-M** [comment]
There are many people who does this mistake, i have informed them many times

**Comment by titusfortner** [comment]
It's easy enough to close the issue and redirect people. Github doesn't charge us by the issue. :)

**Comment by Jun12121988** [comment]
Sorry people!
