### ISSUE TITLE
Watir error No connection could be made because the target machine actively refused it.

### ISSUE THREAD

**Issue by Jun12121988** [watir/watir#714]
My code is below:
require 'watir'

b = Watir::Browser.new :ie

puts "OK"

And after run, result is below:
C:/Ruby/Ruby25-x64/lib/ruby/2.5.0/net/http.rb:939:in `rescue in block in connect': Failed to open TCP connection to 127.0.0.1:5555 (No connection could be made because the target machine actively refused it. - connect(2) for "127.0.0.1" port 5555) (Errno::ECONNREFUSED)
	from C:/Ruby/Ruby25-x64/lib/ruby/2.5.0/net/http.rb:936:in `block in connect'
	from C:/Ruby/Ruby25-x64/lib/ruby/2.5.0/timeout.rb:76:in `timeout'
	from C:/Ruby/Ruby25-x64/lib/ruby/2.5.0/net/http.rb:935:in `connect'
	from C:/Ruby/Ruby25-x64/lib/ruby/2.5.0/net/http.rb:920:in `do_start'
	from C:/Ruby/Ruby25-x64/lib/ruby/2.5.0/net/http.rb:909:in `start'
	from C:/Ruby/Ruby25-x64/lib/ruby/2.5.0/net/http.rb:1455:in `request'
	from C:/Ruby/Ruby25-x64/lib/ruby/gems/2.5.0/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/remote/http/default.rb:121:in `response_for'
	from C:/Ruby/Ruby25-x64/lib/ruby/gems/2.5.0/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/remote/http/default.rb:76:in `request'
	from C:/Ruby/Ruby25-x64/lib/ruby/gems/2.5.0/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
	from C:/Ruby/Ruby25-x64/lib/ruby/gems/2.5.0/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/remote/bridge.rb:164:in `execute'
	from C:/Ruby/Ruby25-x64/lib/ruby/gems/2.5.0/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/remote/bridge.rb:97:in `create_session'
	from C:/Ruby/Ruby25-x64/lib/ruby/gems/2.5.0/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/remote/bridge.rb:53:in `handshake'
	from C:/Ruby/Ruby25-x64/lib/ruby/gems/2.5.0/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/ie/driver.rb:46:in `initialize'
	from C:/Ruby/Ruby25-x64/lib/ruby/gems/2.5.0/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/common/driver.rb:46:in `new'
	from C:/Ruby/Ruby25-x64/lib/ruby/gems/2.5.0/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/common/driver.rb:46:in `for'
	from C:/Ruby/Ruby25-x64/lib/ruby/gems/2.5.0/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver.rb:85:in `for'
	from C:/Ruby/Ruby25-x64/lib/ruby/gems/2.5.0/gems/watir-6.10.3/lib/watir/browser.rb:48:in `initialize'
	from C:/Users/MD/workspace/TempPractice/Run.rb:3:in `new'
	from C:/Users/MD/workspace/TempPractice/Run.rb:3:in `<main>'

I user Win7 + IE9 64 bit
I also set PATH for IE driver

Please help me to solve this problem!!!!

**Comment by titusfortner** [comment]
What version of IEDriver?
You might try using the `webdrivers` gem in case it is some kind of PATH issue.

**Comment by Jun12121988** [comment]
First, thank for reply!!!
I am using IE driver 64 bit. 

But when I change to IE driver 32 bit, above error is not shown. I do not know the reason why?

**Comment by Somoya87** [comment]
Yes. Using 32 bit driver for 64 bit machine resolves the issue.. Any idea?

**Comment by titusfortner** [comment]
Yeah, it's explained here: http://jimevansmusic.blogspot.co.uk/2014/09/screenshots-sendkeys-and-sixty-four.html
