### ISSUE TITLE
Infinite loop occurs when element goes stale during lookup and using_watir locator branch

### ISSUE THREAD

**Issue by jkotests** [watir/watir#718]
## Meta -
Watir Version: 6.10.3
Selenium Version: 3.11.0
Browser Version: Chrome 66.0.3359.139
Browser Driver Version: ChromeDriver 2.38
OS Version: Windows 10

## Expected Behavior -

`Element#present?` should return false when an element goes stale during lookup - see the [element_spec.rb](https://github.com/watir/watir/blob/17d8cceed21308e038794e64b1e327b7d3c0804c/spec/element_spec.rb#L22-L30)

## Actual Behavior -

Watir returns the expected result when located using `Element::Locator#using_selenium` branch. However, Watir will get stuck in an infinite loop if the `Element::Locator#using_watir` branch is used.

## Steps to reproduce -

Given the HTML file:

~~~~~~~~html
<html>
  <body>
    <div id="foo" data-id="foo">test</div>
  </body>
</html>
~~~~~~~~

Run the following spec (which is a modification of the existing spec - [element_spec.rb](https://github.com/watir/watir/blob/17d8cceed21308e038794e64b1e327b7d3c0804c/spec/element_spec.rb#L22-L30)):

~~~~~~~~ruby
require 'watir'
require 'rspec/autorun'

describe Watir::Element do
  describe '#present?' do
    it "returns false if the element is stale and located by Watir" do
      browser = Watir::Browser.new
      browser.goto File.join(__dir__, 'test.htm')
      
      wd_element = browser.div(data_id: "foo").wd

      # simulate element going stale during lookup
      allow(browser.driver).to receive(:find_element).with(:xpath, ".//div[@data-id='foo']") { wd_element }
      browser.refresh

      expect(browser.div(:data_id, 'foo')).to_not be_present
      browser.close
    end
  end
end
~~~~~~~~

Notice that the spec runs forever.

**Comment by titusfortner** [comment]
@jkotests let me know if this one isn't resolved

**Comment by jkotests** [comment]
@titusfortner , this is resolved now. Thanks.
