### ISSUE TITLE
Integration with Chrome Dev Tools Protocol

### ISSUE THREAD

**Issue by thekiiingbob** [watir/watir#721]
It should be possible to integrate/wrap something like https://github.com/cavalle/chrome_remote/ into various commands on the browser.

The gain here is that you have direct access to the Chrome Dev Tools Protocol and can setup things like network intercepts or listening for particular messages in the console (among other things, more found here - https://chromedevtools.github.io/devtools-protocol/).

For reference, in the Javascript space I've been using webdriver.io and there is a package (https://github.com/webdriverio/wdio-devtools-service) that extends the CDP commands onto the browser.

General Thoughts/Concerns:
This would only work in Chrome.
Can this live in Watir or become a "plugin" Gem?
Should people that want to use this just use chrome_remote directly?

**Comment by abotalov** [comment]
Selenium has `executeCdpCommand` though it doesn't have `on`
https://github.com/SeleniumHQ/selenium/blob/07a18746ff756e90fd79ef253a328bd7dfa9e6dc/py/selenium/webdriver/chrome/webdriver.py#L118

**Comment by titusfortner** [comment]
Selenium 4 is working to implement a cross-browser bidirectional API

One option is for Watir to wrap this once all browsers are supported. Another option is to just let the user access the functionality they need with `browser.driver.register` / `browser.driver.devtools`, etc.

We're going to go with the latter unless/until someone has a reason for a change.
