### ISSUE TITLE
Unable to Launch IE with desired capabilities having :introduce_flakiness_by_ignoring_security_domains => true, :ignore_protected_mode_settings=>true

### ISSUE THREAD

**Issue by evnraja32** [watir/watir#722]
## Meta -
Watir Version: 3.10.0
Selenium Version: 3.8.0
Browser Version: IE 11.0.9600.18977
Browser Driver Version: 3.8.0 (64-bit)
OS Version: Windows 7

Hi,

This is raja, I'm pretty new to ruby and Watir. But I had experience in Selenium using Java.
When I was trying to launch IE browser using Watir am getting error saying to disable the protected mode settings. But I have already disabled all my Protected Mode settings in Internet Options. But still I'm getting the error.

I believe Something un-expected was happening in the following method:
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/ie/driver.rb:61:in 'create_capabilities'

So, When I override the 'create_capabilities' method inside the script, I'm able to launch the browser.
Please see the comment section for the script with over-ride method
## Expected Behavior -
Browser Should launch Successfully

## Actual Behavior -
2018-05-09 11:18:31 WARN Watir You can now pass values directly into Watir::Browser opt without needing to use :desired_capabilities
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/remote/response.rb:69:in `assert_ok': Unexpected error launching Internet Explorer. Protected Mode settings are not the same for all zones. Enable Protected Mode must be set to the same value (enabled or disabled) for all zones. (Selenium::WebDriver::Error::SessionNotCreatedError)
	from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/remote/response.rb:32:in `initialize'
	from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/remote/http/common.rb:81:in `new'
	from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/remote/http/common.rb:81:in `create_response'
	from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/remote/http/default.rb:104:in `request'
	from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
	from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/remote/bridge.rb:164:in `execute'
	from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/remote/bridge.rb:97:in `create_session'
	from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/remote/bridge.rb:53:in `handshake'
	from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/ie/driver.rb:45:in `initialize'
	from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/common/driver.rb:46:in `new'
	from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/common/driver.rb:46:in `for'
	from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver.rb:84:in `for'
	from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/watir-6.10.0/lib/watir/browser.rb:48:in `initialize'
	from C:/Users/21946417/Documents/NetBeansProjects/HMSS_Selenium/test/Validation/selenium_test.rb:9:in `new'
	from C:/Users/21946417/Documents/NetBeansProjects/HMSS_Selenium/test/Validation/selenium_test.rb:9:in `<main>'

## Steps to reproduce -
require 'watir'

capsArray = {
   :introduce_flakiness_by_ignoring_security_domains => true, 
   :ignore_protected_mode_settings=>true
}

caps = Selenium::WebDriver::Remote::Capabilities.ie(capsArray)
browser = Watir::Browser.new :ie, :desired_capabilities => caps
browser.goto 'https://www.google.com'

(or)

require 'watir'

browser = Watir::Browser.new :ie
browser.goto 'https://www.google.com'

**Comment by evnraja32** [comment]
Over-ridding Selenium::WebDriver::IE::Driver.create_capabilities method 
require 'watir'

module Selenium
   module WebDriver
      module IE
         class Driver < WebDriver::Driver
            include DriverExtensions::TakesScreenshot

            private
            def create_capabilities(opts)
               caps = opts.delete(:desired_capabilities) { Remote::Capabilities.internet_explorer }
               options = opts.delete(:options) { Options.new }
          
               options.ignore_protected_mode_settings = true #-- removed the old implementation and hard-coded this line
          
               native_events = opts.delete(:native_events)
               unless native_events.nil?
                  WebDriver.logger.deprecate ':native_events', 'Selenium::WebDriver::IE::Options#native_events='
                  options.native_events = native_events
               end

               # Backward compatibility with older IEDriverServer versions
               caps[:ignore_protected_mode_settings] = options.ignore_protected_mode_settings
               caps[:native_events] = options.native_events

               options = options.as_json
               caps.merge!(options) unless options.empty?

               caps
            end

         end # Driver
      end # IE
   end # WebDriver
end # Selenium

capsArray = {
   :introduce_flakiness_by_ignoring_security_domains => true, 
   :ignore_protected_mode_settings=>true
}

browser = Watir::Browser.new :ie, capsArray

browser.goto 'https://www.google.com'

**Comment by Rajagopalan-M** [comment]
Is there any need that you need to do through IE? Because I face many
problem when I use IE driver, so I go for WATIR -CLASSIC which is actually
deprecated. If possible automate through chrome or firefox .

**Comment by evnraja32** [comment]
Hi @Rajagopalan-M ,
Yes, The application which we test only supports IE and EDGE.
We also used WATIR-CLASSIC and WATIR-Webdriver. But the problem is we are supposed to maintain two different frameworks, here the IE framework(here framework refers to our project framework that supports automating our application) we built using Watir-Classic and an EDGE framework built on Watir-Webdriver. Even though we had two different frameworks for IE and EDGE but the test scripts will be written in such a way it supports both the IE and EDGE frameworks. Because of this approach, we have never seen a successful 100% pass in our batch executions, in one or other way we hit with the errors from methods we used to handle them in the application.

Also, this approach makes us put a lot of efforts in resolving our test framework issues.

To say an example :
handling pop-up in IE was different from EDGE. For the same in Watir-Classic rautomation was used to handle the alert, whereas, in Watir-Webdriver, Selenium-Webdriver alert mechanism was used. 
This way of handling making us put a lot of efforts in handling our project framework.

We thought of migrating from Watir-Classic and Watir-Webdriver to Watir-6.10.0 the latest version which built on top of Selenium and which can support both IE, EDGE and other browsers too.


Correct me, if my understanding wrong in the above comments.

**Comment by Rajagopalan-M** [comment]
@evnraja32 

Actually, WATIR(Powered by Selenium) is higher version of old WATIR-Webdriver. But WATIR-Classic is no way related to WATIR(Powered by Selenium) because WATIR-Classic uses WIN32OLE to automate the IE window but WATIR and old version of WATIR(watir-webdriver) is using Selenium under the hood to automate the Browser. 

Yes, you are right watir-classic uses rautomation window to handle the pop up whereas WATIR uses different approaches. 

Since WATIR-Classic is deprecated, I wouldn't ask you to use WATIR-Classic but compared to using IE driver to drive the IE window, it's far more better to use WATIR-classic. 

I had the same problem when I was automating my local application and portal. 

I will suggest you a way here, Input the browser type in your excel, like it's IE or EDGE, and include the code in your program like the one given below

```
if browsertype.eql? 'IE'
  require 'watir-classic'
elsif browsertype.eql? 'EDGE'
  require 'watir'
end
```
This way you can use WATIR(Powered by Selenium) and WATIR-classic in your project. You don't have to change any coding at your level because except few because WATIR is borrowing it's coding style from WATIR-Classic which was actually original WATIR.

**Comment by kapoorlakshya** [comment]
Here is how we deal with the protected modes in IE - https://gist.github.com/kapoorlakshya/71839d33d6e4938a191b91a55d2f225e

You can wrap that code in a method and invoke it right before launching the browser.

And I would personally recommend sticking with `watir` so that you can run the same code on all browsers instead of having to switch between `watir` and `watir-classic`, which do not have the same API.

**Comment by lmtierney** [comment]
Can you try this again since the recent changes in https://github.com/watir/watir/pull/803 (in `6.15.0`)? I believe it *should* have taken care of this.
