### ISSUE TITLE
Watir for IE Browser's set method delay's 5 seconds for each charter when typing text in the text field. This times delay results in Net::ReadTimeout error

### ISSUE THREAD

**Issue by evnraja32** [watir/watir#723]
## Meta -
Watir Version: 6.10.0
Selenium-Webdriver Version: 3.8.0
Browser Version: IE 11.0.9600.18977
Browser Driver Version: 3.8.0 (64-bit)
OS Version: Windows 7

Hi,
I'm just trying to type the string: '123456789012' in a web page's text field using watir. I noticed that when typing there is a time delay of 5seconds for each character. So, based on this time delay it took 60seconds for type the string that contains 12chars at the end of this execution I got a Net::ReadTimeout error.

This delay in typing something in a text field should be fixed. Because we may get a scenario where we have to type say 100 chars in a text field. So, we wait more time in this case

## Expected Behavior -
The text typing into the browser should be fast, no Net::ReadTimeout error thrown.

## Actual Behavior -
2018-05-09 17:41:24 +0530
2018-05-09 17:42:25 +0530
Net::ReadTimeout
C:/Ruby24-x64/lib/ruby/2.4.0/net/protocol.rb:176:in `rbuf_fill'
C:/Ruby24-x64/lib/ruby/2.4.0/net/protocol.rb:154:in `readuntil'
C:/Ruby24-x64/lib/ruby/2.4.0/net/protocol.rb:164:in `readline'
C:/Ruby24-x64/lib/ruby/2.4.0/net/http/response.rb:40:in `read_status_line'
C:/Ruby24-x64/lib/ruby/2.4.0/net/http/response.rb:29:in `read_new'
C:/Ruby24-x64/lib/ruby/2.4.0/net/http.rb:1446:in `block in transport_request'
C:/Ruby24-x64/lib/ruby/2.4.0/net/http.rb:1443:in `catch'
C:/Ruby24-x64/lib/ruby/2.4.0/net/http.rb:1443:in `transport_request'
C:/Ruby24-x64/lib/ruby/2.4.0/net/http.rb:1416:in `request'
C:/Ruby24-x64/lib/ruby/2.4.0/net/http.rb:1409:in `block in request'
C:/Ruby24-x64/lib/ruby/2.4.0/net/http.rb:877:in `start'
C:/Ruby24-x64/lib/ruby/2.4.0/net/http.rb:1407:in `request'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/remote/http/default.rb:121:in `response_for'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/remote/http/default.rb:76:in `request'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/remote/bridge.rb:164:in `execute'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/remote/w3c/bridge.rb:535:in `execute'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/remote/w3c/bridge.rb:365:in `send_keys_to_element'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/common/element.rb:154:in `send_keys'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/watir-6.10.0/lib/watir/user_editable.rb:13:in `block in set'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/watir-6.10.0/lib/watir/elements/element.rb:657:in `element_call'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/watir-6.10.0/lib/watir/user_editable.rb:11:in `set'
C:/Users/21946417/Documents/NetBeansProjects/HMSS_Selenium/test/mednet_test.rb:47:in `<main>'

## Steps to reproduce -

require 'watir'
require 'time'

module Selenium
   module WebDriver
      module IE
         class Driver < WebDriver::Driver
            include DriverExtensions::TakesScreenshot

            private
            def create_capabilities(opts)
               caps = opts.delete(:desired_capabilities) { Remote::Capabilities.internet_explorer }
               options = opts.delete(:options) { Options.new }
          
               options.ignore_protected_mode_settings = true
          
               native_events = opts.delete(:native_events)
               unless native_events.nil?
                  WebDriver.logger.deprecate ':native_events', 'Selenium::WebDriver::IE::Options#native_events='
                  options.native_events = native_events
               end

               # Backward compatibility with older IEDriverServer versions
               caps[:ignore_protected_mode_settings] = options.ignore_protected_mode_settings
               caps[:native_events] = options.native_events

               options = options.as_json
               caps.merge!(options) unless options.empty?

               caps
            end

         end # Driver
      end # IE
   end # WebDriver
end # Selenium

#watir google code
begin
   capsArray = {
      :introduce_flakiness_by_ignoring_security_domains => true, 
      :ignore_protected_mode_settings => true
   }
   @browser = Watir::Browser.new :ie, capsArray
   @browser.goto 'google.com'
   p Time.now
   @browser.text_field(title: 'Search').set '123456789012'
   p Time.now

rescue Net::ReadTimeout => e
   p Time.now
   puts e.message
   puts e.backtrace
end

**Comment by lmtierney** [comment]
You should never use the 64-bit IEDriver. Yes, even if everything else is 64-bit. Please read http://jimevansmusic.blogspot.com/2014/09/screenshots-sendkeys-and-sixty-four.html

**Comment by lmtierney** [comment]
Either way, this is obviously an IEDriver issue.

**Comment by titusfortner** [comment]
That said, you can speed text input if you want to use `#set!` instead of `#set`, since we've implemented it partially with JavaScript: `@browser.text_field(title: 'Search').set! '123456789012'`
