### ISSUE TITLE
Watir 6.11.0.beta1 upgrade appears to break PageObject Gem methods

### ISSUE THREAD

**Issue by newell-paul** [watir/watir#727]
## Meta -
Watir Version: 6.11.0.beta1
Selenium Version: 3.12
Browser Version: Chrome 66.0.3359
Browser Driver Version: ChromeDriver 2.36.540469
OS Version: OSX 10.11.6

## Expected Behaviour - 
PageObject gem check and uncheck methods should function the same as in previous Watir versions

## Actual Behaviour -
ArgumentError: wrong number of arguments (given 3, expected 2)
(eval):1:in `process_watir_call'

## Steps to reproduce -
Page object element:

```
 require 'page-object'
 class OptionPage
    include PageObject
    checkbox(:help, id: 'OPTION_HELP')
     ..
end
```
Step definition:
```
And(/^I (select|unselect) the help option$/) do |choice|
    choice == 'select' ? @option_page.check_help : @option_page.uncheck_help
end
```

Stack Trace:
ArgumentError: wrong number of arguments (given 3, expected 2)
/Users/guest/.rvm/gems/ruby-2.4.0/gems/page-object-2.2.4/lib/page-object/platforms/watir/page_object.rb:1066:in `instance_eval'
/Users/guest/.rvm/gems/ruby-2.4.0/gems/watir-6.11.0.beta1/lib/watir/locators/element/locator.rb:98:in `using_watir'
/Users/guest/.rvm/gems/ruby-2.4.0/gems/watir-6.11.0.beta1/lib/watir/locators/element/locator.rb:39:in `locate'
/Users/guest/.rvm/gems/ruby-2.4.0/gems/watigiri-0.3.1/lib/watigiri/locators/element/locator.rb:17:in `locate'
/Users/guest/.rvm/gems/ruby-2.4.0/gems/watir-6.11.0.beta1/lib/watir/elements/element.rb:595:in `locate'
/Users/guest/.rvm/gems/ruby-2.4.0/gems/watir-6.11.0.beta1/lib/watir/elements/element.rb:579:in `assert_exists'
/Users/guest/.rvm/gems/ruby-2.4.0/gems/watir-6.11.0.beta1/lib/watir/elements/element.rb:691:in `check_condition'
/Users/guest/.rvm/gems/ruby-2.4.0/gems/watir-6.11.0.beta1/lib/watir/elements/element.rb:656:in `element_call'
/Users/guest/.rvm/gems/ruby-2.4.0/gems/watir-6.11.0.beta1/lib/watir/elements/checkbox.rb:29:in `set?'
/Users/guest/.rvm/gems/ruby-2.4.0/gems/watir-6.11.0.beta1/lib/watir/elements/checkbox.rb:19:in `set'
(eval):1:in `process_watir_call'
/Users/guest/.rvm/gems/ruby-2.4.0/gems/page-object-2.2.4/lib/page-object/platforms/watir/page_object.rb:1066:in `instance_eval'
/Users/guest/.rvm/gems/ruby-2.4.0/gems/page-object-2.2.4/lib/page-object/platforms/watir/page_object.rb:1066:in `process_watir_call'
/Users/guest/.rvm/gems/ruby-2.4.0/gems/page-object-2.2.4/lib/page-object/platforms/watir/page_object.rb:355:in `check_checkbox'
/Users/guest/.rvm/gems/ruby-2.4.0/gems/page-object-2.2.4/lib/page-object/accessors.rb:329:in `block in checkbox'
/Users/guest/RubymineProjects/Demo/features/step_definitions/my_steps.rb:182:in `block in <top (required)>'
/Users/guest/.rvm/gems/ruby-2.4.0/gems/cucumber-3.1.0/lib/cucumber/glue/invoke_in_world.rb:38:in `instance_exec'
/Users/guest/.rvm/gems/ruby-2.4.0/gems/cucumber-3.1.0/lib/cucumber/glue/invoke_in_world.rb:38:in `block in cucumber_instance_exec_in'
/Users/guest/.rvm/gems/ruby-2.4.0/gems/cucumber-3.1.0/lib/cucumber/glue/invoke_in_world.rb:53:in `cucumber_run_with_backtrace_filtering'
/Users/guest/.rvm/gems/ruby-2.4.0/gems/cucumber-3.1.0/lib/cucumber/glue/invoke_in_world.rb:26:in `cucumber_instance_exec_in'
/Users/guest/.rvm/gems/ruby-2.4.0/gems/cucumber-3.1.0/lib/cucumber/glue/step_definition.rb:110:in `invoke'
/Users/guest/.rvm/gems/ruby-2.4.0/gems/cucumber-3.1.0/lib/cucumber/step_match.rb:31:in `invoke'
/Users/guest/.rvm/gems/ruby-2.4.0/gems/cucumber-3.1.0/lib/cucumber/step_match.rb:24:in `block in activate'
/Users/guest/.rvm/gems/ruby-2.4.0/gems/cucumber-core-3.1.0/lib/cucumber/core/test/action.rb:24:in `execute'
/Users/guest/.rvm/gems/ruby-2.4.0/gems/cucumber-core-3.1.0/lib/cucumber/core/test/step.rb:32:in `execute'
/Users/guest/.rvm/gems/ruby-2.4.0/gems/cucumber-core-3.1.0/lib/cucumber/core/test/runner.rb:104:in `execute'
/Users/guest/.rvm/gems/ruby-2.4.0/gems/cucumber-core-3.1.0/lib/cucumber/core/test/runner.rb:51:in `execute'
/Users/guest/.rvm/gems/ruby-2.4.0/gems/cucumber-core-3.1.0/lib/cucumber/core/test/runner.rb:27:in `test_step'
/Users/guest/.rvm/gems/ruby-2.4.0/gems/cucumber-core-3.1.0/lib/cucumber/core/test/step.rb:17:in `describe_to'
/Users/guest/.rvm/gems/ruby-2.4.0/gems/cucumber-core-3.1.0/lib/cucumber/core/test/case.rb:28:in `block (3 levels) in describe_to'
/Users/guest/.rvm/gems/ruby-2.4.0/gems/cucumber-core-3.1.0/lib/cucumber/core/test/case.rb:27:in `each'
/Users/guest/.rvm/gems/ruby-2.4.0/gems/cucumber-core-3.1.0/lib/cucumber/core/test/case.rb:27:in `block (2 levels) in describe_to'
/Users/guest/.rvm/gems/ruby-2.4.0/gems/cucumber-3.1.0/lib/cucumber/filters/prepare_world.rb:23:in `block in test_case'
/Users/guest/.rvm/gems/ruby-2.4.0/gems/cucumber-core-3.1.0/lib/cucumber/core/test/around_hook.rb:17:in `execute'
/Users/guest/.rvm/gems/ruby-2.4.0/gems/cucumber-core-3.1.0/lib/cucumber/core/test/runner.rb:104:in `execute'
/Users/guest/.rvm/gems/ruby-2.4.0/gems/cucumber-core-3.1.0/lib/cucumber/core/test/runner.rb:51:in `execute'
/Users/guest/.rvm/gems/ruby-2.4.0/gems/cucumber-core-3.1.0/lib/cucumber/core/test/runner.rb:34:in `around_hook'
/Users/guest/.rvm/gems/ruby-2.4.0/gems/cucumber-core-3.1.0/lib/cucumber/core/test/around_hook.rb:12:in `describe_to'
/Users/guest/.rvm/gems/ruby-2.4.0/gems/cucumber-core-3.1.0/lib/cucumber/core/test/case.rb:120:in `block (2 levels) in compose_around_hooks'
/Users/guest/.rvm/gems/ruby-2.4.0/gems/cucumber-core-3.1.0/lib/cucumber/core/test/case.rb:121:in `compose_around_hooks'
/Users/guest/.rvm/gems/ruby-2.4.0/gems/cucumber-core-3.1.0/lib/cucumber/core/test/case.rb:26:in `block in describe_to'
/Users/guest/.rvm/gems/ruby-2.4.0/gems/cucumber-core-3.1.0/lib/cucumber/core/test/runner.rb:19:in `test_case'
/Users/guest/.rvm/gems/ruby-2.4.0/gems/cucumber-core-3.1.0/lib/cucumber/core/test/case.rb:25:in `describe_to'
/Users/guest/.rvm/gems/ruby-2.4.0/gems/cucumber-3.1.0/lib/cucumber/filters/prepare_world.rb:12:in `test_case'
/Users/guest/.rvm/gems/ruby-2.4.0/gems/cucumber-core-3.1.0/lib/cucumber/core/test/case.rb:25:in `describe_to'
/Users/guest/.rvm/gems/ruby-2.4.0/gems/cucumber-core-3.1.0/lib/cucumber/core/filter.rb:57:in `test_case'
/Users/guest/.rvm/gems/ruby-2.4.0/gems/cucumber-3.1.0/lib/cucumber/filters/retry.rb:18:in `test_case'
/Users/guest/.rvm/gems/ruby-2.4.0/gems/cucumber-core-3.1.0/lib/cucumber/core/test/case.rb:25:in `describe_to'
/Users/guest/.rvm/gems/ruby-2.4.0/gems/cucumber-3.1.0/lib/cucumber/filters/quit.rb:12:in `test_case'
/Users/guest/.rvm/gems/ruby-2.4.0/gems/cucumber-core-3.1.0/lib/cucumber/core/test/case.rb:25:in `describe_to'
/Users/guest/.rvm/gems/ruby-2.4.0/gems/cucumber-3.1.0/lib/cucumber/filters/broadcast_test_run_started_event.rb:20:in `block in done'
/Users/guest/.rvm/gems/ruby-2.4.0/gems/cucumber-3.1.0/lib/cucumber/filters/broadcast_test_run_started_event.rb:19:in `map'
/Users/guest/.rvm/gems/ruby-2.4.0/gems/cucumber-3.1.0/lib/cucumber/filters/broadcast_test_run_started_event.rb:19:in `done'
/Users/guest/.rvm/gems/ruby-2.4.0/gems/cucumber-core-3.1.0/lib/cucumber/core/filter.rb:62:in `done'
/Users/guest/.rvm/gems/ruby-2.4.0/gems/cucumber-core-3.1.0/lib/cucumber/core/filter.rb:62:in `done'
/Users/guest/.rvm/gems/ruby-2.4.0/gems/cucumber-core-3.1.0/lib/cucumber/core/filter.rb:62:in `done'
/Users/guest/.rvm/gems/ruby-2.4.0/gems/cucumber-core-3.1.0/lib/cucumber/core/filter.rb:62:in `done'
/Users/guest/.rvm/gems/ruby-2.4.0/gems/cucumber-core-3.1.0/lib/cucumber/core/filter.rb:62:in `done'
/Users/guest/.rvm/gems/ruby-2.4.0/gems/cucumber-core-3.1.0/lib/cucumber/core/test/filters/locations_filter.rb:20:in `done'
/Users/guest/.rvm/gems/ruby-2.4.0/gems/cucumber-core-3.1.0/lib/cucumber/core/filter.rb:62:in `done'
/Users/guest/.rvm/gems/ruby-2.4.0/gems/cucumber-core-3.1.0/lib/cucumber/core/test/filters/tag_filter.rb:18:in `done'
/Users/guest/.rvm/gems/ruby-2.4.0/gems/cucumber-core-3.1.0/lib/cucumber/core/compiler.rb:24:in `done'
/Users/guest/.rvm/gems/ruby-2.4.0/gems/cucumber-core-3.1.0/lib/cucumber/core/gherkin/parser.rb:37:in `done'
/Users/guest/.rvm/gems/ruby-2.4.0/gems/cucumber-core-3.1.0/lib/cucumber/core.rb:32:in `parse'
/Users/guest/.rvm/gems/ruby-2.4.0/gems/cucumber-core-3.1.0/lib/cucumber/core.rb:21:in `compile'
/Users/guest/.rvm/gems/ruby-2.4.0/gems/cucumber-3.1.0/lib/cucumber/runtime.rb:74:in `run!'
/Users/guest/.rvm/gems/ruby-2.4.0/gems/cucumber-3.1.0/lib/cucumber/cli/main.rb:33:in `execute!'
/Users/guest/.rvm/gems/ruby-2.4.0/gems/cucumber-3.1.0/bin/cucumber:9:in `<top (required)>'
/Users/guest/.rvm/gems/ruby-2.4.0/bin/cucumber:23:in `load'
/Users/guest/.rvm/gems/ruby-2.4.0/bin/cucumber:23:in `<top (required)>'
-e:1:in `load'
-e:1:in `<main>'
/Users/guest/RubymineProjects/Demo/features/options.feature:5:in `And I select the help option

**Comment by titusfortner** [comment]
Aha, you are using watigiri, which is where the error is coming from. I need to update that gem.

**Comment by newell-paul** [comment]
I didn't understand too much of the stack trace but I noticed that Watigiri was getting a couple of mentions even though I am not sure why it would impact on these particular tests. I have now taken out Watigiri from the test suite and the few tests I have run are now running fine.  Thanks for the great support!

**Comment by titusfortner** [comment]
I think watigiri 0.3.2 fixes this. At any rate if there is still a problem, we'll want to track it in that project.
