### ISSUE TITLE
Convert to String custom attribute passed as Symbol into #Attribute method

### ISSUE THREAD

**Issue by jff05** [watir/watir#750]
## Meta -
Watir Version: 6.11.0
Selenium Version: 3.12.0
Browser Version: FF 60.0.2
Browser Driver Version: 
OS Version: Windows 7

## Expected Behavior -
I would like to be able to pass on to the #Attribute method a custom attribute by Symbol such as :data_*
rather than by its String that would be 'data-*'

`puts elmt.attribute('data-widgetapplicationid').nil?`
#=> false
`puts elmt.attribute('data-widgetapplicationid')`
#=> Application.413

`puts elmt.attribute(:data_widgetapplicationid).nil?`
#=>  false
`puts elmt.attribute(:data_widgetapplicationid)`
#=>  Application.413

## Actual Behavior -
Currently if I do pass my custom attribute by Symbol, no error is being thrown but my attribute is not being recognized as it would be as a String.

`puts elmt.attribute('data-widgetapplicationid').nil?`
#=> false
`puts elmt.attribute('data-widgetapplicationid')`
#=> Application.413

`puts elmt.attribute(:data_widgetapplicationid).nil?`
**#=>  true**
`puts elmt.attribute(:data_widgetapplicationid)`
**#=>  nil**

## Steps to reproduce -
`<div id="1" data-widgetapplicationid="Application.413">text</div>`

`puts browser.div(id: '1').attribute('data-widgetapplicationid').nil?`
#=> false
`puts browser.div(id: '1').attribute('data-widgetapplicationid')`
#=> Application.413

`puts browser.div(id: '1').attribute(:data_widgetapplicationid).nil?`
**#=>  true**
`puts browser.div(id: '1').attribute(:data_widgetapplicationid)`
**#=>  nil**

**Comment by jkotests** [comment]
Note that because you can access data-* attributes by method - eg:

~~~~~~~~
browser.div(id: '1').data_widgetapplicationid
#=> "Application.413"
~~~~~~~~

You can use `#send` to access the attribute by Symbol:

~~~~~~~~
browser.div(id: '1').send(:data_widgetapplicationid)
#=> "Application.413"
~~~~~~~~

**Comment by p0deje** [comment]
Why don't you just cast symbols to strings by yourself?

Closing as this works as expected and @jkotests provided a solution already.

**Comment by jff05** [comment]
@p0deje If I opened this issue, it is not about me not being able to do what I want to achieve, I also provided myself with a different solution to my problem.
This issue was meant to make the use of Watir #Attribute method more "general".

When Watir contains the below in /element_locator_spec.rb:
     ` it "handles selector with attribute presence" do`
       `  expect_one :xpath, ".//*[@data-view]"`
       `  locate_one [:data_view, true]`
     ` end`

It lets the user define a Key locator as described, then why not treat that Key locator as any other?
If there is any good argument against it, then I would say it should fire up an error otherwise it becomes confusing for a newbie like me at least.

**Comment by p0deje** [comment]
@jff05 I see your point now. Support landed in master now.

**Comment by jff05** [comment]
Glad I was able to express properly my point. @p0deje  Thank-you for accepting & supporting the change.

**Comment by titusfortner** [comment]
Thanks for adding this @p0deje
