### ISSUE TITLE
Unused list ?

### ISSUE THREAD

**Issue by prakharrr** [watir/watir#754]
https://github.com/watir/watir/blob/a3d7f9cc50229b6b3e73c0f16868733f52af5124/lib/watir/attribute_helper.rb#L24

**Comment by kapoorlakshya** [comment]
If I understand it correctly, by design, `list` is what is returned from the block in parentheses and then `uniq` is called on it.  This is same as:

```
(typed_attributes.values.flatten
  .ancestors[1 .. -1].map do |e|
      e.attribute_list if e.respond_to?(:attribute_list)
    end.compact.flatten
).uniq
```

Storing it in `list` makes the code more readable.

**Comment by prakharrr** [comment]
Thanks
