### ISSUE TITLE
b.exists? is not working when we do checking after we manually closes the window.

### ISSUE THREAD

**Issue by Rajagopalan-M** [watir/watir#762]
## Meta -
Watir Version: Recent Version
Selenium Version: Recent Version 
OS Version: windows

## Expected Behavior -

It has to return true or false

## Actual Behavior -

It's returning `chrome not reachable` for Chrome and `Failed to decode response from marionette` for firefox.

## Steps to reproduce -

If program closes the browser, then this problem wouldn't arises but if we manually closes the browser and check whether browser exist or not, this problem occurs

> require 'watir'
> driver=Selenium::WebDriver.for :firefox
> b=Watir::Browser.new driver
> b.goto 'www.google.com'
> b.close  #If this lines is written then everything goes fine
> puts b.exists?

 #If we don't write the `b.close` and If we put a debug point in the last line `puts b.exists` and when we execute the problem we stop by at the debug point and then if we manually closes the browser and then If we continue execute this line, this throws the error. This is happening due to 

>  def exist?
>       !@closed && window.present?
>  end

`!closed` executes just fine if program closes the browser but if we manually closes the browser then it's still returning true and this expected behavior and that's what you people are doing another checking `window.present?` but it's not working as expected because 

> raise(Exception::NoMatchingWindowFoundException, @selector.inspect) unless @driver.window_handles.include?(handle)

You are making a call to the driver `@driver.window_handles.include?(handle)` and this line ultimately fails because browser doesn't exist. But this should not be an expected behavior because I am inquiring whether browser exist or not.

**Comment by titusfortner** [comment]
What are the actual exceptions getting raised? When Google finally switches to w3c I think they'll both throw the same error and we can rescue that for this method call.

**Comment by Rajagopalan-M** [comment]
@titusfortner 

For Firefox

> 
> 
> Uncaught exception: Failed to decode response from marionette
> 	C:/Ruby/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.13.1/lib/selenium/webdriver/remote/response.rb:69:in `assert_ok'
> 	C:/Ruby/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.13.1/lib/selenium/webdriver/remote/response.rb:32:in `initialize'
> 	C:/Ruby/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.13.1/lib/selenium/webdriver/remote/http/common.rb:84:in `new'
> 	C:/Ruby/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.13.1/lib/selenium/webdriver/remote/http/common.rb:84:in `create_response'
> 	C:/Ruby/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.13.1/lib/selenium/webdriver/remote/http/default.rb:104:in `request'
> 	C:/Ruby/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.13.1/lib/selenium/webdriver/remote/http/common.rb:62:in `call'
> 	C:/Ruby/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.13.1/lib/selenium/webdriver/remote/bridge.rb:164:in `execute'
> 	C:/Ruby/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.13.1/lib/selenium/webdriver/remote/w3c/bridge.rb:548:in `execute'
> 	C:/Ruby/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.13.1/lib/selenium/webdriver/remote/w3c/bridge.rb:161:in `window_handle'
> 	C:/Ruby/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.13.1/lib/selenium/webdriver/common/driver.rb:195:in `window_handle'
> 	C:/Ruby/lib/ruby/gems/2.3.0/gems/watir-6.12.0/lib/watir/window.rb:230:in `current_window'
> 	C:/Ruby/lib/ruby/gems/2.3.0/gems/watir-6.12.0/lib/watir/window.rb:12:in `initialize'
> 	C:/Ruby/lib/ruby/gems/2.3.0/gems/watir-6.12.0/lib/watir/has_window.rb:33:in `new'
> 	C:/Ruby/lib/ruby/gems/2.3.0/gems/watir-6.12.0/lib/watir/has_window.rb:33:in `window'
> 	C:/Ruby/lib/ruby/gems/2.3.0/gems/watir-6.12.0/lib/watir/browser.rb:303:in `exist?'
> 	C:/Users/rajagopalan.m/RubymineProjects/Rajagopalan/Ruby Questions And Answers/example.rb:7:in `<top (required)>'

For Chrome

> 
> Uncaught exception: chrome not reachable
>   (Session info: chrome=67.0.3396.99)
>   (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab),platform=Windows NT 10.0.14393 x86_64)
> 	C:/Ruby/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.13.1/lib/selenium/webdriver/remote/response.rb:69:in `assert_ok'
> 	C:/Ruby/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.13.1/lib/selenium/webdriver/remote/response.rb:32:in `initialize'
> 	C:/Ruby/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.13.1/lib/selenium/webdriver/remote/http/common.rb:84:in `new'
> 	C:/Ruby/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.13.1/lib/selenium/webdriver/remote/http/common.rb:84:in `create_response'
> 	C:/Ruby/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.13.1/lib/selenium/webdriver/remote/http/default.rb:104:in `request'
> 	C:/Ruby/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.13.1/lib/selenium/webdriver/remote/http/common.rb:62:in `call'
> 	C:/Ruby/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.13.1/lib/selenium/webdriver/remote/bridge.rb:164:in `execute'
> 	C:/Ruby/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.13.1/lib/selenium/webdriver/remote/oss/bridge.rb:580:in `execute'
> 	C:/Ruby/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.13.1/lib/selenium/webdriver/remote/oss/bridge.rb:152:in `window_handles'
> 	C:/Ruby/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.13.1/lib/selenium/webdriver/common/driver.rb:185:in `window_handles'
> 	C:/Ruby/lib/ruby/gems/2.3.0/gems/watir-6.12.0/lib/watir/window.rb:225:in `assert_exists'
> 	C:/Ruby/lib/ruby/gems/2.3.0/gems/watir-6.12.0/lib/watir/window.rb:108:in `exists?'
> 	C:/Ruby/lib/ruby/gems/2.3.0/gems/watir-6.12.0/lib/watir/browser.rb:303:in `exist?'
> 	C:/Users/rajagopalan.m/RubymineProjects/Rajagopalan/Ruby Questions And Answers/example.rb:7:in `<top (required)>'
>

**Comment by titusfortner** [comment]
What is the error class for those?

**Comment by Rajagopalan-M** [comment]
@titusfortner It's not giving any error class like `ElementClickInterceptedError`, What I posted is the whole message.

**Comment by titusfortner** [comment]
Interesting, it doesn't show up because there are multiple errors:

```ruby
Exception `KeyError' at /Users/titusfortner/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.14.0/lib/selenium/webdriver/common/error.rb:32 - key not found: 100
Exception `Selenium::WebDriver::Error::WebDriverError' at /Users/titusfortner/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.14.0/lib/selenium/webdriver/remote/response.rb:70 - chrome not reachable
  (Session info: chrome=67.0.3396.99)
```

So, we could do a generic rescue of `Selenium::WebDriver::Error::WebDriverError` and return false, but I believe that Watir should not be masking what I consider to be a true exception (your browser shouldn't be closed in this manner and if it is you have problems).

At the very least for Watir to handle this Selenium would need to have consistent behavior between the browsers, and for that we'll need to finish with w3c adoption.

In the meantime you are welcome to rescue that exception in your code and it will work as you want it to.

**Comment by Rajagopalan-M** [comment]
Exactly!  Generic class exception should not be rescued.

**Comment by Rajagopalan-M** [comment]
Yes, okay. Yes we can't rescue the generic error!
