### ISSUE TITLE
Copy past of examples from your website do not work!

### ISSUE THREAD

**Issue by artmai** [watir/watir#765]
I am replicating the examples from your website on a file.rb (not using gems) and it used to work 2 weeks ago, now it doesn't work anymore. 

I am just copy/pasting this:

require 'watir'

browser = Watir::Browser.new

browser.goto 'watir.com'
browser.link(text: 'documentation').click

puts browser.title
browser.close

And I have the following errors:
- warning: constant ::Fixnum is deprecated
- undefined method `col_span' for class `Watir::TableCell'

These seem to be covered on the web many times, but looks like there is not solide answer. So asking here.

Many thanks for help in advance!

**Comment by titusfortner** [comment]
First, where on the website are you seeing that code? I'll get it updated.

As for the errors, they should have been fixed in Watir 6.1 (#510). Please update your gem to the latest version.

**Comment by titusfortner** [comment]
I can't find this code on our current website, and the underlying error has been fixed, so I'm closing this.

**Comment by artmai** [comment]
This is where the code was: https://www.rubydoc.info/gems/watir/

Which can be accessed via the: "Watir Documentation" link.

Version of Watir was updated.

Let me know.
