### ISSUE TITLE
Getting Net::ReadTimeout errors about 10% of the time

### ISSUE THREAD

**Issue by macmartine** [watir/watir#774]
## Meta -
Watir Version: 6.12.0
Selenium Version: 
Browser Version: Google Chrome 68.0.3440.75
Browser Driver Version: ChromeDriver 2.40.565383
OS Version: 
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.5 LTS
Release:        16.04
Codename:       xenial

## Expected Behavior -

Less Net::ReadTimeout errors

## Actual Behavior -

I seem to be getting Net::ReadTimeout about 10% of the time when my Ruby scripts try to open a URL in headless chrome. I realize this may be a selenium (or other) issues, and maybe not Watir, specific, but how can I track down why this is happening?

Often times if I have the page reload a time or two it eventually works.

Thanks

## Steps to reproduce -

Do this a bunch of time, and about 1 in 10 will get ReadTimeout:
@b.goto 'someurl'

**Comment by titusfortner** [comment]
This is almost always a network error or problem with the system under test. Are the tests running just fine when not in headless mode? (also, do you *need to be running in headless mode?)

**Comment by titusfortner** [comment]
Since this is not an issue with the code, I'm closing this. Contact us by one of our support methods if you still need help: http://watir.com/help/
