### ISSUE TITLE
Provide a way to search for text using XPath predicate

### ISSUE THREAD

**Issue by abotalov** [watir/watir#786]
## Expected Behavior -
There should be an option (maybe `browser.element(class: x, all_text: y)`) that will be converted to XPath.

## Actual Behavior -
When `browser.element(class: x, text: y)` is called, Watir iterates through all elements with class `x` to find an element with text `y`. This is slow if there are many elements with class `x`. That's why I currently use xpath directly on some cases.

**Comment by jkotests** [comment]
@abotalov , is `y` a String or a Regexp?

We should already be doing this for Strings:

~~~~~~~~
browser.element(class: 'a', text: 'y').exists?
#=>2018-09-18 16:44:51 DEBUG Watir Converted {:class=>"a", :text=>"y"} to 
  [:xpath, ".//*[contains(concat(' ', @class, ' '), ' a ') and normalize-space()='y']"]
~~~~~~~~

In the case of Regexps, we don't do anything. We could presumably make similar optimizations to what we did for attributes - ie trying to put part of the regexp into the XPath.

**Comment by titusfortner** [comment]
The specific behavior requested here has been implemented. I believe the intended request is to allow users to leverage the Regexp optimizations we are currently using for attributes. This will require us to remove support for text_regexp deprecation in Watir 7, and will be a straightforward add with the new code.
