### ISSUE TITLE
Handle attribute names containing special characters

### ISSUE THREAD

**Issue by abotalov** [watir/watir#787]
## Expected Behavior -
CSS allows to escape special characters using a backslash.
It may be good to build a CSS selector from a dictionary of attributes if some name contains not allowed characters.

## Actual Behavior -
HTML allows mostly any characters in attribute names. XML / XPath allows only a small subset of letters (https://www.w3.org/TR/REC-xml/#NT-NameChar).
That means that if an attribute name contains some special symbols, XPath search won't find anything.

E.g. `browser.element("{name}": value)`

**Comment by titusfortner** [comment]
There is https://github.com/watir/watir_css/ if there are things you need to do with CSS. I haven't updated it in a while, so we'd have to double check it works with the latest. We used to do a combination of CSS & XPath, but I felt it unnecessarily overcomplicated the code.

**Comment by twalpole** [comment]
FYI - you should be able to work around this in most, if not all, cases with the `attribute` axis and a `local-name`/`name` condition - if the parser doesn't discard the attribute (chrome/ff don't - nokogiri does)

**Comment by abotalov** [comment]
As a note, here's a PR from @twalpole to a dependency of Capybara that does it - https://github.com/teamcapybara/xpath/pull/93/files

**Comment by titusfortner** [comment]
Any interest in making a PR with the code you want to see here?
