### ISSUE TITLE
Can not load cookies - Psych::DisallowedClass: Tried to load unspecified class: Time

### ISSUE THREAD

**Issue by mpz** [watir/watir#790]
## Meta -
Watir Version: 6.14.0
Selenium Version: ~> 3.4, >= 3.4.1

## Expected Behavior -
Can load cookies with cookies.load

## Actual Behavior -
```
Errors occurs: 
Psych::DisallowedClass: Tried to load unspecified class: Time 
from /home/mpz/.rvm/gems/ruby-2.4.0/gems/psych-2.2.4/lib/psych/class_loader.rb:97:in `find'
from /home/mpz/.rvm/gems/ruby-2.4.0/gems/psych-2.2.4/lib/psych/class_loader.rb:28:in `load'
```

## Steps to reproduce -
browser = Watir::Browser.new :firefox
browser.cookies.save
browser.cookies.load

**Comment by mpz** [comment]
It can be fixed with 

`YAML.safe_load(IO.read(file), [Symbol, Time])`

we have only:
`YAML.safe_load(IO.read(file), [::Symbol])`

in https://github.com/watir/watir/blob/master/lib/watir/cookies.rb at @load funct


Full code:

```
module Watir
  class Cookies
    def load(file = '.cookies')
      YAML.safe_load(IO.read(file), [::Symbol, ::Time]).each do |c|
        add(c.delete(:name), c.delete(:value), c)
      end
    end
  end
end
```

**Comment by titusfortner** [comment]
What do you have in your yaml? The code converts string values to time objects.

**Comment by mpz** [comment]
Something like this. 

```
- :name: ds_user_id
  :value: '8535281790'
  :path: "/"
  :domain: ".google.com"
  :expires: 2018-12-19 12:27:56.000000141 +00:00
  :secure: false
```

issue with :expires
if remove it line - this error fixed

**Comment by titusfortner** [comment]
It should work if you put quotes around it. I'd almost rather switch away from safe load if we have to make a bunch of exceptions.

**Comment by titusfortner** [comment]
Actually, we can go ahead and add it. Want to PR it?

**Comment by bsolovei25** [comment]
thanks to @mpz solved my problem with Time class
