### ISSUE TITLE
Not able to start Watir (6.14) remote with chrome headless

### ISSUE THREAD

**Issue by diogopublio** [watir/watir#794]
I am either using the wrong syntax, or there something not compatible:

I tried both:

browser = Watir::Browser.new :chrome, {headless: true,timeout: 120, url: selenium_server}
	
browser = Watir::Browser.new :chrome, :switches => %w[--ignore-certificate-errors --disable-popup-blocking --disable-translate --disable-notifications --start-maximized --disable-gpu --headless]
driver.driver.manage.timeouts.implicit_wait = 100 # seconds

server starts ok but in regular mode.

I have latest version of chromedriver,chrome,zalenium,selenium and watir

**Comment by lmtierney** [comment]
Both of your attempts work fine for me with (with `6.14.0`) using a local selenium server. Can you try the latest and provide debug output from your server?

**Comment by mark0203** [comment]
I've been trying to verify this issue, but I cannot reproduce it. Both local and on a simple selenium-grid chrome starts in headless mode just fine
Just verified that on:

- Windows 10
- Chrome 74
- Ruby 2.5.5
- selenium-webdriver 3.142.3
- watir 6.16.5
