### ISSUE TITLE
Rethinking Nested Elements

### ISSUE THREAD

**Issue by titusfortner** [watir/watir#797]
Now that we are spending time rethinking how Selector Builder works, and now that we are focusing on performance for remote execution and minimizing wire calls....

I think we should investigate merging nested elements into a single locator when possible.

It woks as long as an element does not need filtering, so we create a locator for `browser.tr.td` like:
```ruby
.//*[local-name()='tr']//[local-name()='td']
```
This would drop a number of current wire calls as we do our location recursion.

I'm not sure how this would affect other Selector implementations like Watizzle, etc.

**Comment by jkotests** [comment]
I'm all for performance gains.

Note that when joining the selectors, it's a bit more complicated that just concatenating them. We will need to make sure that we are only searching within the first matching element. For example, the mentioned XPath will actually look for all tds that are a descendant of any tr. In contrast, the Watir code would only look for tds within the very first tr.

**Comment by titusfortner** [comment]
But we'd be finding the first `td` in the first `tr`.

In other words, the example above will work, but this won't:
```ruby
browser.tr.tds
```
I'm not sure off hand how we would support that.

We could also support Collections as query scopes with the XPath above:
```ruby
browser.trs.td(class: 'foo')
```

**Comment by jkotests** [comment]
I'm saying that given the HTML:

~~~~~~~~
<table>
  <tr></tr>
  <tr>
    <td></td>
  </tr>
</table>
~~~~~~~~

Then the Watir code:

~~~~~~~~
p browser.tr.td.exists?
#=> false
~~~~~~~~
Is not equivalent to the suggested XPath:

~~~~~~~~
p browser.td(xpath: ".//*[local-name()='tr']//*[local-name()='td']").exists?
#=> true
~~~~~~~~

In terms of collections, I think I am thinking the opposite. `browser.tr.tds` should be do-able. It's just a difference between matching first vs all. `browser.trs.td` would seem out-of-place given the current behaviour. It'd be a short-cut for `browser.trs.map { |tr| tr.td }`? I guess that's handy... but feels less readable?

**Comment by titusfortner** [comment]
Ah, I see what you are saying, yes, that makes sense.

I'd have to spend more time thinking about this and writing specs. Just wanted to put it on the radar as something that would be nice to see improved if we can find a way....

Could we just add an index to it to make it work?
```ruby
.//*[local-name()='tr'][1]//*[local-name()='td']
```

**Comment by jkotests** [comment]
There was something to remember about getting the nth item. I think you needed brackets:

~~~~~~~~
(.//*[local-name()='tr'])[1]//*[local-name()='td']
~~~~~~~~

... this is exactly why people need Watir. Stupid XPath rules.

**Comment by titusfortner** [comment]
That's what writing a bunch of specs is for...

**Comment by titusfortner** [comment]
#822 addresses this.
