### ISSUE TITLE
present? returns true on some hidden elements

### ISSUE THREAD

**Issue by patrick-silvera** [watir/watir#811]
I just upgraded from Watir 6.11.0 to 6.14.0 and replaced `visible?` occurrences with `present?`. I got some unexpected behavior with hidden elements (present in DOM but not displayed on screen).

## Meta -
Watir Version: 6.14.0
Selenium Version:  ?
Browser Version: Chrome 69.0.3497.100 (Official Build) (64-bit)
Browser Driver Version: ChromeDriver 70.0.3538.16
OS Version: Debian 9.4.0

## Expected Behavior -
When an element is not displayed on the page, `present?` should return `false` and `wait_until_present` should time out.

## Actual Behavior -
On some hidden elements, `present?` always returns true although `wait_until_present` or `wait_until(&:present?)` do time out.

### Case 1 : 
For `<div id="some-id" style="display:block;" class="some-class">` then div.present? is `true`
### Case 2 : 
For a `ul` with a class forcing opacity to 0 then ul.present? is `true`

In both cases, the behavior is different from `wait_until_present` (timed out after x seconds, waiting for element)

**Comment by titusfortner** [comment]
These worked with wait until visible 6.11 and don't work with wait until present 6.14?

**Comment by tobytang1987** [comment]
Did you use ```activesupport``` gem? It has implemented ```present?``` method on Object class.  
This may make your call to ```present?``` method always return true in some cases.

**Comment by patrick-silvera** [comment]
@tobytang1987 you are right, the `present?` method from `activesupport` is called instead (with `div.present?` but not `div.wait_until_present`). As I was only using `visible?` method before updating Watir I didn't see this.
Do you know how I make sure the Watir `present?` is called ?

**Comment by kapoorlakshya** [comment]
@Oopla - If you are using the `page-object` gem, you need this fix - https://github.com/cheezy/page-object/pull/466

**Comment by patrick-silvera** [comment]
My bad, the Watir `present?` method is called correctly.
It turns out I'm using cheezy page-object gem and the issue is in this gem :
https://github.com/cheezy/page-object/issues/465

Thanks for your help.

**Comment by patrick-silvera** [comment]
Ho you were faster than me ;D
