### ISSUE TITLE
Execute_script doesn't wait for argument elements to exist

### ISSUE THREAD

**Issue by abotalov** [watir/watir#813]
## Expected Behavior -
`Browser#execute_script` waits for argument elements to exist.

## Actual Behavior -
`Browser#execute_script` doesn't seem to wait for its argument elements to exist.
It calls `wd` that calls `assert_exists`. `assert_exists` raises an error if element isn't found.
I think it would make sense to wait for elements to exist.

**Comment by titusfortner** [comment]
This seems reasonable. Any chance you want to make a PR? :)

**Comment by reach2jeyan** [comment]
I'll take a look at this and try to raise a PR.
