### ISSUE TITLE
browser.alert.close hangs when there are multiple config dialogs on the page

### ISSUE THREAD

**Issue by waynehoover** [watir/watir#817]
## Meta -
gem 'watir', '6.14.0'
gem 'selenium-webdriver', '3.141.0'
gem "webdrivers", "~> 3.0"
gem 'headless', '2.3.1'

Browser Version: firefox 63.0.1
OS Version: macos 10.14.1

## Expected Behavior -
When I browse to a page that has multiple confirm dialogs and do browser.alert.close it shouldn't hang.

## Actual Behavior -

It hangs when there are multiple js confirm dialogs on a page. Even when I try and browser.html when there is an alert it hangs.

## Steps to reproduce -
go to a page like that has code like this:
<html>
  <head>
  </head>
  <body>
    <script language="javascript">
      i = 0;
      while (i < 4) {
        window.confirm("Confirm: " + i);
        i += 1;
      }
    </script>
  </body>
</html>

and then do browser.alert.close, and notice it hang.

**Comment by titusfortner** [comment]
I can reproduce this in Firefox, but it works just fine with Chrome. As such, this appears to be a bug from Mozilla, so you should raise an issue on the geckodriver project and follow it there.
