### ISSUE TITLE
wait_until(&:stale?) is unable to check staleness

### ISSUE THREAD

**Issue by jkotests** [watir/watir#819]
## Meta -
Watir Version: 6.15
Selenium Version: 3.14
Browser Version: Chrome 70.0.3538.77
Browser Driver Version: ChromeDriver 2.42.591088
OS Version: Windows 7

## Expected Behavior -

`e.wait_until(&:stale?)` waits until the element goes stale.

## Actual Behavior -

An exception immediately occurs - "Can not check staleness of unused element"

## Steps to reproduce -

Run the following:

~~~~~~~~
require 'watir'

browser = Watir::Browser.new
e = browser.element
p e.exists?
#=> true
p e.stale?
#=> false
e.wait_until(&:stale?)
#=> C:/Ruby23/lib/ruby/gems/2.3.0/gems/watir-6.15.0/lib/watir/elements/element.rb:580:in `stale?': Can not check staleness of unused element (Watir::Exception::Error)
#=>   from C:/Ruby23/lib/ruby/gems/2.3.0/gems/watir-6.15.0/lib/watir/wait.rb:216:in `block in create_proc'
#=>   from C:/Ruby23/lib/ruby/gems/2.3.0/gems/watir-6.15.0/lib/watir/wait.rb:43:in `block in until'
#=>   from C:/Ruby23/lib/ruby/gems/2.3.0/gems/watir-6.15.0/lib/watir/wait.rb:87:in `block in run_with_timer'
#=>   from C:/Ruby23/lib/ruby/gems/2.3.0/gems/watir-6.15.0/lib/watir/wait/timer.rb:19:in `block in wait'
#=>   from C:/Ruby23/lib/ruby/gems/2.3.0/gems/watir-6.15.0/lib/watir/wait/timer.rb:18:in `loop'
#=>   from C:/Ruby23/lib/ruby/gems/2.3.0/gems/watir-6.15.0/lib/watir/wait/timer.rb:18:in `wait'
#=>   from C:/Ruby23/lib/ruby/gems/2.3.0/gems/watir-6.15.0/lib/watir/wait.rb:86:in `run_with_timer'
#=>   from C:/Ruby23/lib/ruby/gems/2.3.0/gems/watir-6.15.0/lib/watir/wait.rb:42:in `until'
#=>   from C:/Ruby23/lib/ruby/gems/2.3.0/gems/watir-6.15.0/lib/watir/wait.rb:126:in `wait_until'
#=>   from watir.rb:10:in `<main>'
~~~~~~~~

In 6.14, this would wait correctly - ie there would be a timeout error since the element doesn't go stale.

**Comment by jkotests** [comment]
This appears to be caused by the changes to [Waitable#create_proc](https://github.com/watir/watir/blob/bfa47ac17d2131d64a1c994bf739e2c5448c3b58/lib/watir/wait.rb#L213-L218). A `reset!` occurs at the beginning of the proc.

**Comment by titusfortner** [comment]
Well, that's both retrospectively obvious and unfortunate.

**Comment by titusfortner** [comment]
So... I'm not certain how to fix this, which, I certainly should have realized this was an issue when I tried to deprecate `#wait_while_present` and `#wait_until_present`.

I'm thinking maybe requiring a keyword `reset: true` if users need it? Like, it kind of should be default for dealing with present, but no way to know what is in the block ahead of time, and we do want to allow for `wait_until(&:stale?)`

**Comment by jkotests** [comment]
Does the need to `reset!` in `#wait_until(&:present?)` go away once we change `#present?` to re-locate stale elements?

**Comment by titusfortner** [comment]
oooh, excellent point. I'll try to play with it this weekend and verify.
