### ISSUE TITLE
Watir::Browser.new = nil:NilClass

### ISSUE THREAD

**Issue by shirley-purr** [watir/watir#821]
## Meta -
Watir Version: 6.15.0
Selenium Version: 3.11.0
OS Version: 10.14

## Expected Behavior -
browser = Watir::Browser.new
=> #<Watir::Browser:..

## Actual Behavior -
browser = Watir::Browser.new
=> NoMethodError: undefined method `[]' for nil:NilClass

It was running perfectly fine 10 minutes beforehand, and then this happened. Anyone have any ideas?

**Comment by titusfortner** [comment]
Are you running this as part of a test runner or just in irb? Can you provide a Stack Trace for the error?

**Comment by shirley-purr** [comment]
Hi @titusfortner,

It was part of a rake task and then I tried it in irb too and got the same response.

This is my Stack Trace in irb:
```
irb(main):005:0> require 'webdrivers'
=> false
irb(main):006:0> require 'watir'
=> false
irb(main):007:0> browser = Watir::Browser.new
Traceback (most recent call last):
        2: from (irb):7
        1: from (irb):7:in `new'
NoMethodError (undefined method `[]' for nil:NilClass)
```

**Comment by titusfortner** [comment]
Please set the following and rerun
```
Webdrivers.logger.level = :debug
Selenium::WebDriver.logger.level = :debug
```

**Comment by titusfortner** [comment]
I can not reproduce this and expect it is an issue with configuration on the system. If you still need help, please reach out to us in one of the ways specified here: http://watir.com/help/
