### ISSUE TITLE
Unable to locate certain elements under Watir 6.16 in headless-chrome. Works in 6.15 and 6.14.

### ISSUE THREAD

**Issue by dennismclaugh** [watir/watir#839]
## Meta -
Watir Version: 6.16 
Selenium Version: 3.141.0
Browser Version: Chromium 68.0.3440.75 
Browser Driver Version: ChromeDriver 2.38
OS Version: Alpine linux 3.8.1 (4.9.93-linuxkit-aufs)
Ruby: v2.5.2p104

## Expected Behavior -
When trying to locate all div elements using specific attributes in headless-chrome, Watir should return the correct number of items. 

## Actual Behavior -
0 (zero) items are returned when trying to return all div elements using specified attributes. 
**Only occurs when Chrome is run headless**. Works when a window is displayed.

## Steps to reproduce -
The following example will reproduce the error using Watir's website. I actually had this running within Docker because that's where I run my tests in headless mode. 
```
require 'watir'

Selenium::WebDriver::Chrome.driver_path = 'TestFramework/Drivers/chromedriver'
options = ::Selenium::WebDriver::Chrome::Options.new
options.add_argument('--headless')
options.add_argument('--no-sandbox')
options.add_argument('--disable-dev-shm-usage')
options.add_argument('--window-size=1600,1200')
options.add_argument('--ignore-certificate-errors')
browser = Watir::Browser.new :chrome, options: options

browser.goto 'http://watir.com'

elements = browser.divs(class: ['page','grid'], visible_text: 'Watir')   # This line finds nothing when using Watir 6.16. Should find 1 item.

puts 'Element count = ' + elements.count.to_s # Returns 0 under Watir 6.16. Returns 1 (as expected) under Watir 6.15 and 6.14.
```

This Dockerfile specifically installs Watir 6.16. If you were to install an earlier version of Watir (6.1.5 or earlier), then the test will return the correct number of elements (1, as expected)
**Dockerfile**:
```
FROM alpine:latest

# copy the automated tests into the container.
ADD . integration-test-framework

# For Alpine
RUN apk add --update --no-cache build-base libffi-dev ruby-dev ruby-rdoc zlib-dev chromium-chromedriver ruby-webrick

# install the Watir framework. 
# RUN gem install watir:6.14 minitest minitest-reporters shopify_api bigdecimal rake aws-sdk-s3 
RUN gem install watir:6.16 minitest minitest-reporters shopify_api bigdecimal rake aws-sdk-s3 

# Installs latest stable Chromium package.
RUN apk update && apk upgrade \
    && echo @latest-stable http://nl.alpinelinux.org/alpine/latest-stable/community >> /etc/apk/repositories \
    && echo @latest-stable http://nl.alpinelinux.org/alpine/latest-stable/main >> /etc/apk/repositories \
    && apk add --no-cache \
    chromium@latest-stable \
    nss@latest-stable \
    && rm -rf /var/lib/apt/lists/* \
    /var/cache/apk/* \
    /usr/share/man \
    /tmp/*

RUN rm /integration-test-framework/TestFramework/Drivers/chromedriver
RUN ln -s /usr/bin/chromedriver /integration-test-framework/TestFramework/Drivers/chromedriver

# Add webdriver as a user
RUN adduser -D webdriver \
    && chown -R webdriver:webdriver /integration-test-framework

# Switch to non-privileged user 'webdriver'
USER webdriver
WORKDIR /integration-test-framework

ENV CHROME_BIN=/usr/bin/chromium-browser \
    CHROME_PATH=/usr/lib/chromium/
```

Quick output when the above Ruby example script is run against 2 Docker images; one with Watir 6.15 and the other with 6.16.
```
➜  docker run -ti --entrypoint='/bin/sh' testimagewatir615
/integration-test-framework $ ruby watir_bug.rb
Element count = 1
/integration-test-framework $ 

➜  docker run -ti --entrypoint='/bin/sh' testimagewatir616
/integration-test-framework $ ruby watir_bug.rb
Element count = 0
/integration-test-framework $ 
```

**Comment by jkotests** [comment]
Inspecting the HTML of watir.com, I see 1 div with the class "page" and "grid". However, it doesn't have the visible text "Watir". It's the container around most of the content, so it includes the word "Watir" but doesn't exactly match. 0 matching elements seems right to me.

Am I looking at the wrong element?

Running the code against different Watir versions, it seems that it was a bug introduced in 6.14 but then fixed in 6.16:

~~~~~~~~
gem 'watir', '=6.11'     #=> 0
gem 'watir', '=6.12'     #=> 0
gem 'watir', '=6.13'     #=> 0
gem 'watir', '=6.14'     #=> 1
gem 'watir', '=6.15'     #=> 1
gem 'watir', '=6.15.1'  #=> 1
gem 'watir', '=6.16'     #=> 0
~~~~~~~~

**Comment by titusfortner** [comment]
Ugh, yeah, I created some Collections bugs in 6.14. The current behavior appears to work as intended. Use regular expressions for partial matching. 6.16 makes simple regular expressions very performant if you aren't just looking for what is visible.

This should do what you want:
```
browser.divs(class: ['page','grid'], visible_text: /Watir/)
```
This will be more performant:
```
browser.divs(class: ['page','grid'], text: /Watir/)
```

Let us know if there is something else going on here.
Thanks @jkotests for doing that analysis.

**Comment by dennismclaugh** [comment]
Using watir.com was just to illustrate the issue I'm seeing with my own internal app under test, but I think I understand. You're saying that any use of 'visible_text' is intended for text directly tied to the element that has class "page" and "grid", and not necessarily inside some other element contained therein, much like the "Watir" text in the rest of the watir.com page? 

So the resulting count of 1 is actually wrong; I thought it was correct as it fit my need when trying to locate the element(s) I was targeting. 

I'll try your suggestion with the regular expression. 
Thanks.

**Comment by titusfortner** [comment]
Yeah, the locators are additive.
Find me an element that has class "X" and class "Y" and when making a call to get displayed text, the result is "Z"

Sorry about any confusion
