### ISSUE TITLE
Tag_name parameter doesn't work after upgrading from 6.15.1 to 6.16.4

### ISSUE THREAD

**Issue by saratoga8** [watir/watir#842]
## Meta -
Watir Version: 6.16.4
Selenium Version: 3.141
Browser Version: Chrome 70.0.3538.77
Browser Driver Version: chromedriver=2.45.615279
OS Version: Linux 4.15.0-42-generic x86_64

## Expected Behavior -
 After clicking on a button some element appear within an element find by tag_name
 Wait until presence of the appeared element should execute
## Actual Behavior -
 The element has appeared but wait_until(&:present?) doesn't executed
 (IMHO the problem in using tag_name, because the use of css doesn't cause the problem)
## Steps to reproduce -
require 'watir'

browser = Watir::Browser.new

browser.goto 'https://github.com/session'
browser.wait
root = browser.element(css: '.application-main')
#form = browser.element(css: '.application-main form')

form = root.element(tag_name: 'form')

form.input(id: 'login_field').send_keys("usr")
form.input(id: 'password').send_keys("pwd")
form.input(name: 'commit').click

form.element(css: '.container button').wait_until(timeout: 5, &:present?)

browser.close

**Comment by titusfortner** [comment]
It isn't the tag_name parameter, it is the fact that it is a nested element. I memoized locator scope for re-use, but that is how we were removing @built parameter from list of elements to match, so it was treating @built like it was another attribute, which it obviously is not. I just need to make sure it gets deleted.
