### ISSUE TITLE
Use element find by id ,sometimes it will report "undefined method `[]' for nil"

### ISSUE THREAD

**Issue by LayTonQ** [watir/watir#844]
## Meta -
Watir Version: 6.14.0
Selenium Version: 3.13.0
Browser Version: IE 11.472.17134.0
Browser Driver Version: 3.4
OS Version: Win10 1803

## Expected Behavior -
Elements can be found
## Steps to reproduce -
The Code

require 'watir'
$driver = Watir::Browser.new :ie
$loginUrl = 'http://cardqa.i139.cn/doms_auth/login.jsp'
$driver.goto($loginUrl)
3.times do
    $driver.text_field(:name,"authUserName").set _loginNo
    $driver.text_field(:name,"authPassword").set _passWord
    $driver.input(:class,["inp_btn"]).click
    Watir::Wait.until{$driver.div(:id,"mainbox").font.exist?}
    if $driver.input(:name,"authUserName").value == "" && $driver.input(:name,"authUserName").exist?
      next
    end
    Watir::Wait.until{$driver.form(:id,"logForm").exist?}
    break
end

Sometimes,when i executed this code Watir::Wait.until{$driver.div(:id,"mainbox").font.exist?}, it was ok. 
But sometimes it will report "NoMethodError (undefined method `[]' for nil:NilClass)"
![nilclass](https://user-images.githubusercontent.com/37096930/50430324-41ca4080-08fe-11e9-9665-a59b3ae93208.png)

**Comment by titusfortner** [comment]
If that's your IE Driver version, you need to update it to match your selenium version. Can you update to the latest selenium version as well?

**Comment by LayTonQ** [comment]
I thought the IE driver version needed to match the IE version, just like the Chrome driver version.I downloaded the new IE driver, which solved my problem.Thank you

**Comment by Rajagopalan-M** [comment]
@LayTonQ IE stopped releasing their versions now. They have moved to Edge. So they are releasing only drivers whenever something is fixed. And also IE Driver is not released from Mircrosoft like Chrome driver is released from Google. It's released from Selenium Project.
