### ISSUE TITLE
Ruby 2.6

### ISSUE THREAD

**Issue by titusfortner** [watir/watir#845]
Trying to run watirspecs with Ruby 2.6 and it is failing for Chrome when it gets to this part:

https://github.com/watir/watir/blob/master/spec/watirspec/browser_spec.rb#L158

Comparison of relevant `$DEBUG` for 2.3, 2.5 & 2.6: https://gist.github.com/titusfortner/f514c378041b671cd668732c1f13b2bb

It's failing with childprocess. @p0deje can you duplicate this, any idea what the issue might be?

Also, this underscores how overly convoluted our spec implementation seems, but I also don't feel like digging into it. :)

Maybe I need to at least split out the tests that muck with starting/stopping new browsers with different settings.

**Comment by p0deje** [comment]
Hmm, can you make a plain Selenium work on 2.6? Start and stop driver?

**Comment by titusfortner** [comment]
Yes, and Thomas says Capybara specs are all passing as expected w/2.6. This is unlikely to be a big deal to our users, just... a reproducible weirdness that I can't explain.

**Comment by p0deje** [comment]
I checked and I can confirm that:

a) Selenium works just fine
b) Watir specs don't work

I can't see what could possibly cause this issue, so this definitely needs more research.

**Comment by Rajagopalan-M** [comment]
@titusfortner  Can I create a single exe for my WATIR project through Ruby 2.6 and can start running it because I heard that Ruby is including JIT compiler ?

**Comment by twalpole** [comment]
@Rajagopalan-M A JIT compiler is not what you think it is - https://en.wikipedia.org/wiki/Just-in-time_compilation

**Comment by Rajagopalan-M** [comment]
@twalpole  Yes but they say it prints C Code in the disk unlike traditional JIT compiler. You can read here "Unlike traditional JIT compilers which operate in-process, Ruby’s JIT compiler writes out C code to disk and spawns a common C compiler to generate native code"

**Comment by twalpole** [comment]
@Rajagopalan-M Yes, but that's only used while the program is running to generate chunks of native code that can be run instead of chunks of Ruby code - it does not produce an executable - It is a JIT compiler  (Just In Time) not what you're thinking of as a compiler (even though it uses what you're thinking of as a compiler to do part of the work).

**Comment by Rajagopalan-M** [comment]
@twalpole  yes but it prints the corresponding C Code to disk, Cant we take and compile via GCC compiler and produce the result exe file ?

**Comment by twalpole** [comment]
@Rajagopalan-M It doesn't compile the whole program, it is a JIT compiler - it only processes chunks of the code that get used often, aren't dynamic, and can benefit from being converted to native code -- It is not what you're thinking of as a compiler.   This has gone massively off-topic -- In short the answer is "No you can't" - If you can't accept that then you need to do a lot more reading on the topic of JIT compilers.

**Comment by Rajagopalan-M** [comment]
@twalpole  oh okay, actually Thomas, when we do project, we have to give the code part also to the client so It expose the coding part to them so they tend to modify and start using our coding , we couldn't hide our coding part, So can you let me know Is there any way I can give developed software without my coding part? For an example, when you use RubyMine, you are not seeing the coding part of RubyMine, you only see the software, Likewise can I do anything for my automated software in WATIR?

**Comment by titusfortner** [comment]
@Rajagopalan-M regardless, I ran the specs with it, just to see what it looks like. It is currently slower than not using it: https://travis-ci.org/watir/watir/builds/472370031 (1965.4 vs 1965.5)

**Comment by titusfortner** [comment]
> Is there any way I can give developed software without my coding part?

Not with an interpreted language like Ruby.

**Comment by Rajagopalan-M** [comment]
> 
> 
> @Rajagopalan-M regardless, I ran the specs with it, just to see what it looks like. It is currently slower than not using it: https://travis-ci.org/watir/watir/builds/472370031 (1965.4 vs 1965.5)

Okay.

**Comment by Rajagopalan-M** [comment]
> 
> 
> > Is there any way I can give developed software without my coding part?
> 
> Not with an interpreted language like Ruby.

So it seems like If we develop a project in Ruby, then our code part has to be exposed to the one for whom you are doing the project.
