### ISSUE TITLE
Watir::Wait::TimeoutError when trying to interact with the original window

### ISSUE THREAD

**Issue by Blackbaud-KimberlyHammer** [watir/watir#848]
## Meta -
Watir Version: 6.16.5
Selenium Version:  3.141.0
Browser Version: Firefox 57.0
Browser Driver Version: Using webdrivers 3.6.0 to get the latest driver
OS Version: Ubuntu

## Expected Behavior - 
We should still be able to locate and interact with elements in the original open window after closing a window we no longer need.

## Actual Behavior -
We often have to open up additional windows, run tests in those windows and then go back to the original window to continue running tests. When we use watir 6.10.2 in headless mode everything works great. When we try upgrading to 6.14.0 or 6.16.5, after we close a second window using browser.windows.last.close, we're unable to get the tests to interact with the original window in headless mode. We keep seeing Watir::Wait::TimeoutError when trying to locate elements in the original window.  I've tried the following, but nothing seems to work:
browser.windows.first.use
browser.windows.last.use
browser.driver.switch_to.window(browser.driver.window_handles[0]) 
browser.window(:title => /eTapestry/).use

Is there something else I need to do to be able to located and interact with elements in the window that is still open?

The original window we're trying to interact with does contain an iFrame browser.iframe(:id=>'etapContentIframe')

The only workaround I can find is to perform browser.refresh on the window I want to interact with, but this is not ideal.

**Comment by titusfortner** [comment]
Hi @Blackbaud-KimberlyHammer does this work Firefox non-headless? Are you using Headless gem or `ENV['MOZ_HEADLESS']`?

**Comment by Blackbaud-KimberlyHammer** [comment]
Thank you for the quick response @titusfortner. When I run the tests in Firefox non-headless it works if I only have the new window open for a very brief time. I'm able to reproduce the timeout error if the test is in the new window for a while before going back to the original window.  We are using the Headless gem.

When we use watir 6.10.2 it worked in both headless and non-headless modes regardless of how long we were in the new window.

**Comment by titusfortner** [comment]
Hmm, we haven't really changed anything windows related since 6.10.
Also, there really isn't anything that is affected by how long a window is open.

Are you using this with the watirmark gem, or is this a direct watir implementation?

It is possible (for 'reasons') that this will not do the right thing: `browser.windows.last.close`
For 2 windows my current recommendation is:
```
browser.window(new_window_opts).use
do_things_in_new_window
browser.window.close
browser.original_window.use
```

**Comment by Blackbaud-KimberlyHammer** [comment]
We are using the watirmark gem. I had tried the browser.original_window.use option previously without success. I went ahead and tried it again today with your recommendations, but unfortunately I'm still experiencing the same issue. 

It doesn't feel like a window issue, it feels more related to the present and stale changes maybe. Especially since it goes back to working if I refresh the browser on the window I want to use. If I get a chance tomorrow I will try to narrow down exactly which version it breaks in.

Do you know if there is a way to just refresh the iframe in a window? If I stick with the browser.refresh workaround then I'm going to have to change a number of workflows in our scenarios to account for being returned to the home page. If there is a way to just refresh/reload the iframe in the open browser then I'll remain on the appropriate page in the product and won't have to make a bunch of edits to our scenarios.

**Comment by titusfortner** [comment]
Hmm, maybe it isn't looking inside the iframe like it is supposed to. Switching to a window should return it to the top level browsing context, perhaps it isn't doing that automatically and Watir assumes it is. 

Can you log the flow and put it into a [gist](http://gist.github.com)? 
```
# this will show wire calls
Selenium::WebDriver.logger.level = :info
# this will show selector generation info & flow control info:
Watir.logger.level = :debug
```

Also, is it working for Chrome, or same issue?

**Comment by Blackbaud-KimberlyHammer** [comment]
Thanks so much for working on this with me. Unfortunately my role on the project using this tech stack has changed, so we're just going to go back to using watir 6.10.2. I'm going to go ahead and close this issue since I won't be able to continue working on it.
