### ISSUE TITLE
Tests (partially) fail in Gitlab CI but work locally

### ISSUE THREAD

**Issue by aloifolia** [watir/watir#851]
## Meta
Complete Gem List:

- ast (2.4.0)
- bigdecimal (1.2.8)
- childprocess (0.9.0)
- colorize (0.8.1)
- did_you_mean (1.0.0)
- diff-lcs (1.3)
- faraday (0.15.4)
- ffi (1.10.0)
- headless (2.3.1)
- io-console (0.4.5)
- jaro_winkler (1.5.2)
- json (1.8.3)
- mini_portile2 (2.4.0)
- minitest (5.8.4)
- multipart-post (2.0.0)
- net-telnet (0.1.1)
- net_http_ssl_fix (0.0.10)
- nokogiri (1.10.0)
- parallel (1.12.1)
- parser (2.5.3.0)
- power_assert (0.2.7)
- powerpack (0.1.2)
- psych (2.0.17)
- rainbow (3.0.0)
- rake (10.5.0)
- rdoc (4.2.1)
- regexp_parser (1.3.0)
- rspec (3.8.0)
- rspec-core (3.8.0)
- rspec-expectations (3.8.2)
- rspec-mocks (3.8.0)
- rspec-support (3.8.0)
- rubocop (0.62.0)
- ruby-progressbar (1.10.0)
- rubyzip (1.2.2)
- selenium-webdriver (3.141.0)
- test-unit (3.1.7)
- unicode-display_width (1.4.1)
- watir (6.16.5)
- watir-rspec (3.0.0)
- watir-scroll (0.4.0)
- webdriver-highlighter (0.1.0)
- webdrivers (3.6.0)

Browser Version: Chromium 71.0.3578.98
OS Version: Ubuntu 16.04

## Expected Behavior 
I have test setup that works flawlessly when I run the tests on my local machine. So I expect that this test suite should on other machines, as well.

## Actual Behavior 
When started locally, all tests pass, no error is thrown. When I run the same tests in our Gitlab CI I get errors for some tests because elements cannot be found. If I inspect the content of the parent element (with `puts parent_elem.inner_html`) which is used to search for nested elements, I see that these children actually exist.

## Error message and source code

This is the code which causes the failure:

```ruby
    elem = parent_elem.div(text: 'some random text')
    elem.wait_until_present # this fails
```

And this is the error output:

```
Failures:

  1) MyTest: [Insert some description here]
     Failure/Error: MyModule.select_stuff(browser)

     Watir::Wait::TimeoutError:
       timed out after 10 seconds, waiting for #<Watir::Div: located: false; {:tag_name=>"parent-elem"} --> {:text=>"parent text", :tag_name=>"div"} --> {:text=>"more text", :tag_name=>"div"}> to become present
     # /var/lib/gems/2.3.0/gems/watir-6.16.5/lib/watir/wait.rb:46:in `until'
     # /var/lib/gems/2.3.0/gems/watir-6.16.5/lib/watir/wait.rb:125:in `wait_until'
     # /var/lib/gems/2.3.0/gems/watir-6.16.5/lib/watir/wait.rb:183:in `wait_until_present'
     # ./tests/my_test.rb:17:in `block (2 levels) in <top (required)>'
```

**Comment by titusfortner** [comment]
I don't have any way to reproduce this error, and this is very unlikely to be a bug in Watir.

The most likely cause for tests working locally and not working remotely is some kind of timing issue. I would want to troubleshoot by looking at screenshots and seeing if the logs of Selenium calls (`Selenium::WebDriver.logger.level = :info`) tell us anything. 

Let's continue this discussion either [on Slack](https://goo.gl/9o4J3Y) (find us in #watir channel), or on the [mailing list](https://groups.google.com/forum/#!forum/watir-general).

**Comment by aloifolia** [comment]
I am quite certain that this is a Watir bug. The error occurs with Watir 6.16.5, but not with Watir 6.14.0. For me, it happens when I 
1. select an HTMLElement (with a browser.().()... selector) and save it in a variable `foo`
2. click on some subelement of `foo` which changes the DOM tree (via an angular ng-if attribute) such that a new element appears
3. **re-use** `foo` to find the element that appeared in step 2

To avoid the error I need to avoid the re-use of `foo` by constructing a selector starting from `browser` again. 

So... this fails:

```ruby
foo = browser.div(text: 'foo')
foo.div(class: 'abc').fire_event :click # changes ng-if value => <bar>...</bar> appears
foo.element(tag_name: 'bar').fire_event :click # element cannot be found
```

But this works:
```ruby
foo = browser.div(text: 'foo')
foo.div(class: 'abc').fire_event :click # changes ng-if value => <bar>...</bar> appears
browser.div(text: 'foo').element(tag_name: 'bar').fire_event :click # 🎉
```

My guess is selectors starting from `foo` operate on an outdated version of the DOM because `foo` is set to time-wise fixed version of the DOM.

**Comment by titusfortner** [comment]
This is different from what you originally posted. Seeing a difference between versions is useful information, but I still can't duplicate this issue. 

There is a behavioral difference with 6.16 when it comes to nested elements, but I'm not sure how it correlates to what you are seeing. Instead of locating the parent, and then locating the child underneath, Watir is building a locator for the child from the root of the document directly. So, it shouldn't matter the cacheing of the parent, or any changes to the DOM. One potential issue is if there are elements in the DOM that aren't being displayed.

Does it make a difference if it is `#click` vs `#fire_event`? Does it make a difference if you use `visible_text` instead of `text` as a locator?

**Comment by titusfortner** [comment]
Ah, thanks @jkotests for the reproducible case. This is not a bug, this is working as desired.

After clicking on that element, there no longer exists an element at:
```
browser.div(text: 'foo').element(tag_name: 'bar')
```

You can read the reasoning for this change here: http://watir.com/staleness-changes/

It is unfortunate that this is a breaking change and we didn't have a deprecation warning for it. Ideally we would have waited until Watir 7 for that to happen, but I did not foresee this use case. 

At this point, you can switch to using a regular expression to get this to work:
```
browser.div(text: /foo/).`element(tag_name: 'bar')
```
