### ISSUE TITLE
Browser#execute_script does not wait for stale argument elements to exist

### ISSUE THREAD

**Issue by jkotests** [watir/watir#853]
## Meta -
Watir Version: 6.16.5
Selenium Version: 3.141.0
Browser Version: Chrome 72.0.3626.96
Browser Driver Version: Chromedriver 2.46
OS Version: Windows 10

## Expected Behavior -

`Browser#execute_script` waits for all elements in the arguments Array to exist.

## Actual Behavior -

`Browser#execute_script` times out if any of the elements are stale.

## Steps to reproduce -

Given a page with a select list:

~~~~~~~~
<html>
  <body>
    <select id="ctl00_ctl00_BC_MC_MainTS_AA_ViewOptions">
        <option>A</option>
        <option>B</option>
    </select>
  </body>
</html>
~~~~~~~~

Getting the text of a stale select list will time out:

~~~~~~~~
select = browser.select_list
select.exists?
browser.refresh
select.text
#=> C:/Ruby24/lib/ruby/gems/2.4.0/gems/watir-6.16.5/lib/watir/wait.rb:46:in `until': timed out after 30 seconds, waiting for true condition on #<Watir::Select: located: true; {:tag_name=>"select"}> (Watir::Wait::TimeoutError)
#=> 	from C:/Ruby24/lib/ruby/gems/2.4.0/gems/watir-6.16.5/lib/watir/wait.rb:125:in `wait_until'
#=> 	from C:/Ruby24/lib/ruby/gems/2.4.0/gems/watir-6.16.5/lib/watir/browser.rb:218:in `block in execute_script'
#=> 	from C:/Ruby24/lib/ruby/gems/2.4.0/gems/watir-6.16.5/lib/watir/browser.rb:217:in `map!'
#=> 	from C:/Ruby24/lib/ruby/gems/2.4.0/gems/watir-6.16.5/lib/watir/browser.rb:217:in `execute_script'
#=> 	from C:/Ruby24/lib/ruby/gems/2.4.0/gems/watir-6.16.5/lib/watir/js_snippets.rb:13:in `execute_js'
#=> 	from C:/Ruby24/lib/ruby/gems/2.4.0/gems/watir-6.16.5/lib/watir/elements/select.rb:139:in `block in selected_options'
#=> 	from C:/Ruby24/lib/ruby/gems/2.4.0/gems/watir-6.16.5/lib/watir/elements/element.rb:789:in `element_call'
#=> 	from C:/Ruby24/lib/ruby/gems/2.4.0/gems/watir-6.16.5/lib/watir/elements/select.rb:139:in `selected_options'
#=> 	from C:/Ruby24/lib/ruby/gems/2.4.0/gems/watir-6.16.5/lib/watir/elements/select.rb:129:in `text'
~~~~~~~~

**Comment by jkotests** [comment]
This started failing in v6.16.0 due to #828, which changed `#execute_script` to wait for elements to exist. (Note that `Select#text` uses `#execute_script`.)

~~~~~~~~
    def execute_script(script, *args)
      args.map! do |e|
        e.is_a?(Element) ? e.wait_until(&:exists?).wd : e
      end

      wrap_elements_in(self, @driver.execute_script(script, *args))
    end
~~~~~~~~

However, the root of the problem actually seems to be the change in `Element#exists?` during v6.11.0.beta1. We made a change such that stale elements would no longer be re-located (#719).

~~~~~~~~
    def exists?
      return false if @element && stale?
      assert_exists
      true
    rescue UnknownObjectException, UnknownFrameException
      false
    end
~~~~~~~~

@titusfortner , do you remember why we changed the re-locating behaviour for `#exists?`? It seems strange that we made a backwards incompatible change there - and we seem to have intentionally done as there was even a spec change. Yet the notes for v7.0 is to go back to re-locating?

**Comment by kapoorlakshya** [comment]
Thanks for investigating this! I appreciate the detailed write-up.

**Comment by titusfortner** [comment]
I haven't had a chance to dig into the code at all the past couple weeks due to work issues. All I can say is that all of our specs continue to pass when we release, so if there is a non-backward compatible behavior then we need to document it in a spec.

**Comment by jkotests** [comment]
The funny thing is that we did document the change in the specs. We explicitly changed the spec from (6.10.3):

~~~~~~~~
it "relocates element from a collection when it becomes stale" do
  watir_element = browser.divs(id: "text").first
  expect(watir_element).to exist

  browser.refresh

  expect(watir_element).to exist
end
~~~~~~~~

To (in 6.11.0.beta1):

~~~~~~~~
it "element from a collection returns false when it becomes stale" do
  element = browser.divs(id: "text").first.tap(&:exists?)

  browser.refresh

  expect(element).to be_stale
  expect(element).to_not exist
end
~~~~~~~~

**Comment by titusfortner** [comment]
"funny" sure. I feel like I'm being so careful and then randomly do stuff like this... I'll try to dig into it over the weekend.

**Comment by titusfortner** [comment]
This should have been fixed by: https://github.com/watir/watir/commit/e036ffaa5d63e8c54c56c630ab7cba2f0bdce463
