### ISSUE TITLE
How to deal with waiting when fetching multiple elements?

### ISSUE THREAD

**Issue by woacademy** [watir/watir#854]
## Meta -
Watir Version: `6.16.5`
Selenium Version: `3.141.0`
Browser Version: Chrome `72.0.3626.96`
Browser Driver Version: ChromeDriver `2.45.615291`
OS Version: Windows 7 Enterprise SP1 (`7601`)

## Behavior -
I'm dealing with a website that uses [Apache Wicket](https://wicket.apache.org/) to load a table with an AJAX request after the user performs a search. Since I'd like to loop through each row of this table I presumed I'd be able to use something like this:
```ruby
@browser.trs(class: 'example').each do |tr|
  puts tr.html
end
```
However, it seems the waiting behaviour varies between selecting one element and more than one element as I don't get any output with the above code. Whereas, when I select the first row I do get its HTML:
```ruby
puts @browser.tr(class: 'example').html
```
Is there a preferred way to deal with this?

## Steps to reproduce -

The page appears on a licenced IP telephony portal, I wouldn't know where to start creating an example page that demonstrates this.

**Comment by jkotests** [comment]
There is currently no built-in waiting for element collections. I've been thinking of stealing Capybara's idea of having min/max count locators.

In the mean time, you will have to manually wait until the elements exist:

~~~~~~~~
@browser.tr(class: 'example').wait_until(&:present?)
@browser.trs(class: 'example').each do |tr|
  puts tr.html
end
~~~~~~~~

**Comment by titusfortner** [comment]
Yeah, since we can't know ahead of time what you are going to be doing with an element collection element, there's no way for us to know when to wait.

Hmm, I thought I'd added Waitable to collections. Theoretically we should let users do:

```
@browser.trs(class: 'example').wait_until(&:any?).each  do |tr|
  puts tr.html
end

@browser.trs(class: 'example').wait_until { |collection| collection.size > 3 }.each do |tr|
  puts tr.html
end
```

I wonder if I tried and ran into a problem with it.

@jkotests - `:min_count` and `:max_count` locators for Collections could be interesting as well.

**Comment by titusfortner** [comment]
This should have been fixed by: https://github.com/watir/watir/commit/e036ffaa5d63e8c54c56c630ab7cba2f0bdce463
