### ISSUE TITLE
watir not setting selenium script timeout

### ISSUE THREAD

**Issue by aver-joefleck** [watir/watir#860]
## Meta -
Watir Version: 6.16.5
Selenium Version: 3.141.0
Browser Version: 72.0.3626.121
Browser Driver Version: 2.42.591059 (a3d9684d10d61aa0c45f6723b327283be1ebaad8)
OS Version: Mojave 10.14.3

## Expected Behavior -
doubling the default selenium script timeout of 30 to 60 seconds.
@browser = Watir::Browser.new(:chrome, timeouts: { script: 60_000 }, options: @opts)
## Actual Behavior -
script fails at default time.
Selenium::WebDriver::Error::ScriptTimeOutError:
script timeout: result was not received in 30 seconds
(Session info: headless chrome=72.0.3626.121)
(Driver info: chromedriver=2.42.591071 (0b695ff80972cc1a65a5cd643186d2ae582cd4ac),platform=Linux 4.14.97-74.72.amzn1.x86_64 x86_64)
/var/lib/gems/2.4.0/gems/page-object-2.2.4/lib/page-object/platforms/watir/page_object.rb:1066:in `instance_eval'
/var/lib/gems/2.4.0/gems/selenium-webdriver-3.14.0/lib/selenium/webdriver/remote/response.rb:32:in `initialize'
/var/lib/gems/2.4.0/gems/selenium-webdriver-3.14.0/lib/selenium/webdriver/remote/http/common.rb:84:in `new'
/var/lib/gems/2.4.0/gems/selenium-webdriver-3.14.0/lib/selenium/webdriver/remote/http/common.rb:84:in `create_response'
/var/lib/gems/2.4.0/gems/selenium-webdriver-3.14.0/lib/selenium/webdriver/remote/http/default.rb:104:in `request'
/var/lib/gems/2.4.0/gems/selenium-webdriver-3.14.0/lib/selenium/webdriver/remote/http/common.rb:62:in `call'
/var/lib/gems/2.4.0/gems/selenium-webdriver-3.14.0/lib/selenium/webdriver/remote/bridge.rb:164:in `execute'
 /var/lib/gems/2.4.0/gems/selenium-webdriver-3.14.0/lib/selenium/webdriver/remote/oss/bridge.rb:584:in `execute'
/var/lib/gems/2.4.0/gems/selenium-webdriver-3.14.0/lib/selenium/webdriver/remote/oss/bridge.rb:274:in `execute_async_script'
/var/lib/gems/2.4.0/gems/selenium-webdriver-3.14.0/lib/selenium/webdriver/common/driver.rb:230:in `execute_async_script'
/var/lib/gems/2.4.0/gems/watir_angular-0.4.0/lib/watir_angular.rb:13:in `wait_for_angular'
/var/lib/gems/2.4.0/gems/watir_angular-0.4.0/lib/watir_angular.rb:18:in `block in inject_wait'
/var/lib/gems/2.4.0/gems/watir-6.14.0/lib/watir/after_hooks.rb:70:in `block in run'
/var/lib/gems/2.4.0/gems/watir-6.14.0/lib/watir/after_hooks.rb:100:in `block in each'
/var/lib/gems/2.4.0/gems/watir-6.14.0/lib/watir/after_hooks.rb:100:in `each'
/var/lib/gems/2.4.0/gems/watir-6.14.0/lib/watir/after_hooks.rb:100:in `each'
/var/lib/gems/2.4.0/gems/watir-6.14.0/lib/watir/after_hooks.rb:70:in `run'
/var/lib/gems/2.4.0/gems/watir-6.14.0/lib/watir/elements/element.rb:142:in `click'
(eval):1:in `process_watir_call'
/var/lib/gems/2.4.0/gems/page-object-2.2.4/lib/page-object/platforms/watir/page_object.rb:1066:in `instance_eval'
/var/lib/gems/2.4.0/gems/page-object-2.2.4/lib/page-object/platforms/watir/page_object.rb:1066:in `process_watir_call'
/var/lib/gems/2.4.0/gems/page-object-2.2.4/lib/page-object/platforms/watir/page_object.rb:472:in `click_button_for'
/var/lib/gems/2.4.0/gems/page-object-2.2.4/lib/page-object/accessors.rb:435:in `block in button'
/spec/asset_debugger_spec.rb:85:in `block (3 levels) in <top (required)>'

## Steps to reproduce -
@browser = Watir::Browser.new(:chrome, timeouts: { script: 60_000 }, options: @opts)

**Comment by titusfortner** [comment]
At least with latest Watir/Selenium you can see it is getting set and returned correctly by looking at: `Selenium::WebDriver.logger.level = :info`

If the behavior is not matching the capabilities returned from the browser, then we might need to ask the chromedriver team.
