### ISSUE TITLE
Selenium::WebDriver::Remote::Capabilities does not have #dig method (TypeError)

### ISSUE THREAD

**Issue by Blackbaud-JagjeetChadha** [watir/watir#865]
Since yesterday's my test cases started failing with 
Error: Selenium::WebDriver::Remote::Capabilities does not have #dig method (TypeError). 

Can anyone knows what steps I should take to resolve the issue? Please urgent help is required.

**Comment by twalpole** [comment]
Short term - lock to Selenium-webdriver 3.141.0

**Comment by Blackbaud-JagjeetChadha** [comment]
@twalpole  - I am not sure how to lock to Selenium-webdriver 3.141.0. Can you share steps for that? And what is causing the issue. My project is using Ruby with Watir.

**Comment by titusfortner** [comment]
update your gem file to use:
```
gem 'selenium-webdriver', '= 3.141.0'
```
You can also check in your Gemfile.lock and use `bundle install` instead of `bundle update`

**Comment by Blackbaud-JagjeetChadha** [comment]
@titusfortner - Thank you so much. It resolved the issue.

**Comment by cameronheard** [comment]
FYI: I can no longer produce this issue with selenium-webdriver 3.142.0.

**Comment by Blackbaud-JagjeetChadha** [comment]
@cameronheard - Thank you Cameron. I will try with 3.142.0 as well.
