### ISSUE TITLE
Selenium::WebDriver::Error::NoAlertPresentError is deprecated

### ISSUE THREAD

**Issue by chadcodes** [watir/watir#868]
## Meta -
Watir Version: 6.16.5
Selenium Version: 3.142.0
Browser Version: latest chromedrvier through webdrivers gem
Browser Driver Version: 
OS Version: Mac OS 10.13.6

## Behavior -
WARN Selenium [DEPRECATION] Selenium::WebDriver::Error::NoAlertPresentError is deprecated. Use Selenium::WebDriver::Error::NoSuchAlertError (ensure the driver supports W3C WebDriver specification) instead.

Recently updated watir / selenium and I started to get the errors mentioned above.  I can't tell if the deprecation warning is coming from Watir or Selenium.  

Has anyone run into this issue?  Any resolution, or is there any way to quiet the deprecation warning for now?

**Comment by kapoorlakshya** [comment]
@chadcodes Check out the discussion in #867.

**Comment by Rajagopalan-M** [comment]
Goto error.rb

comment that exception here

![image](https://user-images.githubusercontent.com/31696622/57549852-4dd10f00-7382-11e9-8c64-f64871cf5313.png)

**Comment by titusfortner** [comment]
Do not monkey patch Selenium.

The issue is that Chrome itself is throwing an exception in the latest version of Selenium. Either set Selenium to v3.141.0, or turn on w3c mode in Chrome to avoid this exception.

The next version of watir will likely swallow these exceptions for Chrome specifically, but I haven't gotten there yet.

**Comment by chadcodes** [comment]
I didn't want to monkey patch unless it was a last resort honestly.  Thanks for the feedback on this issue.  

~~How do I set the selenium version to 3.141.0 or turn on w3c mode, I'm not quite sure.  I was pretty sure I'm on 3.141.0 at the moment but maybe not if I'm catching this error.~~

I managed to force selenium-webdriver down to 3.141.0 and it's working.  I don't know if I did this correctly but I did gem uninstall selenium-webdriver for all version past 3.141.0.  Then deleted my Gemfile.lock.  Added this line in the group :test `gem 'selenium-webdriver', '3.141.0'`.  Then bundle install.  Not sure this is the correct way but seems to work so far.

If there is a better solution please let me know.

**Comment by kapoorlakshya** [comment]
@chadcodes

```ruby
Watir::Browser.new(:chrome, options: { options: { w3c: true } })
```

**Comment by chadcodes** [comment]
> ```ruby
> Watir::Browser.new(:chrome, options: { options: { w3c: true } })
> ```

I was unsuccessful with this line, thanks though.  I think the issue is good to close now.
