### ISSUE TITLE
Chrome - "unhandled inspector error" when calling #click! on a link nested inside an iframe.

### ISSUE THREAD

**Issue by kapoorlakshya** [watir/watir#869]
## Meta -
Watir Version: 6.16.5
Selenium Version: 3.142.2 (Reproduced in v4 alpha2 as well)
Browser Version: Chrome 74.0.3729.131 (No error in IE 11)
Browser Driver Version: Chromedriver 74.0.3729.6
OS Version: Windows 10 Build 1709

**Note**: This may not be specific to `watir` and could be a `selenium-webdriver` issue. Posting this here after discussing with Titus to give him all the info he needs to decide where to fix this.

## Expected Behavior

A link nested inside an iframe should be clicked without errors when calling `#click!` on it. Calling `click` does not raise any errors.

Please put down your pitchforks :) - I know `click!` should not be used. This was in an old test running on IE 11 that we recently ran on Chrome and caught this error. The test has been updated to use `click` and it passes now.

## Actual Behavior

When `click!` is called on a link nested inside an iframe, an error is raised AND the link is clicked.

```
unknown error: unhandled inspector error: {"code":-32000,"message":"Cannot find context with specified id"}
        (Session info: chrome=74.0.3729.131)
        (Driver info: chromedriver=74.0.3729.6 (3c16f8a135abc0d4da2dff33804db79b849a7c38),platform=Windows NT 10.0.17134 x86_64) (Selenium::WebDriver::Error::UnknownError)
```

**Simplified Watir Code**

```ruby
browser = Watir::Browser.new :chrome, options: { options: { w3c: true } }
browser.goto 'https://app-host01/PresTier'

# A test step opens a new window

browser.windows.last.use

# More steps to get to the iframe 

Selenium::WebDriver.logger.level  = :info
Selenium::WebDriver.logger.output = 'selenium.log'
lnk = browser.iframe(src: /SearchPage_Procedure/).table(id: 'ctl00_PV_ProcedureLookupConrol_ProcedureResultsPanel_ctl01').tr(class: 'GridRow_BasicGrid').link(text: '1000', visible: true)
lnk.click! # Raises error
```

Selenium log from the above code:

`click` - https://gist.github.com/kapoorlakshya/97b3ecd99a3fbb0399c5268300384b2f

`click!` - https://gist.github.com/kapoorlakshya/8fb738190f9137eff6aa18f94081b15e

**Comment by titusfortner** [comment]
I can't reproduce this, and since it is "just" `#click!` I'm going to call it "wont-fix"
