### ISSUE TITLE
Desired Capabilities Are Not Applied to a Remote Chrome Instance

### ISSUE THREAD

**Issue by darkogj** [watir/watir#870]
I'm using all the latest versions of Selenium, Watir, Linux.

Basically, I want to start the window maximized. So if I do things using the traditional Watir "opts" method, I get

`args = ['--start-maximized']`
`b = Watir::Browser.new :chrome, options: {args: args}, url: "http://localhost:4444/wd/hub"`

which doesn't work.

If I try this, however, everything works well:

`caps = Selenium::WebDriver::Remote::Capabilities.chrome("chromeOptions" => {"args" => [ "--start-maximized" ]})`
`b = Watir::Browser.new :chrome, :desired_capabilities => caps, url: "http://localhost:4444/wd/hub"`

but I get a warning:

> WARN Watir ["use_capabilities"] You can pass values directly into Watir::Browser opt without needing to use :desired_capabilities

It seems like Watir does not recognize when you want to start a Selenium Hub option and doesn't adjust the desired options appropriately.

**Comment by mark0203** [comment]
My setup: 

- Windows 10
- Chrome 74
- Ruby 2.5.5
- Watir 6.16.5

I'm always a bit at a loss when it comes to capabilities and how to pass them properly.
But I do notice the same, the switches only work for the local browser, not for a remote session.
I tried: 
```Ruby
url = 'http://0.0.0.0:4444/wd/hub'
```
```Ruby
b = Watir::Browser.new :chrome, url: url, switches: %w[--start-maximized]
``` 
```Ruby
args = ['--start-maximized']
b = Watir::Browser.new :chrome, url: url, args: args
```
```Ruby
caps{}
caps[:url] = "http://0.0.0.0:4444/wd/hub"
caps[:args] = ["--start-maximized"]
b = Watir::Browser.new :chrome, caps
```
All of these examples do start the browser in the grid, but not maximized.
Here `http://watir.com/guides/chrome/` I do not see an example of the combination of remote and maximized window, most likely I don't pass them properly.
What I always do instead (and that works like a charm) is after starting the browser, I do:
```Ruby
b.window.maximize
```

**Comment by jstefek** [comment]
I have the same problem.

Was trying to instantiate the remote browser with `Chrome::Options`.

I had a short dig into it.
The problematic parts could be https://github.com/watir/watir/blob/master/lib/watir/capabilities.rb#L105-L115 which ignores `browser_options` from line 71 (https://github.com/watir/watir/blob/master/lib/watir/capabilities.rb#L71)

Plus https://github.com/watir/watir/blob/master/lib/watir/capabilities.rb#L107 does not uses the correct key used in newer versions of chrome, which should be `Selenium::WebDriver::Chrome::Options::KEY`

Unfortunately, even when these ^^ are fixed, it seems it still does not go through. I blame https://github.com/SeleniumHQ/selenium/blob/master/rb/lib/selenium/webdriver/remote/bridge.rb#L45

However, the Watir::Browser could be instantiated with a webdriver instance, so you should be able to do: `Watir::Browser.new(Selenium::WebDriver.for :chrome, url: <url>, options: <Chrome::Options>)` (see https://github.com/SeleniumHQ/selenium/wiki/Ruby-Bindings#command-line-switches)

**Comment by titusfortner** [comment]
Yup, Capabilities has so many bugs that I have no idea what I was thinking when I released it.
I'm finally fixing it in Watir 6.19

For now, this is the best way:
```ruby
opts = Selenium::WebDriver::Options::Chrome.new(args: ["--start-maximized"])
b = Watir::Browser.new :remote, url: url, options: opts
```

**Comment by titusfortner** [comment]
These have all been fixed, (switches at the top level is now deprecated, though). Also chrome is now default, so you can do:
```ruby
b = Watir::Browser.new options: {args: args}, url: "http://localhost:4444/wd/hub"
```
