### ISSUE TITLE
Net::ReadTimeout Error for Chrome on Ubuntu

### ISSUE THREAD

**Issue by aashish** [watir/watir#873]
I am getting the **timeout error** with following on Ubuntu, though Chrome browser is starting.

```
2.4.1 :011 > require 'watir'
 => false 
2.4.1 :012 > 
2.4.1 :013 >   browser = Watir::Browser.new
Net::ReadTimeout: Net::ReadTimeout
	from (irb):13:in `new'
	from (irb):13
2.4.1 :014 > 
```

ChromeDriver started
```
$ chromedriver 
Starting ChromeDriver 75.0.3770.90 (a6dcaf7e3ec6f70a194cc25e8149475c6590e025-refs/branch-heads/3770@{#1003}) on port 9515
Only local connections are allowed.
Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.
```

Any idea?

**Comment by titusfortner** [comment]
Sorry for the late reply.
I don't have a good way to reproduce this.

Generally:
1. make sure Chrome is installed
2. make sure chrome version & chromedriver versions are matched (use webdrivers gem for this to be automatic)
3. You can try `$DEBUG = true` to see more of what is going on, but I'm not sure what more that will tell you.
