### ISSUE TITLE
Window matches? method return nil? when passing absolute url 

### ISSUE THREAD

**Issue by ypatel-reflektive** [watir/watir#880]
## Meta -
Watir Version: 6.16.5
Selenium Version:  3.142.3
Browser Version: Version 76.0.3809.132
Browser Driver Version: ChromeDriver 76.0.3809.126
OS Version: MacOs 10.14.6 

## Expected Behavior
window matches? method must return true

## Actual Behavior
https://github.com/watir/watir/blob/9e63367b9f35a65e629fd98ab39fec022b8d3603/lib/watir/window.rb#L232
`@browser.url =~ /#{@selector[:url]}/`
return `nil` even url string same.

## Steps to reproduce
Assume:
```
@browser.url = "http://localhost:3001/app?email=test.com#"
@selector[:url] = "http://localhost:3001/app?email=test.com#"
```

NOTE: I am trying upgrade Watir gem from v.6.11.0 to 6.16.5.
Found below difference:  
``v.6.11.0``
https://github.com/watir/watir/blob/49bd10f87d3f6470bcdc3b0c35d4a45d436b8d4d/lib/watir/window.rb#L238

``v6.16.5``
https://github.com/watir/watir/blob/9e63367b9f35a65e629fd98ab39fec022b8d3603/lib/watir/window.rb#L232

**Comment by ypatel-reflektive** [comment]
I would appreciate if anyone please help me with this issue? or let me know if we have any workaround so that i can unblock myself with gem upgrade.

Thanks

**Comment by kapoorlakshya** [comment]
@ypatel-reflektive I think the match is failing because of the way the `:url` is escaped by `#{}`: 

```ruby
irb(main):053:0> a = "http://localhost:3001/app?email=test.com#"
=> "http://localhost:3001/app?email=test.com#"
irb(main):054:0> b = /#{"http://localhost:3001/app?email=test.com#"}/
=> /http:\/\/localhost:3001\/app?email=test.com#/
irb(main):055:0> a.match? b
=> false
```

 Using `Regexp.escape` fixes this:

```ruby
irb(main):046:0> a = "http://localhost:3001/app?email=test.com#"
=> "http://localhost:3001/app?email=test.com#"
irb(main):047:0> b = Regexp.escape "http://localhost:3001/app?email=test.com#"
=> "http://localhost:3001/app\\?email=test\\.com\\#"
irb(main):048:0> a.match? b
=> true
```

So what exactly are you doing that is blocked by this?

**Comment by ypatel-reflektive** [comment]
> @ypatel-reflektive I think the match is failing because of the way the `:url` is escaped by `#{}`:
> 
> ```ruby
> irb(main):053:0> a = "http://localhost:3001/app?email=test.com#"
> => "http://localhost:3001/app?email=test.com#"
> irb(main):054:0> b = /#{"http://localhost:3001/app?email=test.com#"}/
> => /http:\/\/localhost:3001\/app?email=test.com#/
> irb(main):055:0> a.match? b
> => false
> ```
> 
> Using `Regexp.escape` fixes this:
> 
> ```ruby
> irb(main):046:0> a = "http://localhost:3001/app?email=test.com#"
> => "http://localhost:3001/app?email=test.com#"
> irb(main):047:0> b = Regexp.escape "http://localhost:3001/app?email=test.com#"
> => "http://localhost:3001/app\\?email=test\\.com\\#"
> irb(main):048:0> a.match? b
> => true
> ```
> 
> So what exactly are you doing that is blocked by this?

Thanks @kapoorlakshya :+1:  I am unblocked using Using `Regexp.escape` 

I am going to close this issue.

**Comment by ypatel-reflektive** [comment]
Using Regexp.escape i am able to unblock myself, hence closing this issue.
