### ISSUE TITLE
Recent version of selenium is not allowing watir to wait for visibility of the element

### ISSUE THREAD

**Issue by Rajagopalan-M** [watir/watir#887]
I used the recent version of selenium 3.142.7/3.142.6 it's not waiting for element visibility, it's immediately throwing the following error

`Watir::Exception::UnknownObjectException`

But when I switch back to my old version of selenium 3.142.3, it's working properly.

@p0deje @jkotests @titusfortner  Can you please look into this problem?

**Comment by jkotests** [comment]
@Rajagopalan-M , can you please provide an example (code and HTML)?

**Comment by titusfortner** [comment]
closing until we have something reproducible.
