### ISSUE TITLE
Error When Trying to Run Ruby Gem

### ISSUE THREAD

**Issue by Pamela454** [watir/watir#894]
## Meta -
Watir Version: 6.16.5
Selenium Version: 
Browser Version: Version 78.0.3904.70 (Official Build) (64-bit)
Browser Driver Version: 
OS Version: 10.11.6 (15G22010)

**Comment by titusfortner** [comment]
I'm not sure what I can do with this issue since I'm not familiar with `UrgentCare::Scraper::Watir` class.

If you are still having an issue, I'd recommend posting to stack-overflow and tagging it with watir.
