### ISSUE TITLE
Would it be useful to add an examples/ directory?

### ISSUE THREAD

**Issue by rubyFeedback** [watir/watir#899]
Hello there watir devs,

I found watir recently, indirectly, through this blog post:

https://blog.unexist.dev/2020/10/07/lessons-learned.html

This seemed quite useful or interesting. I'd actually like to
use watir as a way to log in to a remote website, and then
register there for an upcoming exam (it is a university 
website, a local website).

I am not sure if watir is usable for this task; right now I am
totally clueless about it really. :)

I learn best from studying examples, though, and trying
things out on my own. This is what has brought me to
this feature request:

- Would it be useful or helpful if some examples/ directory
could be added, that shows some examples? In particular
the basic ones, but also a few more advanced use cases?

The watir users could perhaps maintain the code for these
examples and add patches or something. Right now I am
a bit lost as to how to learn watir best (hopefully that does
not sound too lazy, but I need to distribute my time as to what
I can do on a given day, so I try to be "efficient" when that is
possible). Please feel free to close this issue at any moment
in time for any reason.

**Comment by titusfortner** [comment]
Watir works for scraping and task automation, though it's designed purpose and focus is on testing applications

Take a look at the guides on our Website: http://watir.com/guides/
If you have more questions, you can reach out to us in the Watir channel on Selenium Slack or on the Watir email list: http://watir.com/help/

Thanks for pointing out the blog post.
