### ISSUE TITLE
javascript error: Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by Rajagopalan-M** [watir/watir#900]
When I am trying to find the element which is in the ShadowDom, it's throwing the below error

> javascript error: Cannot read property 'toLowerCase' of undefined

I observed that this error happens only when I am calling `.shadowRoot`. I couldn't locate the element in the shadow dom because of the aforementioned error. 

I have written the following code.

> element=browser.execute_script("document.querySelectorAll('.login-panel')[0].shadowRoot")

When I am checking in the browser console, the following query `document.querySelectorAll('.login-panel')[0].shadowRoot` works perfectly.

**Comment by titusfortner** [comment]
Yeah, technically WebDriver does not support ShadowDom, so neither does Selenium which means neither does Watir. I think @jkotests started looking into options for how to work with ShadowDom, but since it is explicitly not currently supported, I'm closing this as a bug.
