### ISSUE TITLE
Headless chrome browser throwing timeout error while normal browser is working

### ISSUE THREAD

**Issue by sp2410** [watir/watir#903]
## Meta -
Watir Version: 6.7.0
Selenium Webdriver Version: 3.6
Browser Version: 87
Browser Driver Version: ChromeDriver 87.0.4280.20
OS Version: macOS Catalina 10.15.7 (19H2)

## Expected Behavior -
No error or time out (no issue with the headless: false option)

## Actual Behavior -
Getting a `timed out after 30 seconds, waiting for #<Watir::TextField: located: false; {:name=>"username", :tag_name=>"input", :index=>0}> to be located`
## Steps to reproduce -
```
args = %w[--no-sandbox
      --disable-dev-shm-usage
      --ignore-certificate-errors
      --disable-popup-blocking
      --disable-translate
      --disable-gpu
      --headless]

    options = {
      binary: ENV['GOOGLE_CHROME_BIN'],
      prefs: { password_manager_enable: false, credentials_enable_service: false },
      args: args
    }

    @browser = Watir::Browser.new(:chrome, options: options)
    @browser.goto("https://www.instagram.com/accounts/login/")
@browser.text_fields(name: 'username').first.set(ENV['IG_USERNAME'])
```

**Comment by titusfortner** [comment]
Headless & Shadow DOM don't mix well.
You can use `browser.execute_script` with `shadowRoot.querySelector()`, but you'll have to explore those options.
