### ISSUE TITLE
Element not found when matching :text with Regexp and text content includes leading/trailing whitespace

### ISSUE THREAD

**Issue by jkotests** [watir/watir#924]
## Meta -
Watir Version: 7.0.0.beta1
Selenium Version: 4.0.0.beta2
Browser Version: Chrome 89.0.4389.90
Browser Driver Version: Chromedriver 89.0.4389.90
OS Version: Windows 10

## Expected Behavior -

`browser.link(text: /^link text?/)` should match the element:

~~~~~~~~
		<a>
			<span>link text</span>
		</a>
~~~~~~~~

This works successfully in 6.19.1.

## Actual Behavior -

It does not match.

## Steps to reproduce -

Given the page:

~~~~~~~~
<html>
	<body>
		<a>
			<span>link text</span>
		</a>
	</body>
</html>
~~~~~~~~

The element is not matched:

~~~~~~~~
browser.link(text: /^link text?/).exists?
2021-03-24 01:46:11 INFO Watir Converted {:text=>/^link text?/, :tag_name=>"a"} to {:text=>/^link text?/, :xpath=>".//*[local-name()='a'][contains(normalize-space(), 'link tex')]"}
2021-03-24 01:46:11 DEBUG Watir Iterating through 1 elements to locate {:text=>/^link text?/, :tag_name=>"a"}
2021-03-24 01:46:11 INFO Watir Executing Script on Browser: getTextContent
=> false
~~~~~~~~

Other similar locators are able to find the element:

~~~~~~~~
browser.link(text: 'link text').exists?     #=> true
browser.link(text: /link text/).exists?     #=> true
browser.link(text: /^link text/).exists?    #=> true
browser.link(text: /link text?/).exists?    #=> true
browser.link(text: /^link text?/).exists?   #=> false
~~~~~~~~

I believe the problem is the handling of leading/trailing spaces. When `:text` is fully converted to `:xpath`, the text comparison uses `normalise-space()` which strips the leading/trailing spaces. In contrast, when `:text` cannot be converted to `:xpath`, the Regexp is compared to text content that includes the leading/trailing spaces.

**Comment by titusfortner** [comment]
This was the behavior we decided on: http://watir.com/watir-6-10/#locating-elements-by-text
Using `:text` locator with a `Regexp` now locates based on everything in the DOM, not just visible text.

It's "bad" that we didn't figure out how to throw a deprecation notice for this, but the answer is to switch to using `:visible_text`

**Comment by jkotests** [comment]
@titusfortner , not sure I follow your response. I agree that `:text` should match all the text in the DOM. In this case, all of the text is visible, so `:text` and `:visible_text` should really produce the same thing.

The issue here is that `:text` using `Regexp` returns different things based on whether the `Regexp` could be completely converted to `:xpath` or not:

~~~~~~~~
browser.link(text: /^link text/).exists?    #=> true (was completely converted to :xpath)
browser.link(text: /^link text?/).exists?   #=> false (could not be completed converted to :xpath)
~~~~~~~~

Why should the act of adding the `?` (ie the last "t" being optional) in the second example cause the element to no longer be found?

**Comment by titusfortner** [comment]
The content of the DOM is whatever is returned from `execute_js(:getTextContent, element)`

In this case it includes additional whitespace characters (`"\n link text\n "`).

I'm ok stripping white space from "visible text" but I don't think we should do so from "text".

**Comment by titusfortner** [comment]
Also, I may not have had the exact same reproduction case as you, even though I copy/pasted what you had into a file.
In my reproduction the carat was a problem and the question mark was not

**Comment by titusfortner** [comment]
merged fix
