### ISSUE TITLE
uninitialized constant Watir::VERSION

### ISSUE THREAD

**Issue by aaron-humerickhouse** [watir/watir#930]
## Meta -
Watir Version:  7.0.0.beta2 and 6.19.1, this is all I tested
Selenium Version: 4
Browser Version: all browsers
Browser Driver Version: all drivers
OS Version: OSX

## Expected Behavior -
Browser starts

## Actual Behavior -
Error is thrown: `uninitialized constant Watir::VERSION`

## Steps to reproduce -
```
[1] pry(main)> require 'watir'
true
[2] pry(main)> require 'webdrivers'
true
[3] pry(main)> browser = Watir::Browser.new
NameError: uninitialized constant Watir::VERSION
from /Users/aaron/.rvm/gems/ruby-2.6.5/gems/watir-7.0.0.beta2/lib/watir/http_client.rb:4:in `request'
```

Adding `require_relative './version` to `lib/watir/http_client.rb` allowed me to get around the issue locally.

**Comment by titusfortner** [comment]
Hmm, I can't duplicate this. As of 6.19, `require 'watir/version'` was added to `lib/watir.rb`, so it should already be loaded by the first line.

**Comment by aaron-humerickhouse** [comment]
https://github.com/watir/watir-rails/issues/32

Someone else ran into it and reported it in a different repo

**Comment by aaron-humerickhouse** [comment]
This is interesting:
```
❯ pry
[1] pry(main)> require 'watir'
true
[2] pry(main)> require 'webdrivers'
true
[3] pry(main)> browser = Watir::Browser.new
NameError: uninitialized constant Watir::VERSION
from /Users/aaron/.rvm/gems/ruby-2.6.5/gems/watir-7.0.0.beta2/lib/watir/http_client.rb:4:in `request'
[4] pry(main)> exit

❯ gem uninstall watir-rails
Successfully uninstalled watir-rails-2.2.2

❯ pry
[1] pry(main)> require 'watir'
true
[2] pry(main)> require 'webdrivers'
true
[3] pry(main)> browser = Watir::Browser.new
#<Watir::Browser:0x4e3687e47280a50a url="data:," title="">
```

Clearly there's a conflict with the `watir-rails` gem, I'll elaborate over there.
