### ISSUE TITLE
Elements search with negative 'class' attribute value is not working correctly

### ISSUE THREAD

**Issue by nkumarreviews** [watir/watir#934]
Elements search with negative 'class' attribute value is not working correctly

## Steps to reproduce -
I ran below lines of code on irb prompt. iam searching for divs with no class name as ''seat" but in the returned elements's attribute still showing the excluded class names

irb(main):065:0> b.divs(class:["slots-box",**"!seat"**])[0].attributes
=> {"_ngcontent-unr-c119"=>"", :class=>"slots-box **seat** ng-star-inserted", :placement=>"top", :show_delay=>"100", :theme=>"light", :tooltip=>"Fully Booked"}

**Comment by titusfortner** [comment]
Thanks for reporting this!

Adding Wait functionality to elements meant changing how things were stored, so we were ending up calling `#build` on the selector twice, and the first time mutated the selector.

Fix released in 7.0.0.beta4
