### ISSUE TITLE
Deprecation warning for focused? method

### ISSUE THREAD

**Issue by kiran-borole** [watir/watir#945]
watir version 5.0.0
watir-webdriver version - 0.9.3
page-object - 1.2.0

Not sure what is wrong here, We are getting Deprecation warning for focused? method on below line of code : 

expect(@current_page.send(field_name).focused?).to eq(expectation)

Note : field_name is element name with _element

Warning : 

*** You are calling a method named focused? at /home/ciamci/jenkins/workspace/code-review-acceptance-tests/acceptance-tests/features/step_definitions/base_steps.rb:411:in `block in <top (required)>'.
*** This method does not exist in page-object so it is being passed to the driver.
*** This feature will be removed in the near future.
*** Please change your code to call the correct page-object method.
*** If you are using functionality that does not exist in page-object please request it be added.

**Comment by jkotests** [comment]
You are not doing anything wrong. 

This deprecation warning is actually raised by Page-Object not Watir. I don't remember the exact reason for why we raised this warning but we eventually ended keeping the automatic passing of methods - ie today's current version of Page-Object is expected to pass methods to the driver (Watir).

You can ignore the warning, but I'd still suggest considering upgrading the Watir and Page-Object gems to latest.

**Comment by kiran-borole** [comment]
@jkotests : Thank you for response. Is there any way, we can suppress the warnings till the time we will upgrade gems. Also  I would prefer to know the reason to behind this warning if you are able to recollect somehow.

**Comment by jkotests** [comment]
@kiran-borole , my best guess for the warning was that Page-Object wanted tighter control over the methods available to `PageObject::Elements::Element`. Automatically forwarding methods (using `method_missing`) to the underlying driver, which could be a Watir or Selelnium-WebDriver element, meant that people using different drivers could get different results. For example, this could lead to a Watir user having access to a method that a Selenium-WebDriver user did not. Page-Object eventually changed to only using Watir as the underlying driver, so we are once again forwarding missing methods to the underlying `Watir::Element`.

For removing the warning, there isn't a configurable option. The most you can do is monkey-patch Page-Object to remove the warning:

```
require 'page-object'

# Monkey patch to remove deprecation warnings in method_missing
module PageObject
  module Elements
    class Element
      def method_missing(*args, &block)
        m = args.shift
        begin
          element.send m, *args, &block
        rescue Exception => e
          raise
        end
      end
    end
  end
end
```

**Comment by titusfortner** [comment]
@jkotests we're going to release Watir 7 likely this next month. Is there anything we can do in Watir/Page Object to fix this (or any other issues) before release?

**Comment by titusfortner** [comment]
Oh just looked at the version, this is likely already dealt with a long time ago. :)

@kiran-borole we can't really fix something from a gem that is 5 years out of date. Please update to Watir 7, and let us know if there's any help we can provide.

**Comment by kiran-borole** [comment]
Sure, will update versions and let you know if need any help. Appreciate your quick responses, Thanks a lot

**Comment by kiran-borole** [comment]
Just to share quick solution on this issue : 
expect(@current_page.send(field_name).**element**.focused?).to eq(expectation)
