### ISSUE TITLE
Watir Download File  at specific loaction using Chrome - The provided code in the Watir official page is not working as expected. 

### ISSUE THREAD

**Issue by SP8890** [watir/watir#950]
## Meta -
Watir Version: watir (7.0.0, 6.19.1)
Selenium Version:  - 
Browser Version:  tried using Chrome 94,95,96 
Browser Driver Version:   tried with windows 94,95,96
OS Version: Windows 10

## Expected Behavior - The File should download according to the code mentioned in the official page of watir, 

prefs = {
  download: {
    prompt_for_download: false,  
    default_directory: '/path/to/dir'
  }
}

[Please note  :  Changing syntax is also not working, means not downloading file as expected location.
    prefs = {
  :download => {
    :prompt_for_download => false,
    :default_directory => download_path
  }
}
]

b = Watir::Browser.new :chrome, options: {prefs: prefs}

## Actual Behavior -

Not downloading file as expected location.

## Steps to reproduce -

- Already mentioned above.

**Comment by titusfortner** [comment]
There was a Selenium bug, so make sure you are using the latest patch release.

**Comment by SP8890** [comment]
hi, As I mentioned, it's a latest version : watir (7.0.0, 6.19.1) but doesn't works. or I understand something wrong. please advise. 
Thanks

**Comment by titusfortner** [comment]
Yes, watir 7 requires selenium 4. Please make sure you also are using Selenium 4.0.3.

**Comment by SP8890** [comment]
As you can see below when I got - gem list  in my console; 

Watir  - 7.0.0,6.19.1
Selenium - 4.0.3 
---------------------------------------

readline (default: 0.0.2)
regexp_parser (2.1.1)
reline (default: 0.1.5)
require_all (3.0.0)
rexml (3.2.5, default: 3.2.3.1)
rspec (3.10.0)
rspec-core (3.10.1)
rspec-expectations (3.10.1)
rspec-mocks (3.10.2)
rspec-support (3.10.2)
rss (default: 0.2.8)
rubyzip (2.3.2, 1.3.0)
sdbm (default: 1.0.0)
**selenium-webdriver (4.0.3)**
singleton (default: 0.1.0)
stringio (default: 0.1.0)
strscan (default: 1.0.3)
sys-uname (1.2.2)
test-unit (3.3.4)
testgen (1.0)
thor (1.1.0)
thread_safe (0.3.6)
timeout (default: 0.1.0)
tracer (default: 0.1.0)
tzinfo (2.0.4)
uri (default: 0.10.0)
**watir (7.0.0, 6.19.1)**
webdriver (0.19.0)
webdrivers (4.6.1)
 --------------------------------------

Please advise 
Thanks

**Comment by SP8890** [comment]
any update?

**Comment by SP8890** [comment]
no comments.
