### ISSUE TITLE
Watir 7.0.0 not honoring Firefox `headless` option

### ISSUE THREAD

**Issue by chrismcmahon** [watir/watir#951]
## Meta -
Watir Version: 7.0.0
Selenium Version: 4.0.3
Browser Version: any recent Firefox
Browser Driver Version: geckodriver 29 and 30
OS Version: Mac and Windows

## Expected Behavior -

Starting Firefox with option `headless: false` should not throw an error 

`Invalid moz:firefoxOptions field headless (Selenium::WebDriver::Error::InvalidArgumentError)`

## Actual Behavior -

Find above error on the command line and tests fail

## Steps to reproduce -

<img width="732" alt="Screen Shot 2021-11-02 at 3 07 52 PM" src="https://user-images.githubusercontent.com/204643/139963542-7a02e3a2-533b-4abc-a652-97b67bcd2fcb.png">

**Comment by titusfortner** [comment]
Headless is a slightly special case here, since we are doing a custom modification of options instead of it being an option itself:
http://watir.com/guides/capabilities/#headless

To run in headless mode, you can either:
```ruby
browser_opts = {
  accept_insecure_certs: true,
  args = ['-headless']
}
@browser = Watir::Browser.new :firefox, options: browser_opts
```
or
```ruby
browser_opts = {
  accept_insecure_certs: true,
}
@browser = Watir::Browser.new :firefox, headless: true, options: browser_opts
```

`headless: false` will also work here.
