### ISSUE TITLE
prefs.profile.default_content_setting_values does nothing

### ISSUE THREAD

**Issue by osadasami** [watir/watir#955]
Watir Version: `7.1.0`
Selenium Version: don't know where to check it
Browser Version: `98.0.4758.80`
Browser Driver Version: `ChromeDriver 98.0.4758.80`
OS Version: `10.15.7`

## Expected Behavior -

I want to run Chrome without images. I tried to use this setup

```ruby
Watir::Browser.new(
  :chrome,
  options: {
    prefs: {
      profile: {
        default_content_setting_values: {
          images: 2
        }
      }
    }
  }
)
```

Go to `chrome://settings/content/images` and expect `Don't allow sites to show images` to be checked but it's not

I tries different settings like

```ruby
Watir::Browser.new(
  :chrome,
  options: {
    prefs: {
      'profile.default_content_setting_values.images' => 2
    }
  }
)
```

```ruby
Watir::Browser.new(
  :chrome,
  options: {
    prefs: {
      'profile' => {
        'default_content_setting_values' => {
          'images' => 2
        }
      }
    }
  }
)
```

But nothing works

**Comment by titusfortner** [comment]
Does this work? https://stackoverflow.com/a/35128928/4072371

**Comment by osadasami** [comment]
This did not disable images

```ruby
Watir::Browser.new(
  :chrome,
  options: {
    prefs: {
      profile: {
        managed_default_content_settings: {
          images: 2
        }
      }
      'profile.managed_default_content_settings.images' => 2
    }
  }
)
```

But this disabled it

```ruby
Watir::Browser.new(
  :chrome,
  options: {
    args: [
      '--blink-settings=imagesEnabled=false',
    ],
  }
)
```

@titusfortner Thank you. Did waste a lot of time to finally get it working
