### ISSUE TITLE
Cannot locate element by css class if TAB character is present in front of class name

### ISSUE THREAD

**Issue by tbone2k-git** [watir/watir#956]
## Meta -
Watir Version: 7.1.0
Selenium Version:  v0.0 (I don't know)
Browser Version: v95.0.4638.54
Browser Driver Version: 95.0.4638.17
OS Version: Win7Pro

## Expected Behavior -
Find element with css class, which has a leading tab-character in front. Leading tab character before css class happens easily when trying to format html code and html attributes into multiple lines for readability and/or IDEs converting leading spaces to tabs.

## Actual Behavior -
Watir does not "see" individual css class, if they are separated by tab-character from other css classes.

## Steps to reproduce -
Create button element like this (note the TAB (\t) charachter in front of "active" css class)..
`<button type="button" value="printall" id="printall" class="btn btn-default we_btn	active">All</button>`

Or create button with class attribute value spread onto two lines with leading TABs.
```
<button type="button"
	value="printall"
	id="printall"
	class="alotof css classes go into this attribute value thats why we need to break the line here
		active the IDE will insert TABs to the front of this line leading to problem">
	All
</button>
```
Try to locate element with:
$b.button(id: 'printall', class: 'active') 
It will fail.

**Comment by titusfortner** [comment]
fixed in b1f9aed0736ae60a7b0ce8da90ecd52dfd1cee1e

**Comment by tbone2k-git** [comment]
Awesome, thank you very much! o)

**Comment by titusfortner** [comment]
@tbone2k-git you're welcome. Sorry it took so long.

**Comment by tbone2k-git** [comment]
@titusfortner
Providing some kind of support for the project by filing bugs and eventually getting a fix, is fun and worth being patient!..
Thanks again! o)
