### ISSUE TITLE
Select#includes(regex) breaks when regex contains a single quote (')

### ISSUE THREAD

**Issue by SteveRawlinson** [watir/watir#957]
## Meta -
Watir Version:  7.1.0
Selenium Version:  4.1.0
Browser Version: Chrome 98.0.4758.102
Browser Driver Version: 
OS Version: Ubuntu 20.04

## Expected Behavior -

Select#includes?(/regex/) should not throw an exception when the regex contains a quote mark (')

## Actual Behavior -

Throws an exception like this:

Selenium::WebDriver::Error::InvalidSelectorError ... [contains(normalize-space(), 'O'Rourke')] is not a valid XPath expression.

## Steps to reproduce -

```
select = browser.select(name: 'foo')
select.includes?(/O'Rourke/) # => Selenium::WebDriver::Error::InvalidSelectorError
```

**Comment by titusfortner** [comment]
fixed in c1eaf79ac7e5d844802d3c4862ac7fde328bd3c3
