### ISSUE TITLE
How to get selenium selector from watir element ?

### ISSUE THREAD

**Issue by rtcoms** [watir/watir#959]
Planning to use this for an enterprise application and to convince the management I want to show that we can easily port our test to selenium if required in future.

Is there an easy way to get selenium selector for  Watr Element

## Meta -
Watir Version: 6.1
Selenium Version: 4.1

Currently, I'm getting something like following

```
login_page.username_element
#<PageObject::Elements::TextField:0x00007f7fd6068940 @element=#<Watir::TextField: located: false; {:id=>"user_login", :tag_name=>"input"}>, @platform=#<PageObject::Platforms::Watir::PageObject:0x00007f7fd6068918 @browser=#<Watir::TextField: located: false; {:id=>"user_login", :tag_name=>"input"}>>>
(byebug) login_page.username_element.element
#<Watir::TextField: located: false; {:id=>"user_login", :tag_name=>"input"}>
(byebug) login_page.username_element.element.wd
#<Selenium::WebDriver::Element:0x..fb7c7ff2e30aa3b22 id="55e03ca9-e026-444d-842a-9115e4cf53e5">
```

I expected `wd` to return Selenium element with selector, similar to Watir elements but that is not what I'm getting here.

**Comment by titusfortner** [comment]
Selenium doesn't store selectors, only an ID provided by the driver. This is one of the reasons for wrapping Selenium elements with a library like Watir. `#wd` returns the wrapped instance of the Selenium element, which includes everything about that element. 

Watir stores the webdriver locator in the `Locator` class instance which can be obtained using `#locator`. In simple cases, the `@built` variable stores the XPath value, but it won't be complete unless the `@locator_scope` variable is also a `Browser` instance.
