### ISSUE TITLE
Verify You Are Human

### ISSUE THREAD

**Issue by daBee** [watir/watir#965]
## Meta -
Watir Version: `7.2.2`
Selenium Version: `selenium-webdriver (4.8.0)`
Browser Version: `109.0.5414.119`
Browser Driver Version: `109.0.5414.74%`
OS Version: `MacOS Ventura 13.2`

## Expected Behavior -
I thought I should be able to get into my current chatgpt session.  

## Actual Behavior -
Cloudflare has me check a checkbox saying I am human, then it checks my browser, then it returns to the Human checkbox.  I cannot progress past this.  

## Procedure - 
```
s = 'https://chat.openai.com/chat/30129d6f-<stuff>'
Watir.default_timeout = 30
a = Watir::Browser.new(:chrome, headless: false)
a.goto s
a.window.move_to(0,0)
a.window.resize_to(1200, 1600)
sleep 20             # this is where I try to make this work manually, but it cycles.
```

The site knows that this `Watir` browser/agent is not good.

**Comment by titusfortner** [comment]
If the site is explicitly trying to prevent users from accessing it with automaton tools, it sounds like it is working as intended.

**Comment by daBee** [comment]
Yes, I wasn't debating that.  There is no way to find out what that is?

**Comment by titusfortner** [comment]
I tend to avoid helping people with solutions that violate a site's terms of service, and this tool is for tracking code problems not general support.

**Comment by daBee** [comment]
Ah I see.  Well, from the looks of it, it isn't clear what the issue is.  Hence the post here.
