### ISSUE TITLE
Cookie httpOnly

### ISSUE THREAD

**Issue by noraj** [watir/watir#967]
[Cookie add method](https://rubydoc.info/gems/watir/Watir/Cookies#add-instance_method) as an option `secure` that I believe will set the `secure` attribute on the cookie, but there is no option to control the `httpOnly` attribute.

Ref. https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie

**Comment by titusfortner** [comment]
Looks like we're also missing `sameSite` support - https://w3c.github.io/webdriver/#cookies

Would you like to make a Pull Request? Looks like the values just need to be added to this Hash - https://github.com/watir/watir/blob/main/lib/watir/cookies.rb#L57-L71
